/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[8] = {0, 8, 16, 24, 32, 39, 46, 53};
static const casadi_int casadi_s5[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s6[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s7[8] = {1, 9, 17, 25, 33, 40, 47, 54};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s9[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s10[8] = {2, 10, 18, 26, 34, 41, 48, 55};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s12[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s13[8] = {3, 11, 19, 27, 35, 42, 49, 56};
static const casadi_int casadi_s14[3] = {0, 1, 2};
static const casadi_int casadi_s15[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s16[12] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
static const casadi_int casadi_s17[12] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
static const casadi_int casadi_s18[4] = {1, 0, 3, 2};
static const casadi_int casadi_s19[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s20[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s21[7] = {4, 12, 20, 28, 36, 43, 50};
static const casadi_int casadi_s22[4] = {2, 3, 0, 1};
static const casadi_int casadi_s23[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s24[7] = {5, 13, 21, 29, 37, 44, 51};
static const casadi_int casadi_s25[4] = {3, 2, 1, 0};
static const casadi_int casadi_s26[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s27[7] = {6, 14, 22, 30, 38, 45, 52};
static const casadi_int casadi_s28[90] = {30, 30, 0, 0, 0, 0, 0, 0, 0, 8, 16, 24, 32, 39, 46, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 57, 57, 57, 57, 6, 7, 8, 9, 10, 11, 12, 26, 6, 7, 8, 9, 10, 11, 12, 26, 6, 7, 8, 9, 10, 11, 12, 26, 6, 7, 8, 9, 10, 11, 12, 26, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9, 10, 11, 12, 6, 7, 8, 9};
static const casadi_int casadi_s29[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s30[3] = {0, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* quadrotor_impl_dae_hess:(i0[13],i1[13],i2[4],i3[],i4[13],i5[13])->(o0[30x30,57nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+4, *w1=w+61, *w2=w+74, *w3=w+78, *w4=w+87, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+125, *w21=w+138, *w22=w+142, *w23=w+146, *w24=w+150, *w25=w+154, *w26=w+158, *w27=w+167, *w28=w+170, *w29=w+173, *w30=w+176, *w31=w+179, *w32=w+182, *w33=w+191, *w34=w+200, *w35=w+209, *w36=w+218, *w37=w+222, *w38=w+226, *w39=w+235, *w40=w+244, *w41=w+248, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, *w56=w+266, *w57=w+282, *w58=w+298, *w59=w+302, w60, w61, w62, w63, w64, w65, w66, w67, *w84=w+314, *w85=w+328, *w86=w+336, *w87=w+345, *w89=w+348, *w90=w+355;
  /* #0: @0 = zeros(30x30,57nz) */
  casadi_clear(w0, 57);
  /* #1: @1 = zeros(13x1) */
  casadi_clear(w1, 13);
  /* #2: @2 = zeros(4x1) */
  casadi_clear(w2, 4);
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = ones(30x1,23nz) */
  casadi_fill(w4, 23, 1.);
  /* #5: {NULL, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@4) */
  w5 = w4[6];
  /* #6: @6 = sparsity_cast(@5) */
  casadi_copy((&w5), 1, (&w6));
  /* #7: @7 = input[0][0] */
  w7 = arg[0] ? arg[0][0] : 0;
  /* #8: @8 = input[0][1] */
  w8 = arg[0] ? arg[0][1] : 0;
  /* #9: @9 = input[0][2] */
  w9 = arg[0] ? arg[0][2] : 0;
  /* #10: @10 = input[0][3] */
  w10 = arg[0] ? arg[0][3] : 0;
  /* #11: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #12: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #13: @13 = input[0][6] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #14: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #15: @15 = input[0][8] */
  w15 = arg[0] ? arg[0][8] : 0;
  /* #16: @16 = input[0][9] */
  w16 = arg[0] ? arg[0][9] : 0;
  /* #17: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #18: @18 = input[0][11] */
  w18 = arg[0] ? arg[0][11] : 0;
  /* #19: @19 = input[0][12] */
  w19 = arg[0] ? arg[0][12] : 0;
  /* #20: @20 = vertcat(@7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w20;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #21: @21 = @20[6:10] */
  for (rr=w21, ss=w20+6; ss!=w20+10; ss+=1) *rr++ = *ss;
  /* #22: @7 = ||@21||_F */
  w7 = sqrt(casadi_dot(4, w21, w21));
  /* #23: @8 = (@6/@7) */
  w8  = (w6/w7);
  /* #24: @22 = dense(@8) */
  casadi_densify((&w8), casadi_s0, w22, 0);
  /* #25: @23 = (@21/@7) */
  for (i=0, rr=w23, cr=w21; i<4; ++i) (*rr++)  = ((*cr++)/w7);
  /* #26: @24 = (@23/@7) */
  for (i=0, rr=w24, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)/w7);
  /* #27: @8 = project(@21) */
  casadi_sparsify(w21, (&w8), casadi_s0, 0);
  /* #28: @9 = dot(@8, @6) */
  w9 = casadi_dot(1, (&w8), (&w6));
  /* #29: @9 = (@9/@7) */
  w9 /= w7;
  /* #30: @25 = (@24*@9) */
  for (i=0, rr=w25, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #31: @22 = (@22-@25) */
  for (i=0, rr=w22, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #32: @8 = @22[3] */
  for (rr=(&w8), ss=w22+3; ss!=w22+4; ss+=1) *rr++ = *ss;
  /* #33: @8 = (-@8) */
  w8 = (- w8 );
  /* #34: (@3[3] += @8) */
  for (rr=w3+3, ss=(&w8); rr!=w3+4; rr+=1) *rr += *ss++;
  /* #35: @8 = 0 */
  w8 = 0.;
  /* #36: (@3[6] = @8) */
  for (rr=w3+6, ss=(&w8); rr!=w3+7; rr+=1) *rr = *ss++;
  /* #37: @8 = @22[2] */
  for (rr=(&w8), ss=w22+2; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #38: (@3[6] += @8) */
  for (rr=w3+6, ss=(&w8); rr!=w3+7; rr+=1) *rr += *ss++;
  /* #39: @8 = 0 */
  w8 = 0.;
  /* #40: (@3[7] = @8) */
  for (rr=w3+7, ss=(&w8); rr!=w3+8; rr+=1) *rr = *ss++;
  /* #41: @8 = @22[1] */
  for (rr=(&w8), ss=w22+1; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #42: @8 = (-@8) */
  w8 = (- w8 );
  /* #43: (@3[7] += @8) */
  for (rr=w3+7, ss=(&w8); rr!=w3+8; rr+=1) *rr += *ss++;
  /* #44: @8 = 0 */
  w8 = 0.;
  /* #45: (@3[1] = @8) */
  for (rr=w3+1, ss=(&w8); rr!=w3+2; rr+=1) *rr = *ss++;
  /* #46: @8 = @22[3] */
  for (rr=(&w8), ss=w22+3; ss!=w22+4; ss+=1) *rr++ = *ss;
  /* #47: (@3[1] += @8) */
  for (rr=w3+1, ss=(&w8); rr!=w3+2; rr+=1) *rr += *ss++;
  /* #48: @8 = 0 */
  w8 = 0.;
  /* #49: (@3[2] = @8) */
  for (rr=w3+2, ss=(&w8); rr!=w3+3; rr+=1) *rr = *ss++;
  /* #50: @8 = @22[2] */
  for (rr=(&w8), ss=w22+2; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #51: @8 = (-@8) */
  w8 = (- w8 );
  /* #52: (@3[2] += @8) */
  for (rr=w3+2, ss=(&w8); rr!=w3+3; rr+=1) *rr += *ss++;
  /* #53: @8 = 0 */
  w8 = 0.;
  /* #54: (@3[5] = @8) */
  for (rr=w3+5, ss=(&w8); rr!=w3+6; rr+=1) *rr = *ss++;
  /* #55: @8 = @22[1] */
  for (rr=(&w8), ss=w22+1; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #56: (@3[5] += @8) */
  for (rr=w3+5, ss=(&w8); rr!=w3+6; rr+=1) *rr += *ss++;
  /* #57: @26 = zeros(3x3) */
  casadi_clear(w26, 9);
  /* #58: @8 = input[2][0] */
  w8 = arg[2] ? arg[2][0] : 0;
  /* #59: @20 = input[4][0] */
  casadi_copy(arg[4], 13, w20);
  /* #60: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<13; ++i) *rr++ = (- *cs++ );
  /* #61: {NULL, @27, @25, @28} = vertsplit(@20) */
  casadi_copy(w20+3, 3, w27);
  casadi_copy(w20+6, 4, w25);
  casadi_copy(w20+10, 3, w28);
  /* #62: @29 = (@8*@27) */
  for (i=0, rr=w29, cs=w27; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #63: @30 = zeros(3x1) */
  casadi_clear(w30, 3);
  /* #64: @8 = 1 */
  w8 = 1.;
  /* #65: (@30[2] = @8) */
  for (rr=w30+2, ss=(&w8); rr!=w30+3; rr+=1) *rr = *ss++;
  /* #66: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #67: @26 = mac(@29,@31,@26) */
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w31+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #68: @8 = dot(@3, @26) */
  w8 = casadi_dot(9, w3, w26);
  /* #69: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #70: (@2[0] += @8) */
  for (rr=w2+0, ss=(&w8); rr!=w2+1; rr+=1) *rr += *ss++;
  /* #71: @8 = @22[0] */
  for (rr=(&w8), ss=w22+0; ss!=w22+1; ss+=1) *rr++ = *ss;
  /* #72: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #73: @32 = (@26*@8) */
  for (i=0, rr=w32, cr=w26; i<9; ++i) (*rr++)  = ((*cr++)*w8);
  /* #74: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #75: @34 = (2.*@26) */
  for (i=0, rr=w34, cs=w26; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #76: @35 = @3' */
  for (i=0, rr=w35, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #77: @33 = mac(@34,@35,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #78: @32 = (@32+@33) */
  for (i=0, rr=w32, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #79: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #80: @35 = @3' */
  for (i=0, rr=w35, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #81: @33 = mac(@35,@34,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w35+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #82: @32 = (@32+@33) */
  for (i=0, rr=w32, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #83: @10 = @32[5] */
  for (rr=(&w10), ss=w32+5; ss!=w32+6; ss+=1) *rr++ = *ss;
  /* #84: (@2[1] += @10) */
  for (rr=w2+1, ss=(&w10); rr!=w2+2; rr+=1) *rr += *ss++;
  /* #85: @10 = 0 */
  w10 = 0.;
  /* #86: (@32[5] = @10) */
  for (rr=w32+5, ss=(&w10); rr!=w32+6; rr+=1) *rr = *ss++;
  /* #87: @10 = @32[2] */
  for (rr=(&w10), ss=w32+2; ss!=w32+3; ss+=1) *rr++ = *ss;
  /* #88: @10 = (-@10) */
  w10 = (- w10 );
  /* #89: (@2[2] += @10) */
  for (rr=w2+2, ss=(&w10); rr!=w2+3; rr+=1) *rr += *ss++;
  /* #90: @10 = 0 */
  w10 = 0.;
  /* #91: (@32[2] = @10) */
  for (rr=w32+2, ss=(&w10); rr!=w32+3; rr+=1) *rr = *ss++;
  /* #92: @10 = @32[1] */
  for (rr=(&w10), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #93: (@2[3] += @10) */
  for (rr=w2+3, ss=(&w10); rr!=w2+4; rr+=1) *rr += *ss++;
  /* #94: @10 = 0 */
  w10 = 0.;
  /* #95: (@32[1] = @10) */
  for (rr=w32+1, ss=(&w10); rr!=w32+2; rr+=1) *rr = *ss++;
  /* #96: @10 = @32[7] */
  for (rr=(&w10), ss=w32+7; ss!=w32+8; ss+=1) *rr++ = *ss;
  /* #97: @10 = (-@10) */
  w10 = (- w10 );
  /* #98: (@2[1] += @10) */
  for (rr=w2+1, ss=(&w10); rr!=w2+2; rr+=1) *rr += *ss++;
  /* #99: @10 = 0 */
  w10 = 0.;
  /* #100: (@32[7] = @10) */
  for (rr=w32+7, ss=(&w10); rr!=w32+8; rr+=1) *rr = *ss++;
  /* #101: @10 = @32[6] */
  for (rr=(&w10), ss=w32+6; ss!=w32+7; ss+=1) *rr++ = *ss;
  /* #102: (@2[2] += @10) */
  for (rr=w2+2, ss=(&w10); rr!=w2+3; rr+=1) *rr += *ss++;
  /* #103: @10 = 0 */
  w10 = 0.;
  /* #104: (@32[6] = @10) */
  for (rr=w32+6, ss=(&w10); rr!=w32+7; rr+=1) *rr = *ss++;
  /* #105: @10 = @32[3] */
  for (rr=(&w10), ss=w32+3; ss!=w32+4; ss+=1) *rr++ = *ss;
  /* #106: @10 = (-@10) */
  w10 = (- w10 );
  /* #107: (@2[3] += @10) */
  for (rr=w2+3, ss=(&w10); rr!=w2+4; rr+=1) *rr += *ss++;
  /* #108: @36 = (@2/@7) */
  for (i=0, rr=w36, cr=w2; i<4; ++i) (*rr++)  = ((*cr++)/w7);
  /* #109: @37 = zeros(4x1) */
  casadi_clear(w37, 4);
  /* #110: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #111: @10 = @23[3] */
  for (rr=(&w10), ss=w23+3; ss!=w23+4; ss+=1) *rr++ = *ss;
  /* #112: @10 = (-@10) */
  w10 = (- w10 );
  /* #113: (@32[3] = @10) */
  for (rr=w32+3, ss=(&w10); rr!=w32+4; rr+=1) *rr = *ss++;
  /* #114: @10 = @23[2] */
  for (rr=(&w10), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #115: (@32[6] = @10) */
  for (rr=w32+6, ss=(&w10); rr!=w32+7; rr+=1) *rr = *ss++;
  /* #116: @10 = @23[1] */
  for (rr=(&w10), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #117: @10 = (-@10) */
  w10 = (- w10 );
  /* #118: (@32[7] = @10) */
  for (rr=w32+7, ss=(&w10); rr!=w32+8; rr+=1) *rr = *ss++;
  /* #119: @10 = @23[3] */
  for (rr=(&w10), ss=w23+3; ss!=w23+4; ss+=1) *rr++ = *ss;
  /* #120: (@32[1] = @10) */
  for (rr=w32+1, ss=(&w10); rr!=w32+2; rr+=1) *rr = *ss++;
  /* #121: @10 = @23[2] */
  for (rr=(&w10), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #122: @10 = (-@10) */
  w10 = (- w10 );
  /* #123: (@32[2] = @10) */
  for (rr=w32+2, ss=(&w10); rr!=w32+3; rr+=1) *rr = *ss++;
  /* #124: @10 = @23[1] */
  for (rr=(&w10), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #125: (@32[5] = @10) */
  for (rr=w32+5, ss=(&w10); rr!=w32+6; rr+=1) *rr = *ss++;
  /* #126: @10 = dot(@32, @26) */
  w10 = casadi_dot(9, w32, w26);
  /* #127: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #128: (@37[0] += @10) */
  for (rr=w37+0, ss=(&w10); rr!=w37+1; rr+=1) *rr += *ss++;
  /* #129: @10 = @23[0] */
  for (rr=(&w10), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #130: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #131: @33 = (@10*@26) */
  for (i=0, rr=w33, cs=w26; i<9; ++i) (*rr++)  = (w10*(*cs++));
  /* #132: @35 = zeros(3x3) */
  casadi_clear(w35, 9);
  /* #133: @38 = @32' */
  for (i=0, rr=w38, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #134: @35 = mac(@34,@38,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #135: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<9; ++i) (*rr++) += (*cs++);
  /* #136: @35 = zeros(3x3) */
  casadi_clear(w35, 9);
  /* #137: @39 = @32' */
  for (i=0, rr=w39, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #138: @35 = mac(@39,@34,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w39+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #139: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<9; ++i) (*rr++) += (*cs++);
  /* #140: @11 = @33[5] */
  for (rr=(&w11), ss=w33+5; ss!=w33+6; ss+=1) *rr++ = *ss;
  /* #141: (@37[1] += @11) */
  for (rr=w37+1, ss=(&w11); rr!=w37+2; rr+=1) *rr += *ss++;
  /* #142: @11 = 0 */
  w11 = 0.;
  /* #143: (@33[5] = @11) */
  for (rr=w33+5, ss=(&w11); rr!=w33+6; rr+=1) *rr = *ss++;
  /* #144: @11 = @33[2] */
  for (rr=(&w11), ss=w33+2; ss!=w33+3; ss+=1) *rr++ = *ss;
  /* #145: @11 = (-@11) */
  w11 = (- w11 );
  /* #146: (@37[2] += @11) */
  for (rr=w37+2, ss=(&w11); rr!=w37+3; rr+=1) *rr += *ss++;
  /* #147: @11 = 0 */
  w11 = 0.;
  /* #148: (@33[2] = @11) */
  for (rr=w33+2, ss=(&w11); rr!=w33+3; rr+=1) *rr = *ss++;
  /* #149: @11 = @33[1] */
  for (rr=(&w11), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #150: (@37[3] += @11) */
  for (rr=w37+3, ss=(&w11); rr!=w37+4; rr+=1) *rr += *ss++;
  /* #151: @11 = 0 */
  w11 = 0.;
  /* #152: (@33[1] = @11) */
  for (rr=w33+1, ss=(&w11); rr!=w33+2; rr+=1) *rr = *ss++;
  /* #153: @11 = @33[7] */
  for (rr=(&w11), ss=w33+7; ss!=w33+8; ss+=1) *rr++ = *ss;
  /* #154: @11 = (-@11) */
  w11 = (- w11 );
  /* #155: (@37[1] += @11) */
  for (rr=w37+1, ss=(&w11); rr!=w37+2; rr+=1) *rr += *ss++;
  /* #156: @11 = 0 */
  w11 = 0.;
  /* #157: (@33[7] = @11) */
  for (rr=w33+7, ss=(&w11); rr!=w33+8; rr+=1) *rr = *ss++;
  /* #158: @11 = @33[6] */
  for (rr=(&w11), ss=w33+6; ss!=w33+7; ss+=1) *rr++ = *ss;
  /* #159: (@37[2] += @11) */
  for (rr=w37+2, ss=(&w11); rr!=w37+3; rr+=1) *rr += *ss++;
  /* #160: @11 = 0 */
  w11 = 0.;
  /* #161: (@33[6] = @11) */
  for (rr=w33+6, ss=(&w11); rr!=w33+7; rr+=1) *rr = *ss++;
  /* #162: @11 = @33[3] */
  for (rr=(&w11), ss=w33+3; ss!=w33+4; ss+=1) *rr++ = *ss;
  /* #163: @11 = (-@11) */
  w11 = (- w11 );
  /* #164: (@37[3] += @11) */
  for (rr=w37+3, ss=(&w11); rr!=w37+4; rr+=1) *rr += *ss++;
  /* #165: @40 = (@37/@7) */
  for (i=0, rr=w40, cr=w37; i<4; ++i) (*rr++)  = ((*cr++)/w7);
  /* #166: @40 = (@40/@7) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) /= w7;
  /* #167: @41 = (@40*@9) */
  for (i=0, rr=w41, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #168: @36 = (@36-@41) */
  for (i=0, rr=w36, cs=w41; i<4; ++i) (*rr++) -= (*cs++);
  /* #169: @11 = 10 */
  w11 = 10.;
  /* #170: @12 = (2.*@13) */
  w12 = (2.* w13 );
  /* #171: @12 = (@12*@5) */
  w12 *= w5;
  /* #172: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #173: @41 = (@25*@12) */
  for (i=0, rr=w41, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w12);
  /* #174: @36 = (@36-@41) */
  for (i=0, rr=w36, cs=w41; i<4; ++i) (*rr++) -= (*cs++);
  /* #175: @23 = (@23/@7) */
  for (i=0, rr=w23; i<4; ++i) (*rr++) /= w7;
  /* #176: @41 = (-@23) */
  for (i=0, rr=w41, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #177: @12 = dot(@41, @2) */
  w12 = casadi_dot(4, w41, w2);
  /* #178: @22 = (@22/@7) */
  for (i=0, rr=w22; i<4; ++i) (*rr++) /= w7;
  /* #179: @23 = (@23/@7) */
  for (i=0, rr=w23; i<4; ++i) (*rr++) /= w7;
  /* #180: @2 = (@23*@9) */
  for (i=0, rr=w2, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #181: @22 = (@22-@2) */
  for (i=0, rr=w22, cs=w2; i<4; ++i) (*rr++) -= (*cs++);
  /* #182: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<4; ++i) *rr++ = (- *cs++ );
  /* #183: @17 = dot(@22, @37) */
  w17 = casadi_dot(4, w22, w37);
  /* #184: @12 = (@12+@17) */
  w12 += w17;
  /* #185: @12 = (@12/@7) */
  w12 /= w7;
  /* #186: @17 = dot(@41, @37) */
  w17 = casadi_dot(4, w41, w37);
  /* #187: @17 = (@17/@7) */
  w17 /= w7;
  /* #188: @18 = (@17/@7) */
  w18  = (w17/w7);
  /* #189: @9 = (@18*@9) */
  w9  = (w18*w9);
  /* #190: @12 = (@12-@9) */
  w12 -= w9;
  /* #191: @22 = (@21*@12) */
  for (i=0, rr=w22, cr=w21; i<4; ++i) (*rr++)  = ((*cr++)*w12);
  /* #192: @12 = (@17*@6) */
  w12  = (w17*w6);
  /* #193: @2 = dense(@12) */
  casadi_densify((&w12), casadi_s0, w2, 0);
  /* #194: @22 = (@22+@2) */
  for (i=0, rr=w22, cs=w2; i<4; ++i) (*rr++) += (*cs++);
  /* #195: @36 = (@36+@22) */
  for (i=0, rr=w36, cs=w22; i<4; ++i) (*rr++) += (*cs++);
  /* #196: (@1[6:10] += @36) */
  for (rr=w1+6, ss=w36; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #197: {@12, @9, @19, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51} = vertsplit(@1) */
  w12 = w1[0];
  w9 = w1[1];
  w19 = w1[2];
  w42 = w1[3];
  w43 = w1[4];
  w44 = w1[5];
  w45 = w1[6];
  w46 = w1[7];
  w47 = w1[8];
  w48 = w1[9];
  w49 = w1[10];
  w50 = w1[11];
  w51 = w1[12];
  /* #198: @52 = dot(@21, @25) */
  w52 = casadi_dot(4, w21, w25);
  /* #199: @52 = (@11*@52) */
  w52  = (w11*w52);
  /* #200: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #201: @5 = (@52*@5) */
  w5  = (w52*w5);
  /* #202: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #203: @53 = project(@25) */
  casadi_sparsify(w25, (&w53), casadi_s0, 0);
  /* #204: @54 = dot(@6, @53) */
  w54 = casadi_dot(1, (&w6), (&w53));
  /* #205: @54 = (@11*@54) */
  w54  = (w11*w54);
  /* #206: @53 = (@13*@54) */
  w53  = (w13*w54);
  /* #207: @5 = (@5+@53) */
  w5 += w53;
  /* #208: @45 = (@45-@5) */
  w45 -= w5;
  /* #209: @5 = (2.*@14) */
  w5 = (2.* w14 );
  /* #210: @53 = (@5*@54) */
  w53  = (w5*w54);
  /* #211: @46 = (@46-@53) */
  w46 -= w53;
  /* #212: @53 = (2.*@15) */
  w53 = (2.* w15 );
  /* #213: @55 = (@53*@54) */
  w55  = (w53*w54);
  /* #214: @47 = (@47-@55) */
  w47 -= w55;
  /* #215: @55 = (2.*@16) */
  w55 = (2.* w16 );
  /* #216: @54 = (@55*@54) */
  w54  = (w55*w54);
  /* #217: @48 = (@48-@54) */
  w48 -= w54;
  /* #218: @56 = zeros(4x4) */
  casadi_clear(w56, 16);
  /* #219: @54 = 0.5 */
  w54 = 5.0000000000000000e-01;
  /* #220: @36 = (@54*@25) */
  for (i=0, rr=w36, cs=w25; i<4; ++i) (*rr++)  = (w54*(*cs++));
  /* #221: @6 = @6' */
  /* #222: @56 = mac(@36,@6,@56) */
  casadi_mtimes(w36, casadi_s3, (&w6), casadi_s2, w56, casadi_s1, w, 0);
  /* #223: @57 = @56' */
  for (i=0, rr=w57, cs=w56; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #224: {@22, @2, @58, @59} = horzsplit(@57) */
  casadi_copy(w57, 4, w22);
  casadi_copy(w57+4, 4, w2);
  casadi_copy(w57+8, 4, w58);
  casadi_copy(w57+12, 4, w59);
  /* #225: @58 = @58' */
  /* #226: {@6, @54, NULL, @60} = horzsplit(@58) */
  w6 = w58[0];
  w54 = w58[1];
  w60 = w58[3];
  /* #227: @59 = @59' */
  /* #228: {@61, @62, @63, NULL} = horzsplit(@59) */
  w61 = w59[0];
  w62 = w59[1];
  w63 = w59[2];
  /* #229: @60 = (@60-@63) */
  w60 -= w63;
  /* #230: @2 = @2' */
  /* #231: {@63, NULL, @64, @65} = horzsplit(@2) */
  w63 = w2[0];
  w64 = w2[2];
  w65 = w2[3];
  /* #232: @60 = (@60+@63) */
  w60 += w63;
  /* #233: @22 = @22' */
  /* #234: {NULL, @63, @66, @67} = horzsplit(@22) */
  w63 = w22[1];
  w66 = w22[2];
  w67 = w22[3];
  /* #235: @60 = (@60-@63) */
  w60 -= w63;
  /* #236: @60 = (@60+@49) */
  w60 += w49;
  /* #237: @62 = (@62+@6) */
  w62 += w6;
  /* #238: @62 = (@62-@65) */
  w62 -= w65;
  /* #239: @62 = (@62-@66) */
  w62 -= w66;
  /* #240: @62 = (@62+@50) */
  w62 += w50;
  /* #241: @61 = (@61-@54) */
  w61 -= w54;
  /* #242: @61 = (@61+@64) */
  w61 += w64;
  /* #243: @61 = (@61-@67) */
  w61 -= w67;
  /* #244: @61 = (@61+@51) */
  w61 += w51;
  /* #245: @68 = 00 */
  /* #246: @69 = 00 */
  /* #247: @70 = 00 */
  /* #248: @71 = 00 */
  /* #249: @72 = 00 */
  /* #250: @73 = 00 */
  /* #251: @74 = 00 */
  /* #252: @75 = 00 */
  /* #253: @76 = 00 */
  /* #254: @77 = 00 */
  /* #255: @78 = 00 */
  /* #256: @79 = 00 */
  /* #257: @80 = 00 */
  /* #258: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #259: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #260: @33 = mac(@32,@3,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #261: @35 = zeros(3x3) */
  casadi_clear(w35, 9);
  /* #262: @35 = mac(@3,@32,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #263: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<9; ++i) (*rr++) += (*cs++);
  /* #264: @33 = (2.*@33) */
  for (i=0, rr=w33, cs=w33; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #265: @35 = (@32*@8) */
  for (i=0, rr=w35, cr=w32; i<9; ++i) (*rr++)  = ((*cr++)*w8);
  /* #266: @3 = (@10*@3) */
  for (i=0, rr=w3, cs=w3; i<9; ++i) (*rr++)  = (w10*(*cs++));
  /* #267: @35 = (@35+@3) */
  for (i=0, rr=w35, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #268: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<9; ++i) (*rr++) += (*cs++);
  /* #269: @29 = mac(@33,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #270: @8 = dot(@29, @27) */
  w8 = casadi_dot(3, w29, w27);
  /* #271: @81 = 00 */
  /* #272: @82 = 00 */
  /* #273: @83 = 00 */
  /* #274: @84 = vertcat(@12, @9, @19, @42, @43, @44, @45, @46, @47, @48, @60, @62, @61, @68, @69, @70, @71, @72, @73, @74, @75, @76, @77, @78, @79, @80, @8, @81, @82, @83) */
  rr=w84;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w19;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w60;
  *rr++ = w62;
  *rr++ = w61;
  *rr++ = w8;
  /* #275: @85 = @84[6:14] */
  for (rr=w85, ss=w84+6; ss!=w84+14; ss+=1) *rr++ = *ss;
  /* #276: (@0[0, 8, 16, 24, 32, 39, 46, 53] = @85) */
  for (cii=casadi_s4, rr=w0, ss=w85; cii!=casadi_s4+8; ++cii, ++ss) rr[*cii] = *ss;
  /* #277: @1 = zeros(13x1) */
  casadi_clear(w1, 13);
  /* #278: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #279: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #280: @12 = ones(30x1,1nz) */
  w12 = 1.;
  /* #281: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@12) */
  w9 = w12;
  /* #282: @12 = sparsity_cast(@9) */
  casadi_copy((&w9), 1, (&w12));
  /* #283: @19 = (@12/@7) */
  w19  = (w12/w7);
  /* #284: @2 = dense(@19) */
  casadi_densify((&w19), casadi_s5, w2, 0);
  /* #285: @19 = project(@21) */
  casadi_sparsify(w21, (&w19), casadi_s5, 0);
  /* #286: @42 = dot(@19, @12) */
  w42 = casadi_dot(1, (&w19), (&w12));
  /* #287: @42 = (@42/@7) */
  w42 /= w7;
  /* #288: @59 = (@24*@42) */
  for (i=0, rr=w59, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #289: @2 = (@2-@59) */
  for (i=0, rr=w2, cs=w59; i<4; ++i) (*rr++) -= (*cs++);
  /* #290: @19 = @2[3] */
  for (rr=(&w19), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #291: @19 = (-@19) */
  w19 = (- w19 );
  /* #292: (@33[3] += @19) */
  for (rr=w33+3, ss=(&w19); rr!=w33+4; rr+=1) *rr += *ss++;
  /* #293: @19 = 0 */
  w19 = 0.;
  /* #294: (@33[6] = @19) */
  for (rr=w33+6, ss=(&w19); rr!=w33+7; rr+=1) *rr = *ss++;
  /* #295: @19 = @2[2] */
  for (rr=(&w19), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #296: (@33[6] += @19) */
  for (rr=w33+6, ss=(&w19); rr!=w33+7; rr+=1) *rr += *ss++;
  /* #297: @19 = 0 */
  w19 = 0.;
  /* #298: (@33[7] = @19) */
  for (rr=w33+7, ss=(&w19); rr!=w33+8; rr+=1) *rr = *ss++;
  /* #299: @19 = @2[1] */
  for (rr=(&w19), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #300: @19 = (-@19) */
  w19 = (- w19 );
  /* #301: (@33[7] += @19) */
  for (rr=w33+7, ss=(&w19); rr!=w33+8; rr+=1) *rr += *ss++;
  /* #302: @19 = 0 */
  w19 = 0.;
  /* #303: (@33[1] = @19) */
  for (rr=w33+1, ss=(&w19); rr!=w33+2; rr+=1) *rr = *ss++;
  /* #304: @19 = @2[3] */
  for (rr=(&w19), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #305: (@33[1] += @19) */
  for (rr=w33+1, ss=(&w19); rr!=w33+2; rr+=1) *rr += *ss++;
  /* #306: @19 = 0 */
  w19 = 0.;
  /* #307: (@33[2] = @19) */
  for (rr=w33+2, ss=(&w19); rr!=w33+3; rr+=1) *rr = *ss++;
  /* #308: @19 = @2[2] */
  for (rr=(&w19), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #309: @19 = (-@19) */
  w19 = (- w19 );
  /* #310: (@33[2] += @19) */
  for (rr=w33+2, ss=(&w19); rr!=w33+3; rr+=1) *rr += *ss++;
  /* #311: @19 = 0 */
  w19 = 0.;
  /* #312: (@33[5] = @19) */
  for (rr=w33+5, ss=(&w19); rr!=w33+6; rr+=1) *rr = *ss++;
  /* #313: @19 = @2[1] */
  for (rr=(&w19), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #314: (@33[5] += @19) */
  for (rr=w33+5, ss=(&w19); rr!=w33+6; rr+=1) *rr += *ss++;
  /* #315: @19 = dot(@33, @26) */
  w19 = casadi_dot(9, w33, w26);
  /* #316: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #317: (@22[0] += @19) */
  for (rr=w22+0, ss=(&w19); rr!=w22+1; rr+=1) *rr += *ss++;
  /* #318: @19 = @2[0] */
  for (rr=(&w19), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #319: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #320: @35 = (@26*@19) */
  for (i=0, rr=w35, cr=w26; i<9; ++i) (*rr++)  = ((*cr++)*w19);
  /* #321: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #322: @86 = @33' */
  for (i=0, rr=w86, cs=w33; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #323: @3 = mac(@34,@86,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w86+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #324: @35 = (@35+@3) */
  for (i=0, rr=w35, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #325: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #326: @86 = @33' */
  for (i=0, rr=w86, cs=w33; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #327: @3 = mac(@86,@34,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w86+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #328: @35 = (@35+@3) */
  for (i=0, rr=w35, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #329: @43 = @35[5] */
  for (rr=(&w43), ss=w35+5; ss!=w35+6; ss+=1) *rr++ = *ss;
  /* #330: (@22[1] += @43) */
  for (rr=w22+1, ss=(&w43); rr!=w22+2; rr+=1) *rr += *ss++;
  /* #331: @43 = 0 */
  w43 = 0.;
  /* #332: (@35[5] = @43) */
  for (rr=w35+5, ss=(&w43); rr!=w35+6; rr+=1) *rr = *ss++;
  /* #333: @43 = @35[2] */
  for (rr=(&w43), ss=w35+2; ss!=w35+3; ss+=1) *rr++ = *ss;
  /* #334: @43 = (-@43) */
  w43 = (- w43 );
  /* #335: (@22[2] += @43) */
  for (rr=w22+2, ss=(&w43); rr!=w22+3; rr+=1) *rr += *ss++;
  /* #336: @43 = 0 */
  w43 = 0.;
  /* #337: (@35[2] = @43) */
  for (rr=w35+2, ss=(&w43); rr!=w35+3; rr+=1) *rr = *ss++;
  /* #338: @43 = @35[1] */
  for (rr=(&w43), ss=w35+1; ss!=w35+2; ss+=1) *rr++ = *ss;
  /* #339: (@22[3] += @43) */
  for (rr=w22+3, ss=(&w43); rr!=w22+4; rr+=1) *rr += *ss++;
  /* #340: @43 = 0 */
  w43 = 0.;
  /* #341: (@35[1] = @43) */
  for (rr=w35+1, ss=(&w43); rr!=w35+2; rr+=1) *rr = *ss++;
  /* #342: @43 = @35[7] */
  for (rr=(&w43), ss=w35+7; ss!=w35+8; ss+=1) *rr++ = *ss;
  /* #343: @43 = (-@43) */
  w43 = (- w43 );
  /* #344: (@22[1] += @43) */
  for (rr=w22+1, ss=(&w43); rr!=w22+2; rr+=1) *rr += *ss++;
  /* #345: @43 = 0 */
  w43 = 0.;
  /* #346: (@35[7] = @43) */
  for (rr=w35+7, ss=(&w43); rr!=w35+8; rr+=1) *rr = *ss++;
  /* #347: @43 = @35[6] */
  for (rr=(&w43), ss=w35+6; ss!=w35+7; ss+=1) *rr++ = *ss;
  /* #348: (@22[2] += @43) */
  for (rr=w22+2, ss=(&w43); rr!=w22+3; rr+=1) *rr += *ss++;
  /* #349: @43 = 0 */
  w43 = 0.;
  /* #350: (@35[6] = @43) */
  for (rr=w35+6, ss=(&w43); rr!=w35+7; rr+=1) *rr = *ss++;
  /* #351: @43 = @35[3] */
  for (rr=(&w43), ss=w35+3; ss!=w35+4; ss+=1) *rr++ = *ss;
  /* #352: @43 = (-@43) */
  w43 = (- w43 );
  /* #353: (@22[3] += @43) */
  for (rr=w22+3, ss=(&w43); rr!=w22+4; rr+=1) *rr += *ss++;
  /* #354: @59 = (@22/@7) */
  for (i=0, rr=w59, cr=w22; i<4; ++i) (*rr++)  = ((*cr++)/w7);
  /* #355: @58 = (@40*@42) */
  for (i=0, rr=w58, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #356: @59 = (@59-@58) */
  for (i=0, rr=w59, cs=w58; i<4; ++i) (*rr++) -= (*cs++);
  /* #357: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #358: @14 = (@14*@9) */
  w14 *= w9;
  /* #359: @14 = (@11*@14) */
  w14  = (w11*w14);
  /* #360: @58 = (@25*@14) */
  for (i=0, rr=w58, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w14);
  /* #361: @59 = (@59-@58) */
  for (i=0, rr=w59, cs=w58; i<4; ++i) (*rr++) -= (*cs++);
  /* #362: @14 = dot(@41, @22) */
  w14 = casadi_dot(4, w41, w22);
  /* #363: @2 = (@2/@7) */
  for (i=0, rr=w2; i<4; ++i) (*rr++) /= w7;
  /* #364: @22 = (@23*@42) */
  for (i=0, rr=w22, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)*w42);
  /* #365: @2 = (@2-@22) */
  for (i=0, rr=w2, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #366: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) *rr++ = (- *cs++ );
  /* #367: @43 = dot(@2, @37) */
  w43 = casadi_dot(4, w2, w37);
  /* #368: @14 = (@14+@43) */
  w14 += w43;
  /* #369: @14 = (@14/@7) */
  w14 /= w7;
  /* #370: @42 = (@18*@42) */
  w42  = (w18*w42);
  /* #371: @14 = (@14-@42) */
  w14 -= w42;
  /* #372: @2 = (@21*@14) */
  for (i=0, rr=w2, cr=w21; i<4; ++i) (*rr++)  = ((*cr++)*w14);
  /* #373: @14 = (@17*@12) */
  w14  = (w17*w12);
  /* #374: @22 = dense(@14) */
  casadi_densify((&w14), casadi_s5, w22, 0);
  /* #375: @2 = (@2+@22) */
  for (i=0, rr=w2, cs=w22; i<4; ++i) (*rr++) += (*cs++);
  /* #376: @59 = (@59+@2) */
  for (i=0, rr=w59, cs=w2; i<4; ++i) (*rr++) += (*cs++);
  /* #377: (@1[6:10] += @59) */
  for (rr=w1+6, ss=w59; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #378: {@14, @42, @43, @44, @45, @46, @47, @48, @60, @62, @61, @8, @51} = vertsplit(@1) */
  w14 = w1[0];
  w42 = w1[1];
  w43 = w1[2];
  w44 = w1[3];
  w45 = w1[4];
  w46 = w1[5];
  w47 = w1[6];
  w48 = w1[7];
  w60 = w1[8];
  w62 = w1[9];
  w61 = w1[10];
  w8 = w1[11];
  w51 = w1[12];
  /* #379: @67 = project(@25) */
  casadi_sparsify(w25, (&w67), casadi_s5, 0);
  /* #380: @64 = dot(@12, @67) */
  w64 = casadi_dot(1, (&w12), (&w67));
  /* #381: @64 = (@11*@64) */
  w64  = (w11*w64);
  /* #382: @67 = (@13*@64) */
  w67  = (w13*w64);
  /* #383: @47 = (@47-@67) */
  w47 -= w67;
  /* #384: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #385: @9 = (@52*@9) */
  w9  = (w52*w9);
  /* #386: @67 = (@5*@64) */
  w67  = (w5*w64);
  /* #387: @9 = (@9+@67) */
  w9 += w67;
  /* #388: @48 = (@48-@9) */
  w48 -= w9;
  /* #389: @9 = (@53*@64) */
  w9  = (w53*w64);
  /* #390: @60 = (@60-@9) */
  w60 -= w9;
  /* #391: @64 = (@55*@64) */
  w64  = (w55*w64);
  /* #392: @62 = (@62-@64) */
  w62 -= w64;
  /* #393: @57 = zeros(4x4) */
  casadi_clear(w57, 16);
  /* #394: @12 = @12' */
  /* #395: @57 = mac(@36,@12,@57) */
  casadi_mtimes(w36, casadi_s3, (&w12), casadi_s6, w57, casadi_s1, w, 0);
  /* #396: @56 = @57' */
  for (i=0, rr=w56, cs=w57; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #397: {@59, @2, @22, @58} = horzsplit(@56) */
  casadi_copy(w56, 4, w59);
  casadi_copy(w56+4, 4, w2);
  casadi_copy(w56+8, 4, w22);
  casadi_copy(w56+12, 4, w58);
  /* #398: @22 = @22' */
  /* #399: {@12, @64, NULL, @9} = horzsplit(@22) */
  w12 = w22[0];
  w64 = w22[1];
  w9 = w22[3];
  /* #400: @58 = @58' */
  /* #401: {@67, @54, @50, NULL} = horzsplit(@58) */
  w67 = w58[0];
  w54 = w58[1];
  w50 = w58[2];
  /* #402: @9 = (@9-@50) */
  w9 -= w50;
  /* #403: @2 = @2' */
  /* #404: {@50, NULL, @66, @65} = horzsplit(@2) */
  w50 = w2[0];
  w66 = w2[2];
  w65 = w2[3];
  /* #405: @9 = (@9+@50) */
  w9 += w50;
  /* #406: @59 = @59' */
  /* #407: {NULL, @50, @6, @49} = horzsplit(@59) */
  w50 = w59[1];
  w6 = w59[2];
  w49 = w59[3];
  /* #408: @9 = (@9-@50) */
  w9 -= w50;
  /* #409: @9 = (@9+@61) */
  w9 += w61;
  /* #410: @54 = (@54+@12) */
  w54 += w12;
  /* #411: @54 = (@54-@65) */
  w54 -= w65;
  /* #412: @54 = (@54-@6) */
  w54 -= w6;
  /* #413: @54 = (@54+@8) */
  w54 += w8;
  /* #414: @67 = (@67-@64) */
  w67 -= w64;
  /* #415: @67 = (@67+@66) */
  w67 += w66;
  /* #416: @67 = (@67-@49) */
  w67 -= w49;
  /* #417: @67 = (@67+@51) */
  w67 += w51;
  /* #418: @68 = 00 */
  /* #419: @69 = 00 */
  /* #420: @70 = 00 */
  /* #421: @71 = 00 */
  /* #422: @72 = 00 */
  /* #423: @73 = 00 */
  /* #424: @74 = 00 */
  /* #425: @75 = 00 */
  /* #426: @76 = 00 */
  /* #427: @77 = 00 */
  /* #428: @78 = 00 */
  /* #429: @79 = 00 */
  /* #430: @80 = 00 */
  /* #431: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #432: @35 = zeros(3x3) */
  casadi_clear(w35, 9);
  /* #433: @35 = mac(@32,@33,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #434: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #435: @3 = mac(@33,@32,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #436: @35 = (@35+@3) */
  for (i=0, rr=w35, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #437: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #438: @3 = (@32*@19) */
  for (i=0, rr=w3, cr=w32; i<9; ++i) (*rr++)  = ((*cr++)*w19);
  /* #439: @33 = (@10*@33) */
  for (i=0, rr=w33, cs=w33; i<9; ++i) (*rr++)  = (w10*(*cs++));
  /* #440: @3 = (@3+@33) */
  for (i=0, rr=w3, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #441: @35 = (@35+@3) */
  for (i=0, rr=w35, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #442: @29 = mac(@35,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w35+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #443: @19 = dot(@29, @27) */
  w19 = casadi_dot(3, w29, w27);
  /* #444: @81 = 00 */
  /* #445: @82 = 00 */
  /* #446: @83 = 00 */
  /* #447: @84 = vertcat(@14, @42, @43, @44, @45, @46, @47, @48, @60, @62, @9, @54, @67, @68, @69, @70, @71, @72, @73, @74, @75, @76, @77, @78, @79, @80, @19, @81, @82, @83) */
  rr=w84;
  *rr++ = w14;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w60;
  *rr++ = w62;
  *rr++ = w9;
  *rr++ = w54;
  *rr++ = w67;
  *rr++ = w19;
  /* #448: @85 = @84[6:14] */
  for (rr=w85, ss=w84+6; ss!=w84+14; ss+=1) *rr++ = *ss;
  /* #449: (@0[1, 9, 17, 25, 33, 40, 47, 54] = @85) */
  for (cii=casadi_s7, rr=w0, ss=w85; cii!=casadi_s7+8; ++cii, ++ss) rr[*cii] = *ss;
  /* #450: @1 = zeros(13x1) */
  casadi_clear(w1, 13);
  /* #451: @59 = zeros(4x1) */
  casadi_clear(w59, 4);
  /* #452: @35 = zeros(3x3) */
  casadi_clear(w35, 9);
  /* #453: @14 = ones(30x1,1nz) */
  w14 = 1.;
  /* #454: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @42, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@14) */
  w42 = w14;
  /* #455: @14 = sparsity_cast(@42) */
  casadi_copy((&w42), 1, (&w14));
  /* #456: @43 = (@14/@7) */
  w43  = (w14/w7);
  /* #457: @2 = dense(@43) */
  casadi_densify((&w43), casadi_s8, w2, 0);
  /* #458: @43 = project(@21) */
  casadi_sparsify(w21, (&w43), casadi_s8, 0);
  /* #459: @44 = dot(@43, @14) */
  w44 = casadi_dot(1, (&w43), (&w14));
  /* #460: @44 = (@44/@7) */
  w44 /= w7;
  /* #461: @58 = (@24*@44) */
  for (i=0, rr=w58, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #462: @2 = (@2-@58) */
  for (i=0, rr=w2, cs=w58; i<4; ++i) (*rr++) -= (*cs++);
  /* #463: @43 = @2[3] */
  for (rr=(&w43), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #464: @43 = (-@43) */
  w43 = (- w43 );
  /* #465: (@35[3] += @43) */
  for (rr=w35+3, ss=(&w43); rr!=w35+4; rr+=1) *rr += *ss++;
  /* #466: @43 = 0 */
  w43 = 0.;
  /* #467: (@35[6] = @43) */
  for (rr=w35+6, ss=(&w43); rr!=w35+7; rr+=1) *rr = *ss++;
  /* #468: @43 = @2[2] */
  for (rr=(&w43), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #469: (@35[6] += @43) */
  for (rr=w35+6, ss=(&w43); rr!=w35+7; rr+=1) *rr += *ss++;
  /* #470: @43 = 0 */
  w43 = 0.;
  /* #471: (@35[7] = @43) */
  for (rr=w35+7, ss=(&w43); rr!=w35+8; rr+=1) *rr = *ss++;
  /* #472: @43 = @2[1] */
  for (rr=(&w43), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #473: @43 = (-@43) */
  w43 = (- w43 );
  /* #474: (@35[7] += @43) */
  for (rr=w35+7, ss=(&w43); rr!=w35+8; rr+=1) *rr += *ss++;
  /* #475: @43 = 0 */
  w43 = 0.;
  /* #476: (@35[1] = @43) */
  for (rr=w35+1, ss=(&w43); rr!=w35+2; rr+=1) *rr = *ss++;
  /* #477: @43 = @2[3] */
  for (rr=(&w43), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #478: (@35[1] += @43) */
  for (rr=w35+1, ss=(&w43); rr!=w35+2; rr+=1) *rr += *ss++;
  /* #479: @43 = 0 */
  w43 = 0.;
  /* #480: (@35[2] = @43) */
  for (rr=w35+2, ss=(&w43); rr!=w35+3; rr+=1) *rr = *ss++;
  /* #481: @43 = @2[2] */
  for (rr=(&w43), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #482: @43 = (-@43) */
  w43 = (- w43 );
  /* #483: (@35[2] += @43) */
  for (rr=w35+2, ss=(&w43); rr!=w35+3; rr+=1) *rr += *ss++;
  /* #484: @43 = 0 */
  w43 = 0.;
  /* #485: (@35[5] = @43) */
  for (rr=w35+5, ss=(&w43); rr!=w35+6; rr+=1) *rr = *ss++;
  /* #486: @43 = @2[1] */
  for (rr=(&w43), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #487: (@35[5] += @43) */
  for (rr=w35+5, ss=(&w43); rr!=w35+6; rr+=1) *rr += *ss++;
  /* #488: @43 = dot(@35, @26) */
  w43 = casadi_dot(9, w35, w26);
  /* #489: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #490: (@59[0] += @43) */
  for (rr=w59+0, ss=(&w43); rr!=w59+1; rr+=1) *rr += *ss++;
  /* #491: @43 = @2[0] */
  for (rr=(&w43), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #492: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #493: @3 = (@26*@43) */
  for (i=0, rr=w3, cr=w26; i<9; ++i) (*rr++)  = ((*cr++)*w43);
  /* #494: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #495: @86 = @35' */
  for (i=0, rr=w86, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #496: @33 = mac(@34,@86,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w86+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #497: @3 = (@3+@33) */
  for (i=0, rr=w3, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #498: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #499: @86 = @35' */
  for (i=0, rr=w86, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #500: @33 = mac(@86,@34,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w86+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #501: @3 = (@3+@33) */
  for (i=0, rr=w3, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #502: @45 = @3[5] */
  for (rr=(&w45), ss=w3+5; ss!=w3+6; ss+=1) *rr++ = *ss;
  /* #503: (@59[1] += @45) */
  for (rr=w59+1, ss=(&w45); rr!=w59+2; rr+=1) *rr += *ss++;
  /* #504: @45 = 0 */
  w45 = 0.;
  /* #505: (@3[5] = @45) */
  for (rr=w3+5, ss=(&w45); rr!=w3+6; rr+=1) *rr = *ss++;
  /* #506: @45 = @3[2] */
  for (rr=(&w45), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #507: @45 = (-@45) */
  w45 = (- w45 );
  /* #508: (@59[2] += @45) */
  for (rr=w59+2, ss=(&w45); rr!=w59+3; rr+=1) *rr += *ss++;
  /* #509: @45 = 0 */
  w45 = 0.;
  /* #510: (@3[2] = @45) */
  for (rr=w3+2, ss=(&w45); rr!=w3+3; rr+=1) *rr = *ss++;
  /* #511: @45 = @3[1] */
  for (rr=(&w45), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #512: (@59[3] += @45) */
  for (rr=w59+3, ss=(&w45); rr!=w59+4; rr+=1) *rr += *ss++;
  /* #513: @45 = 0 */
  w45 = 0.;
  /* #514: (@3[1] = @45) */
  for (rr=w3+1, ss=(&w45); rr!=w3+2; rr+=1) *rr = *ss++;
  /* #515: @45 = @3[7] */
  for (rr=(&w45), ss=w3+7; ss!=w3+8; ss+=1) *rr++ = *ss;
  /* #516: @45 = (-@45) */
  w45 = (- w45 );
  /* #517: (@59[1] += @45) */
  for (rr=w59+1, ss=(&w45); rr!=w59+2; rr+=1) *rr += *ss++;
  /* #518: @45 = 0 */
  w45 = 0.;
  /* #519: (@3[7] = @45) */
  for (rr=w3+7, ss=(&w45); rr!=w3+8; rr+=1) *rr = *ss++;
  /* #520: @45 = @3[6] */
  for (rr=(&w45), ss=w3+6; ss!=w3+7; ss+=1) *rr++ = *ss;
  /* #521: (@59[2] += @45) */
  for (rr=w59+2, ss=(&w45); rr!=w59+3; rr+=1) *rr += *ss++;
  /* #522: @45 = 0 */
  w45 = 0.;
  /* #523: (@3[6] = @45) */
  for (rr=w3+6, ss=(&w45); rr!=w3+7; rr+=1) *rr = *ss++;
  /* #524: @45 = @3[3] */
  for (rr=(&w45), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #525: @45 = (-@45) */
  w45 = (- w45 );
  /* #526: (@59[3] += @45) */
  for (rr=w59+3, ss=(&w45); rr!=w59+4; rr+=1) *rr += *ss++;
  /* #527: @58 = (@59/@7) */
  for (i=0, rr=w58, cr=w59; i<4; ++i) (*rr++)  = ((*cr++)/w7);
  /* #528: @22 = (@40*@44) */
  for (i=0, rr=w22, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #529: @58 = (@58-@22) */
  for (i=0, rr=w58, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #530: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #531: @15 = (@15*@42) */
  w15 *= w42;
  /* #532: @15 = (@11*@15) */
  w15  = (w11*w15);
  /* #533: @22 = (@25*@15) */
  for (i=0, rr=w22, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w15);
  /* #534: @58 = (@58-@22) */
  for (i=0, rr=w58, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #535: @15 = dot(@41, @59) */
  w15 = casadi_dot(4, w41, w59);
  /* #536: @2 = (@2/@7) */
  for (i=0, rr=w2; i<4; ++i) (*rr++) /= w7;
  /* #537: @59 = (@23*@44) */
  for (i=0, rr=w59, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #538: @2 = (@2-@59) */
  for (i=0, rr=w2, cs=w59; i<4; ++i) (*rr++) -= (*cs++);
  /* #539: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) *rr++ = (- *cs++ );
  /* #540: @45 = dot(@2, @37) */
  w45 = casadi_dot(4, w2, w37);
  /* #541: @15 = (@15+@45) */
  w15 += w45;
  /* #542: @15 = (@15/@7) */
  w15 /= w7;
  /* #543: @44 = (@18*@44) */
  w44  = (w18*w44);
  /* #544: @15 = (@15-@44) */
  w15 -= w44;
  /* #545: @2 = (@21*@15) */
  for (i=0, rr=w2, cr=w21; i<4; ++i) (*rr++)  = ((*cr++)*w15);
  /* #546: @15 = (@17*@14) */
  w15  = (w17*w14);
  /* #547: @59 = dense(@15) */
  casadi_densify((&w15), casadi_s8, w59, 0);
  /* #548: @2 = (@2+@59) */
  for (i=0, rr=w2, cs=w59; i<4; ++i) (*rr++) += (*cs++);
  /* #549: @58 = (@58+@2) */
  for (i=0, rr=w58, cs=w2; i<4; ++i) (*rr++) += (*cs++);
  /* #550: (@1[6:10] += @58) */
  for (rr=w1+6, ss=w58; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #551: {@15, @44, @45, @46, @47, @48, @60, @62, @9, @54, @67, @19, @51} = vertsplit(@1) */
  w15 = w1[0];
  w44 = w1[1];
  w45 = w1[2];
  w46 = w1[3];
  w47 = w1[4];
  w48 = w1[5];
  w60 = w1[6];
  w62 = w1[7];
  w9 = w1[8];
  w54 = w1[9];
  w67 = w1[10];
  w19 = w1[11];
  w51 = w1[12];
  /* #552: @49 = project(@25) */
  casadi_sparsify(w25, (&w49), casadi_s8, 0);
  /* #553: @66 = dot(@14, @49) */
  w66 = casadi_dot(1, (&w14), (&w49));
  /* #554: @66 = (@11*@66) */
  w66  = (w11*w66);
  /* #555: @49 = (@13*@66) */
  w49  = (w13*w66);
  /* #556: @60 = (@60-@49) */
  w60 -= w49;
  /* #557: @49 = (@5*@66) */
  w49  = (w5*w66);
  /* #558: @62 = (@62-@49) */
  w62 -= w49;
  /* #559: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #560: @42 = (@52*@42) */
  w42  = (w52*w42);
  /* #561: @49 = (@53*@66) */
  w49  = (w53*w66);
  /* #562: @42 = (@42+@49) */
  w42 += w49;
  /* #563: @9 = (@9-@42) */
  w9 -= w42;
  /* #564: @66 = (@55*@66) */
  w66  = (w55*w66);
  /* #565: @54 = (@54-@66) */
  w54 -= w66;
  /* #566: @56 = zeros(4x4) */
  casadi_clear(w56, 16);
  /* #567: @14 = @14' */
  /* #568: @56 = mac(@36,@14,@56) */
  casadi_mtimes(w36, casadi_s3, (&w14), casadi_s9, w56, casadi_s1, w, 0);
  /* #569: @57 = @56' */
  for (i=0, rr=w57, cs=w56; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #570: {@58, @2, @59, @22} = horzsplit(@57) */
  casadi_copy(w57, 4, w58);
  casadi_copy(w57+4, 4, w2);
  casadi_copy(w57+8, 4, w59);
  casadi_copy(w57+12, 4, w22);
  /* #571: @59 = @59' */
  /* #572: {@14, @66, NULL, @42} = horzsplit(@59) */
  w14 = w59[0];
  w66 = w59[1];
  w42 = w59[3];
  /* #573: @22 = @22' */
  /* #574: {@49, @64, @8, NULL} = horzsplit(@22) */
  w49 = w22[0];
  w64 = w22[1];
  w8 = w22[2];
  /* #575: @42 = (@42-@8) */
  w42 -= w8;
  /* #576: @2 = @2' */
  /* #577: {@8, NULL, @6, @65} = horzsplit(@2) */
  w8 = w2[0];
  w6 = w2[2];
  w65 = w2[3];
  /* #578: @42 = (@42+@8) */
  w42 += w8;
  /* #579: @58 = @58' */
  /* #580: {NULL, @8, @12, @61} = horzsplit(@58) */
  w8 = w58[1];
  w12 = w58[2];
  w61 = w58[3];
  /* #581: @42 = (@42-@8) */
  w42 -= w8;
  /* #582: @42 = (@42+@67) */
  w42 += w67;
  /* #583: @64 = (@64+@14) */
  w64 += w14;
  /* #584: @64 = (@64-@65) */
  w64 -= w65;
  /* #585: @64 = (@64-@12) */
  w64 -= w12;
  /* #586: @64 = (@64+@19) */
  w64 += w19;
  /* #587: @49 = (@49-@66) */
  w49 -= w66;
  /* #588: @49 = (@49+@6) */
  w49 += w6;
  /* #589: @49 = (@49-@61) */
  w49 -= w61;
  /* #590: @49 = (@49+@51) */
  w49 += w51;
  /* #591: @68 = 00 */
  /* #592: @69 = 00 */
  /* #593: @70 = 00 */
  /* #594: @71 = 00 */
  /* #595: @72 = 00 */
  /* #596: @73 = 00 */
  /* #597: @74 = 00 */
  /* #598: @75 = 00 */
  /* #599: @76 = 00 */
  /* #600: @77 = 00 */
  /* #601: @78 = 00 */
  /* #602: @79 = 00 */
  /* #603: @80 = 00 */
  /* #604: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #605: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #606: @3 = mac(@32,@35,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #607: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #608: @33 = mac(@35,@32,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w35+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #609: @3 = (@3+@33) */
  for (i=0, rr=w3, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #610: @3 = (2.*@3) */
  for (i=0, rr=w3, cs=w3; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #611: @33 = (@32*@43) */
  for (i=0, rr=w33, cr=w32; i<9; ++i) (*rr++)  = ((*cr++)*w43);
  /* #612: @35 = (@10*@35) */
  for (i=0, rr=w35, cs=w35; i<9; ++i) (*rr++)  = (w10*(*cs++));
  /* #613: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<9; ++i) (*rr++) += (*cs++);
  /* #614: @3 = (@3+@33) */
  for (i=0, rr=w3, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #615: @29 = mac(@3,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #616: @43 = dot(@29, @27) */
  w43 = casadi_dot(3, w29, w27);
  /* #617: @81 = 00 */
  /* #618: @82 = 00 */
  /* #619: @83 = 00 */
  /* #620: @84 = vertcat(@15, @44, @45, @46, @47, @48, @60, @62, @9, @54, @42, @64, @49, @68, @69, @70, @71, @72, @73, @74, @75, @76, @77, @78, @79, @80, @43, @81, @82, @83) */
  rr=w84;
  *rr++ = w15;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w60;
  *rr++ = w62;
  *rr++ = w9;
  *rr++ = w54;
  *rr++ = w42;
  *rr++ = w64;
  *rr++ = w49;
  *rr++ = w43;
  /* #621: @85 = @84[6:14] */
  for (rr=w85, ss=w84+6; ss!=w84+14; ss+=1) *rr++ = *ss;
  /* #622: (@0[2, 10, 18, 26, 34, 41, 48, 55] = @85) */
  for (cii=casadi_s10, rr=w0, ss=w85; cii!=casadi_s10+8; ++cii, ++ss) rr[*cii] = *ss;
  /* #623: @1 = zeros(13x1) */
  casadi_clear(w1, 13);
  /* #624: @58 = zeros(4x1) */
  casadi_clear(w58, 4);
  /* #625: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #626: @15 = ones(30x1,1nz) */
  w15 = 1.;
  /* #627: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @44, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@15) */
  w44 = w15;
  /* #628: @15 = sparsity_cast(@44) */
  casadi_copy((&w44), 1, (&w15));
  /* #629: @45 = (@15/@7) */
  w45  = (w15/w7);
  /* #630: @2 = dense(@45) */
  casadi_densify((&w45), casadi_s11, w2, 0);
  /* #631: @45 = project(@21) */
  casadi_sparsify(w21, (&w45), casadi_s11, 0);
  /* #632: @46 = dot(@45, @15) */
  w46 = casadi_dot(1, (&w45), (&w15));
  /* #633: @46 = (@46/@7) */
  w46 /= w7;
  /* #634: @24 = (@24*@46) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) *= w46;
  /* #635: @2 = (@2-@24) */
  for (i=0, rr=w2, cs=w24; i<4; ++i) (*rr++) -= (*cs++);
  /* #636: @45 = @2[3] */
  for (rr=(&w45), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #637: @45 = (-@45) */
  w45 = (- w45 );
  /* #638: (@3[3] += @45) */
  for (rr=w3+3, ss=(&w45); rr!=w3+4; rr+=1) *rr += *ss++;
  /* #639: @45 = 0 */
  w45 = 0.;
  /* #640: (@3[6] = @45) */
  for (rr=w3+6, ss=(&w45); rr!=w3+7; rr+=1) *rr = *ss++;
  /* #641: @45 = @2[2] */
  for (rr=(&w45), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #642: (@3[6] += @45) */
  for (rr=w3+6, ss=(&w45); rr!=w3+7; rr+=1) *rr += *ss++;
  /* #643: @45 = 0 */
  w45 = 0.;
  /* #644: (@3[7] = @45) */
  for (rr=w3+7, ss=(&w45); rr!=w3+8; rr+=1) *rr = *ss++;
  /* #645: @45 = @2[1] */
  for (rr=(&w45), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #646: @45 = (-@45) */
  w45 = (- w45 );
  /* #647: (@3[7] += @45) */
  for (rr=w3+7, ss=(&w45); rr!=w3+8; rr+=1) *rr += *ss++;
  /* #648: @45 = 0 */
  w45 = 0.;
  /* #649: (@3[1] = @45) */
  for (rr=w3+1, ss=(&w45); rr!=w3+2; rr+=1) *rr = *ss++;
  /* #650: @45 = @2[3] */
  for (rr=(&w45), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #651: (@3[1] += @45) */
  for (rr=w3+1, ss=(&w45); rr!=w3+2; rr+=1) *rr += *ss++;
  /* #652: @45 = 0 */
  w45 = 0.;
  /* #653: (@3[2] = @45) */
  for (rr=w3+2, ss=(&w45); rr!=w3+3; rr+=1) *rr = *ss++;
  /* #654: @45 = @2[2] */
  for (rr=(&w45), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #655: @45 = (-@45) */
  w45 = (- w45 );
  /* #656: (@3[2] += @45) */
  for (rr=w3+2, ss=(&w45); rr!=w3+3; rr+=1) *rr += *ss++;
  /* #657: @45 = 0 */
  w45 = 0.;
  /* #658: (@3[5] = @45) */
  for (rr=w3+5, ss=(&w45); rr!=w3+6; rr+=1) *rr = *ss++;
  /* #659: @45 = @2[1] */
  for (rr=(&w45), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #660: (@3[5] += @45) */
  for (rr=w3+5, ss=(&w45); rr!=w3+6; rr+=1) *rr += *ss++;
  /* #661: @45 = dot(@3, @26) */
  w45 = casadi_dot(9, w3, w26);
  /* #662: @45 = (2.*@45) */
  w45 = (2.* w45 );
  /* #663: (@58[0] += @45) */
  for (rr=w58+0, ss=(&w45); rr!=w58+1; rr+=1) *rr += *ss++;
  /* #664: @45 = @2[0] */
  for (rr=(&w45), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #665: @45 = (2.*@45) */
  w45 = (2.* w45 );
  /* #666: @26 = (@26*@45) */
  for (i=0, rr=w26; i<9; ++i) (*rr++) *= w45;
  /* #667: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #668: @35 = @3' */
  for (i=0, rr=w35, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #669: @33 = mac(@34,@35,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #670: @26 = (@26+@33) */
  for (i=0, rr=w26, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #671: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #672: @35 = @3' */
  for (i=0, rr=w35, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #673: @33 = mac(@35,@34,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w35+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #674: @26 = (@26+@33) */
  for (i=0, rr=w26, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #675: @47 = @26[5] */
  for (rr=(&w47), ss=w26+5; ss!=w26+6; ss+=1) *rr++ = *ss;
  /* #676: (@58[1] += @47) */
  for (rr=w58+1, ss=(&w47); rr!=w58+2; rr+=1) *rr += *ss++;
  /* #677: @47 = 0 */
  w47 = 0.;
  /* #678: (@26[5] = @47) */
  for (rr=w26+5, ss=(&w47); rr!=w26+6; rr+=1) *rr = *ss++;
  /* #679: @47 = @26[2] */
  for (rr=(&w47), ss=w26+2; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #680: @47 = (-@47) */
  w47 = (- w47 );
  /* #681: (@58[2] += @47) */
  for (rr=w58+2, ss=(&w47); rr!=w58+3; rr+=1) *rr += *ss++;
  /* #682: @47 = 0 */
  w47 = 0.;
  /* #683: (@26[2] = @47) */
  for (rr=w26+2, ss=(&w47); rr!=w26+3; rr+=1) *rr = *ss++;
  /* #684: @47 = @26[1] */
  for (rr=(&w47), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #685: (@58[3] += @47) */
  for (rr=w58+3, ss=(&w47); rr!=w58+4; rr+=1) *rr += *ss++;
  /* #686: @47 = 0 */
  w47 = 0.;
  /* #687: (@26[1] = @47) */
  for (rr=w26+1, ss=(&w47); rr!=w26+2; rr+=1) *rr = *ss++;
  /* #688: @47 = @26[7] */
  for (rr=(&w47), ss=w26+7; ss!=w26+8; ss+=1) *rr++ = *ss;
  /* #689: @47 = (-@47) */
  w47 = (- w47 );
  /* #690: (@58[1] += @47) */
  for (rr=w58+1, ss=(&w47); rr!=w58+2; rr+=1) *rr += *ss++;
  /* #691: @47 = 0 */
  w47 = 0.;
  /* #692: (@26[7] = @47) */
  for (rr=w26+7, ss=(&w47); rr!=w26+8; rr+=1) *rr = *ss++;
  /* #693: @47 = @26[6] */
  for (rr=(&w47), ss=w26+6; ss!=w26+7; ss+=1) *rr++ = *ss;
  /* #694: (@58[2] += @47) */
  for (rr=w58+2, ss=(&w47); rr!=w58+3; rr+=1) *rr += *ss++;
  /* #695: @47 = 0 */
  w47 = 0.;
  /* #696: (@26[6] = @47) */
  for (rr=w26+6, ss=(&w47); rr!=w26+7; rr+=1) *rr = *ss++;
  /* #697: @47 = @26[3] */
  for (rr=(&w47), ss=w26+3; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #698: @47 = (-@47) */
  w47 = (- w47 );
  /* #699: (@58[3] += @47) */
  for (rr=w58+3, ss=(&w47); rr!=w58+4; rr+=1) *rr += *ss++;
  /* #700: @24 = (@58/@7) */
  for (i=0, rr=w24, cr=w58; i<4; ++i) (*rr++)  = ((*cr++)/w7);
  /* #701: @40 = (@40*@46) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) *= w46;
  /* #702: @24 = (@24-@40) */
  for (i=0, rr=w24, cs=w40; i<4; ++i) (*rr++) -= (*cs++);
  /* #703: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #704: @16 = (@16*@44) */
  w16 *= w44;
  /* #705: @16 = (@11*@16) */
  w16  = (w11*w16);
  /* #706: @40 = (@25*@16) */
  for (i=0, rr=w40, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #707: @24 = (@24-@40) */
  for (i=0, rr=w24, cs=w40; i<4; ++i) (*rr++) -= (*cs++);
  /* #708: @16 = dot(@41, @58) */
  w16 = casadi_dot(4, w41, w58);
  /* #709: @2 = (@2/@7) */
  for (i=0, rr=w2; i<4; ++i) (*rr++) /= w7;
  /* #710: @23 = (@23*@46) */
  for (i=0, rr=w23; i<4; ++i) (*rr++) *= w46;
  /* #711: @2 = (@2-@23) */
  for (i=0, rr=w2, cs=w23; i<4; ++i) (*rr++) -= (*cs++);
  /* #712: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) *rr++ = (- *cs++ );
  /* #713: @47 = dot(@2, @37) */
  w47 = casadi_dot(4, w2, w37);
  /* #714: @16 = (@16+@47) */
  w16 += w47;
  /* #715: @16 = (@16/@7) */
  w16 /= w7;
  /* #716: @18 = (@18*@46) */
  w18 *= w46;
  /* #717: @16 = (@16-@18) */
  w16 -= w18;
  /* #718: @2 = (@21*@16) */
  for (i=0, rr=w2, cr=w21; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #719: @17 = (@17*@15) */
  w17 *= w15;
  /* #720: @37 = dense(@17) */
  casadi_densify((&w17), casadi_s11, w37, 0);
  /* #721: @2 = (@2+@37) */
  for (i=0, rr=w2, cs=w37; i<4; ++i) (*rr++) += (*cs++);
  /* #722: @24 = (@24+@2) */
  for (i=0, rr=w24, cs=w2; i<4; ++i) (*rr++) += (*cs++);
  /* #723: (@1[6:10] += @24) */
  for (rr=w1+6, ss=w24; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #724: {@17, @16, @18, @46, @47, @48, @60, @62, @9, @54, @42, @64, @49} = vertsplit(@1) */
  w17 = w1[0];
  w16 = w1[1];
  w18 = w1[2];
  w46 = w1[3];
  w47 = w1[4];
  w48 = w1[5];
  w60 = w1[6];
  w62 = w1[7];
  w9 = w1[8];
  w54 = w1[9];
  w42 = w1[10];
  w64 = w1[11];
  w49 = w1[12];
  /* #725: @43 = project(@25) */
  casadi_sparsify(w25, (&w43), casadi_s11, 0);
  /* #726: @51 = dot(@15, @43) */
  w51 = casadi_dot(1, (&w15), (&w43));
  /* #727: @11 = (@11*@51) */
  w11 *= w51;
  /* #728: @13 = (@13*@11) */
  w13 *= w11;
  /* #729: @60 = (@60-@13) */
  w60 -= w13;
  /* #730: @5 = (@5*@11) */
  w5 *= w11;
  /* #731: @62 = (@62-@5) */
  w62 -= w5;
  /* #732: @53 = (@53*@11) */
  w53 *= w11;
  /* #733: @9 = (@9-@53) */
  w9 -= w53;
  /* #734: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #735: @52 = (@52*@44) */
  w52 *= w44;
  /* #736: @55 = (@55*@11) */
  w55 *= w11;
  /* #737: @52 = (@52+@55) */
  w52 += w55;
  /* #738: @54 = (@54-@52) */
  w54 -= w52;
  /* #739: @57 = zeros(4x4) */
  casadi_clear(w57, 16);
  /* #740: @15 = @15' */
  /* #741: @57 = mac(@36,@15,@57) */
  casadi_mtimes(w36, casadi_s3, (&w15), casadi_s12, w57, casadi_s1, w, 0);
  /* #742: @56 = @57' */
  for (i=0, rr=w56, cs=w57; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #743: {@25, @24, @2, @37} = horzsplit(@56) */
  casadi_copy(w56, 4, w25);
  casadi_copy(w56+4, 4, w24);
  casadi_copy(w56+8, 4, w2);
  casadi_copy(w56+12, 4, w37);
  /* #744: @2 = @2' */
  /* #745: {@15, @52, NULL, @55} = horzsplit(@2) */
  w15 = w2[0];
  w52 = w2[1];
  w55 = w2[3];
  /* #746: @37 = @37' */
  /* #747: {@11, @44, @53, NULL} = horzsplit(@37) */
  w11 = w37[0];
  w44 = w37[1];
  w53 = w37[2];
  /* #748: @55 = (@55-@53) */
  w55 -= w53;
  /* #749: @24 = @24' */
  /* #750: {@53, NULL, @5, @13} = horzsplit(@24) */
  w53 = w24[0];
  w5 = w24[2];
  w13 = w24[3];
  /* #751: @55 = (@55+@53) */
  w55 += w53;
  /* #752: @25 = @25' */
  /* #753: {NULL, @53, @51, @43} = horzsplit(@25) */
  w53 = w25[1];
  w51 = w25[2];
  w43 = w25[3];
  /* #754: @55 = (@55-@53) */
  w55 -= w53;
  /* #755: @55 = (@55+@42) */
  w55 += w42;
  /* #756: @44 = (@44+@15) */
  w44 += w15;
  /* #757: @44 = (@44-@13) */
  w44 -= w13;
  /* #758: @44 = (@44-@51) */
  w44 -= w51;
  /* #759: @44 = (@44+@64) */
  w44 += w64;
  /* #760: @11 = (@11-@52) */
  w11 -= w52;
  /* #761: @11 = (@11+@5) */
  w11 += w5;
  /* #762: @11 = (@11-@43) */
  w11 -= w43;
  /* #763: @11 = (@11+@49) */
  w11 += w49;
  /* #764: @68 = 00 */
  /* #765: @69 = 00 */
  /* #766: @70 = 00 */
  /* #767: @71 = 00 */
  /* #768: @72 = 00 */
  /* #769: @73 = 00 */
  /* #770: @74 = 00 */
  /* #771: @75 = 00 */
  /* #772: @76 = 00 */
  /* #773: @77 = 00 */
  /* #774: @78 = 00 */
  /* #775: @79 = 00 */
  /* #776: @80 = 00 */
  /* #777: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #778: @26 = zeros(3x3) */
  casadi_clear(w26, 9);
  /* #779: @26 = mac(@32,@3,@26) */
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #780: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #781: @33 = mac(@3,@32,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #782: @26 = (@26+@33) */
  for (i=0, rr=w26, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #783: @26 = (2.*@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #784: @33 = (@32*@45) */
  for (i=0, rr=w33, cr=w32; i<9; ++i) (*rr++)  = ((*cr++)*w45);
  /* #785: @3 = (@10*@3) */
  for (i=0, rr=w3, cs=w3; i<9; ++i) (*rr++)  = (w10*(*cs++));
  /* #786: @33 = (@33+@3) */
  for (i=0, rr=w33, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #787: @26 = (@26+@33) */
  for (i=0, rr=w26, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #788: @29 = mac(@26,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w26+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #789: @45 = dot(@29, @27) */
  w45 = casadi_dot(3, w29, w27);
  /* #790: @81 = 00 */
  /* #791: @82 = 00 */
  /* #792: @83 = 00 */
  /* #793: @84 = vertcat(@17, @16, @18, @46, @47, @48, @60, @62, @9, @54, @55, @44, @11, @68, @69, @70, @71, @72, @73, @74, @75, @76, @77, @78, @79, @80, @45, @81, @82, @83) */
  rr=w84;
  *rr++ = w17;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w60;
  *rr++ = w62;
  *rr++ = w9;
  *rr++ = w54;
  *rr++ = w55;
  *rr++ = w44;
  *rr++ = w11;
  *rr++ = w45;
  /* #794: @85 = @84[6:14] */
  for (rr=w85, ss=w84+6; ss!=w84+14; ss+=1) *rr++ = *ss;
  /* #795: (@0[3, 11, 19, 27, 35, 42, 49, 56] = @85) */
  for (cii=casadi_s13, rr=w0, ss=w85; cii!=casadi_s13+8; ++cii, ++ss) rr[*cii] = *ss;
  /* #796: @1 = zeros(13x1) */
  casadi_clear(w1, 13);
  /* #797: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #798: @26 = zeros(3x3) */
  casadi_clear(w26, 9);
  /* #799: @17 = 0.00264 */
  w17 = 2.6400000000000000e-03;
  /* #800: (@26[0] = @17) */
  for (rr=w26+0, ss=(&w17); rr!=w26+1; rr+=1) *rr = *ss++;
  /* #801: @17 = 0.00264 */
  w17 = 2.6400000000000000e-03;
  /* #802: (@26[4] = @17) */
  for (rr=w26+4, ss=(&w17); rr!=w26+5; rr+=1) *rr = *ss++;
  /* #803: @17 = 0.00496 */
  w17 = 4.9600000000000000e-03;
  /* #804: (@26[8] = @17) */
  for (rr=w26+8, ss=(&w17); rr!=w26+9; rr+=1) *rr = *ss++;
  /* #805: @33 = @26' */
  for (i=0, rr=w33, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #806: @30 = zeros(3x1) */
  casadi_clear(w30, 3);
  /* #807: @87 = zeros(3x1) */
  casadi_clear(w87, 3);
  /* #808: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #809: @3 = (@26\@3) */
  rr = w3;
  ss = w26;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s15, ss, w, casadi_s16, v, casadi_s17, r, beta, casadi_s14, casadi_s14);
    casadi_qr_solve(rr, 3, 0, casadi_s16, v, casadi_s17, r, beta, casadi_s14, casadi_s14, w);
  }
  /* #810: @35 = @3' */
  for (i=0, rr=w35, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #811: @87 = mac(@35,@28,@87) */
  for (i=0, rr=w87; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w35+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #812: @87 = (-@87) */
  for (i=0, rr=w87, cs=w87; i<3; ++i) *rr++ = (- *cs++ );
  /* #813: {@17, @16, @18} = vertsplit(@87) */
  w17 = w87[0];
  w16 = w87[1];
  w18 = w87[2];
  /* #814: @46 = ones(30x1,1nz) */
  w46 = 1.;
  /* #815: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @47, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@46) */
  w47 = w46;
  /* #816: @46 = (@18*@47) */
  w46  = (w18*w47);
  /* #817: (@30[1] += @46) */
  for (rr=w30+1, ss=(&w46); rr!=w30+2; rr+=1) *rr += *ss++;
  /* #818: @46 = (@16*@47) */
  w46  = (w16*w47);
  /* #819: @46 = (-@46) */
  w46 = (- w46 );
  /* #820: (@30[2] += @46) */
  for (rr=w30+2, ss=(&w46); rr!=w30+3; rr+=1) *rr += *ss++;
  /* #821: @29 = mac(@33,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #822: (@1[10:13] += @29) */
  for (rr=w1+10, ss=w29; rr!=w1+13; rr+=1) *rr += *ss++;
  /* #823: @68 = 00 */
  /* #824: @46 = (-@47) */
  w46 = (- w47 );
  /* #825: @69 = 00 */
  /* #826: @70 = 00 */
  /* #827: @48 = horzcat(@68, @46, @69, @70) */
  rr=(&w48);
  *rr++ = w46;
  /* #828: @48 = @48' */
  /* #829: @68 = 00 */
  /* #830: @69 = 00 */
  /* #831: @70 = 00 */
  /* #832: @46 = horzcat(@47, @68, @69, @70) */
  rr=(&w46);
  *rr++ = w47;
  /* #833: @46 = @46' */
  /* #834: @68 = 00 */
  /* #835: @70 = 00 */
  /* #836: @71 = 00 */
  /* #837: @60 = horzcat(@68, @70, @71, @47) */
  rr=(&w60);
  *rr++ = w47;
  /* #838: @60 = @60' */
  /* #839: @62 = (-@47) */
  w62 = (- w47 );
  /* #840: @70 = 00 */
  /* #841: @9 = horzcat(@69, @68, @62, @70) */
  rr=(&w9);
  *rr++ = w62;
  /* #842: @9 = @9' */
  /* #843: @25 = horzcat(@48, @46, @60, @9) */
  rr=w25;
  *rr++ = w48;
  *rr++ = w46;
  *rr++ = w60;
  *rr++ = w9;
  /* #844: @25 = nonzeros(@25) */
  /* #845: @25 = (@25*@36) */
  for (i=0, rr=w25, cs=w36; i<4; ++i) (*rr++) *= (*cs++);
  /* #846: @24 = @25[1, 0, 3, 2] */
  for (cii=casadi_s18, rr=w24, ss=w25; cii!=casadi_s18+4; ++cii) *rr++ = ss[*cii];
  /* #847: (@1[6:10] += @24) */
  for (rr=w1+6, ss=w24; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #848: {@48, @46, @60, @9, @62, @54, @55, @44, @11, @45, @49, @43, @5} = vertsplit(@1) */
  w48 = w1[0];
  w46 = w1[1];
  w60 = w1[2];
  w9 = w1[3];
  w62 = w1[4];
  w54 = w1[5];
  w55 = w1[6];
  w44 = w1[7];
  w11 = w1[8];
  w45 = w1[9];
  w49 = w1[10];
  w43 = w1[11];
  w5 = w1[12];
  /* #849: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #850: @47 = sparsity_cast(@47) */
  /* #851: @29 = mac(@26,@47,@29) */
  casadi_mtimes(w26, casadi_s15, (&w47), casadi_s20, w29, casadi_s19, w, 0);
  /* #852: @47 = @29[1] */
  for (rr=(&w47), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #853: @52 = (@18*@47) */
  w52  = (w18*w47);
  /* #854: @64 = @29[2] */
  for (rr=(&w64), ss=w29+2; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #855: @51 = (@16*@64) */
  w51  = (w16*w64);
  /* #856: @52 = (@52-@51) */
  w52 -= w51;
  /* #857: @52 = (@52+@49) */
  w52 += w49;
  /* #858: @64 = (@17*@64) */
  w64  = (w17*w64);
  /* #859: @49 = @29[0] */
  for (rr=(&w49), ss=w29+0; ss!=w29+1; ss+=1) *rr++ = *ss;
  /* #860: @51 = (@18*@49) */
  w51  = (w18*w49);
  /* #861: @64 = (@64-@51) */
  w64 -= w51;
  /* #862: @64 = (@64+@43) */
  w64 += w43;
  /* #863: @49 = (@16*@49) */
  w49  = (w16*w49);
  /* #864: @47 = (@17*@47) */
  w47  = (w17*w47);
  /* #865: @49 = (@49-@47) */
  w49 -= w47;
  /* #866: @49 = (@49+@5) */
  w49 += w5;
  /* #867: @69 = 00 */
  /* #868: @68 = 00 */
  /* #869: @70 = 00 */
  /* #870: @71 = 00 */
  /* #871: @72 = 00 */
  /* #872: @73 = 00 */
  /* #873: @74 = 00 */
  /* #874: @75 = 00 */
  /* #875: @76 = 00 */
  /* #876: @77 = 00 */
  /* #877: @78 = 00 */
  /* #878: @79 = 00 */
  /* #879: @80 = 00 */
  /* #880: @81 = 00 */
  /* #881: @82 = 00 */
  /* #882: @83 = 00 */
  /* #883: @88 = 00 */
  /* #884: @1 = vertcat(@48, @46, @60, @9, @62, @54, @55, @44, @11, @45, @52, @64, @49, @69, @68, @70, @71, @72, @73, @74, @75, @76, @77, @78, @79, @80, @81, @82, @83, @88) */
  rr=w1;
  *rr++ = w48;
  *rr++ = w46;
  *rr++ = w60;
  *rr++ = w9;
  *rr++ = w62;
  *rr++ = w54;
  *rr++ = w55;
  *rr++ = w44;
  *rr++ = w11;
  *rr++ = w45;
  *rr++ = w52;
  *rr++ = w64;
  *rr++ = w49;
  /* #885: @89 = @1[6:13] */
  for (rr=w89, ss=w1+6; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #886: (@0[4, 12, 20, 28, 36, 43, 50] = @89) */
  for (cii=casadi_s21, rr=w0, ss=w89; cii!=casadi_s21+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #887: @1 = zeros(13x1) */
  casadi_clear(w1, 13);
  /* #888: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #889: @30 = zeros(3x1) */
  casadi_clear(w30, 3);
  /* #890: @48 = ones(30x1,1nz) */
  w48 = 1.;
  /* #891: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @46, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@48) */
  w46 = w48;
  /* #892: @48 = (@18*@46) */
  w48  = (w18*w46);
  /* #893: @48 = (-@48) */
  w48 = (- w48 );
  /* #894: (@30[0] += @48) */
  for (rr=w30+0, ss=(&w48); rr!=w30+1; rr+=1) *rr += *ss++;
  /* #895: @48 = (@17*@46) */
  w48  = (w17*w46);
  /* #896: (@30[2] += @48) */
  for (rr=w30+2, ss=(&w48); rr!=w30+3; rr+=1) *rr += *ss++;
  /* #897: @29 = mac(@33,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #898: (@1[10:13] += @29) */
  for (rr=w1+10, ss=w29; rr!=w1+13; rr+=1) *rr += *ss++;
  /* #899: @69 = 00 */
  /* #900: @68 = 00 */
  /* #901: @48 = (-@46) */
  w48 = (- w46 );
  /* #902: @70 = 00 */
  /* #903: @60 = horzcat(@69, @68, @48, @70) */
  rr=(&w60);
  *rr++ = w48;
  /* #904: @60 = @60' */
  /* #905: @69 = 00 */
  /* #906: @68 = 00 */
  /* #907: @70 = 00 */
  /* #908: @48 = (-@46) */
  w48 = (- w46 );
  /* #909: @9 = horzcat(@69, @68, @70, @48) */
  rr=(&w9);
  *rr++ = w48;
  /* #910: @9 = @9' */
  /* #911: @68 = 00 */
  /* #912: @71 = 00 */
  /* #913: @48 = horzcat(@46, @68, @71, @69) */
  rr=(&w48);
  *rr++ = w46;
  /* #914: @48 = @48' */
  /* #915: @68 = 00 */
  /* #916: @71 = 00 */
  /* #917: @62 = horzcat(@70, @46, @68, @71) */
  rr=(&w62);
  *rr++ = w46;
  /* #918: @62 = @62' */
  /* #919: @24 = horzcat(@60, @9, @48, @62) */
  rr=w24;
  *rr++ = w60;
  *rr++ = w9;
  *rr++ = w48;
  *rr++ = w62;
  /* #920: @24 = nonzeros(@24) */
  /* #921: @24 = (@24*@36) */
  for (i=0, rr=w24, cs=w36; i<4; ++i) (*rr++) *= (*cs++);
  /* #922: @25 = @24[2, 3, 0, 1] */
  for (cii=casadi_s22, rr=w25, ss=w24; cii!=casadi_s22+4; ++cii) *rr++ = ss[*cii];
  /* #923: (@1[6:10] += @25) */
  for (rr=w1+6, ss=w25; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #924: {@60, @9, @48, @62, @54, @55, @44, @11, @45, @52, @64, @49, @5} = vertsplit(@1) */
  w60 = w1[0];
  w9 = w1[1];
  w48 = w1[2];
  w62 = w1[3];
  w54 = w1[4];
  w55 = w1[5];
  w44 = w1[6];
  w11 = w1[7];
  w45 = w1[8];
  w52 = w1[9];
  w64 = w1[10];
  w49 = w1[11];
  w5 = w1[12];
  /* #925: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #926: @46 = sparsity_cast(@46) */
  /* #927: @29 = mac(@26,@46,@29) */
  casadi_mtimes(w26, casadi_s15, (&w46), casadi_s23, w29, casadi_s19, w, 0);
  /* #928: @46 = @29[1] */
  for (rr=(&w46), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #929: @47 = (@18*@46) */
  w47  = (w18*w46);
  /* #930: @43 = @29[2] */
  for (rr=(&w43), ss=w29+2; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #931: @51 = (@16*@43) */
  w51  = (w16*w43);
  /* #932: @47 = (@47-@51) */
  w47 -= w51;
  /* #933: @47 = (@47+@64) */
  w47 += w64;
  /* #934: @43 = (@17*@43) */
  w43  = (w17*w43);
  /* #935: @64 = @29[0] */
  for (rr=(&w64), ss=w29+0; ss!=w29+1; ss+=1) *rr++ = *ss;
  /* #936: @51 = (@18*@64) */
  w51  = (w18*w64);
  /* #937: @43 = (@43-@51) */
  w43 -= w51;
  /* #938: @43 = (@43+@49) */
  w43 += w49;
  /* #939: @64 = (@16*@64) */
  w64  = (w16*w64);
  /* #940: @46 = (@17*@46) */
  w46  = (w17*w46);
  /* #941: @64 = (@64-@46) */
  w64 -= w46;
  /* #942: @64 = (@64+@5) */
  w64 += w5;
  /* #943: @70 = 00 */
  /* #944: @68 = 00 */
  /* #945: @71 = 00 */
  /* #946: @69 = 00 */
  /* #947: @72 = 00 */
  /* #948: @73 = 00 */
  /* #949: @74 = 00 */
  /* #950: @75 = 00 */
  /* #951: @76 = 00 */
  /* #952: @77 = 00 */
  /* #953: @78 = 00 */
  /* #954: @79 = 00 */
  /* #955: @80 = 00 */
  /* #956: @81 = 00 */
  /* #957: @82 = 00 */
  /* #958: @83 = 00 */
  /* #959: @88 = 00 */
  /* #960: @1 = vertcat(@60, @9, @48, @62, @54, @55, @44, @11, @45, @52, @47, @43, @64, @70, @68, @71, @69, @72, @73, @74, @75, @76, @77, @78, @79, @80, @81, @82, @83, @88) */
  rr=w1;
  *rr++ = w60;
  *rr++ = w9;
  *rr++ = w48;
  *rr++ = w62;
  *rr++ = w54;
  *rr++ = w55;
  *rr++ = w44;
  *rr++ = w11;
  *rr++ = w45;
  *rr++ = w52;
  *rr++ = w47;
  *rr++ = w43;
  *rr++ = w64;
  /* #961: @89 = @1[6:13] */
  for (rr=w89, ss=w1+6; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #962: (@0[5, 13, 21, 29, 37, 44, 51] = @89) */
  for (cii=casadi_s24, rr=w0, ss=w89; cii!=casadi_s24+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #963: @1 = zeros(13x1) */
  casadi_clear(w1, 13);
  /* #964: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #965: @30 = zeros(3x1) */
  casadi_clear(w30, 3);
  /* #966: @60 = ones(30x1,1nz) */
  w60 = 1.;
  /* #967: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@60) */
  w9 = w60;
  /* #968: @60 = (@16*@9) */
  w60  = (w16*w9);
  /* #969: (@30[0] += @60) */
  for (rr=w30+0, ss=(&w60); rr!=w30+1; rr+=1) *rr += *ss++;
  /* #970: @60 = (@17*@9) */
  w60  = (w17*w9);
  /* #971: @60 = (-@60) */
  w60 = (- w60 );
  /* #972: (@30[1] += @60) */
  for (rr=w30+1, ss=(&w60); rr!=w30+2; rr+=1) *rr += *ss++;
  /* #973: @29 = mac(@33,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #974: (@1[10:13] += @29) */
  for (rr=w1+10, ss=w29; rr!=w1+13; rr+=1) *rr += *ss++;
  /* #975: @70 = 00 */
  /* #976: @68 = 00 */
  /* #977: @71 = 00 */
  /* #978: @60 = (-@9) */
  w60 = (- w9 );
  /* #979: @48 = horzcat(@70, @68, @71, @60) */
  rr=(&w48);
  *rr++ = w60;
  /* #980: @48 = @48' */
  /* #981: @70 = 00 */
  /* #982: @68 = 00 */
  /* #983: @71 = 00 */
  /* #984: @60 = horzcat(@70, @68, @9, @71) */
  rr=(&w60);
  *rr++ = w9;
  /* #985: @60 = @60' */
  /* #986: @68 = 00 */
  /* #987: @62 = (-@9) */
  w62 = (- w9 );
  /* #988: @71 = 00 */
  /* #989: @54 = horzcat(@68, @62, @71, @70) */
  rr=(&w54);
  *rr++ = w62;
  /* #990: @54 = @54' */
  /* #991: @71 = 00 */
  /* #992: @70 = 00 */
  /* #993: @62 = horzcat(@9, @68, @71, @70) */
  rr=(&w62);
  *rr++ = w9;
  /* #994: @62 = @62' */
  /* #995: @25 = horzcat(@48, @60, @54, @62) */
  rr=w25;
  *rr++ = w48;
  *rr++ = w60;
  *rr++ = w54;
  *rr++ = w62;
  /* #996: @25 = nonzeros(@25) */
  /* #997: @25 = (@25*@36) */
  for (i=0, rr=w25, cs=w36; i<4; ++i) (*rr++) *= (*cs++);
  /* #998: @36 = @25[3, 2, 1, 0] */
  for (cii=casadi_s25, rr=w36, ss=w25; cii!=casadi_s25+4; ++cii) *rr++ = ss[*cii];
  /* #999: (@1[6:10] += @36) */
  for (rr=w1+6, ss=w36; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #1000: {@48, @60, @54, @62, @55, @44, @11, @45, @52, @47, @43, @64, @5} = vertsplit(@1) */
  w48 = w1[0];
  w60 = w1[1];
  w54 = w1[2];
  w62 = w1[3];
  w55 = w1[4];
  w44 = w1[5];
  w11 = w1[6];
  w45 = w1[7];
  w52 = w1[8];
  w47 = w1[9];
  w43 = w1[10];
  w64 = w1[11];
  w5 = w1[12];
  /* #1001: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #1002: @9 = sparsity_cast(@9) */
  /* #1003: @29 = mac(@26,@9,@29) */
  casadi_mtimes(w26, casadi_s15, (&w9), casadi_s26, w29, casadi_s19, w, 0);
  /* #1004: @9 = @29[1] */
  for (rr=(&w9), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #1005: @46 = (@18*@9) */
  w46  = (w18*w9);
  /* #1006: @49 = @29[2] */
  for (rr=(&w49), ss=w29+2; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #1007: @51 = (@16*@49) */
  w51  = (w16*w49);
  /* #1008: @46 = (@46-@51) */
  w46 -= w51;
  /* #1009: @46 = (@46+@43) */
  w46 += w43;
  /* #1010: @49 = (@17*@49) */
  w49  = (w17*w49);
  /* #1011: @43 = @29[0] */
  for (rr=(&w43), ss=w29+0; ss!=w29+1; ss+=1) *rr++ = *ss;
  /* #1012: @18 = (@18*@43) */
  w18 *= w43;
  /* #1013: @49 = (@49-@18) */
  w49 -= w18;
  /* #1014: @49 = (@49+@64) */
  w49 += w64;
  /* #1015: @16 = (@16*@43) */
  w16 *= w43;
  /* #1016: @17 = (@17*@9) */
  w17 *= w9;
  /* #1017: @16 = (@16-@17) */
  w16 -= w17;
  /* #1018: @16 = (@16+@5) */
  w16 += w5;
  /* #1019: @68 = 00 */
  /* #1020: @71 = 00 */
  /* #1021: @70 = 00 */
  /* #1022: @69 = 00 */
  /* #1023: @72 = 00 */
  /* #1024: @73 = 00 */
  /* #1025: @74 = 00 */
  /* #1026: @75 = 00 */
  /* #1027: @76 = 00 */
  /* #1028: @77 = 00 */
  /* #1029: @78 = 00 */
  /* #1030: @79 = 00 */
  /* #1031: @80 = 00 */
  /* #1032: @81 = 00 */
  /* #1033: @82 = 00 */
  /* #1034: @83 = 00 */
  /* #1035: @88 = 00 */
  /* #1036: @1 = vertcat(@48, @60, @54, @62, @55, @44, @11, @45, @52, @47, @46, @49, @16, @68, @71, @70, @69, @72, @73, @74, @75, @76, @77, @78, @79, @80, @81, @82, @83, @88) */
  rr=w1;
  *rr++ = w48;
  *rr++ = w60;
  *rr++ = w54;
  *rr++ = w62;
  *rr++ = w55;
  *rr++ = w44;
  *rr++ = w11;
  *rr++ = w45;
  *rr++ = w52;
  *rr++ = w47;
  *rr++ = w46;
  *rr++ = w49;
  *rr++ = w16;
  /* #1037: @89 = @1[6:13] */
  for (rr=w89, ss=w1+6; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #1038: (@0[6, 14, 22, 30, 38, 45, 52] = @89) */
  for (cii=casadi_s27, rr=w0, ss=w89; cii!=casadi_s27+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #1039: @1 = zeros(13x1) */
  casadi_clear(w1, 13);
  /* #1040: @36 = zeros(4x1) */
  casadi_clear(w36, 4);
  /* #1041: @26 = zeros(3x3) */
  casadi_clear(w26, 9);
  /* #1042: @48 = ones(30x1,1nz) */
  w48 = 1.;
  /* #1043: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @60, NULL, NULL, NULL} = vertsplit(@48) */
  w60 = w48;
  /* #1044: @27 = (@27*@60) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) *= w60;
  /* #1045: @26 = mac(@27,@31,@26) */
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w31+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #1046: @60 = dot(@32, @26) */
  w60 = casadi_dot(9, w32, w26);
  /* #1047: @60 = (2.*@60) */
  w60 = (2.* w60 );
  /* #1048: (@36[0] += @60) */
  for (rr=w36+0, ss=(&w60); rr!=w36+1; rr+=1) *rr += *ss++;
  /* #1049: @32 = (@10*@26) */
  for (i=0, rr=w32, cs=w26; i<9; ++i) (*rr++)  = (w10*(*cs++));
  /* #1050: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #1051: @26 = (2.*@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #1052: @33 = mac(@26,@38,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w26+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1053: @32 = (@32+@33) */
  for (i=0, rr=w32, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #1054: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #1055: @33 = mac(@39,@26,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w39+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1056: @32 = (@32+@33) */
  for (i=0, rr=w32, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #1057: @10 = @32[5] */
  for (rr=(&w10), ss=w32+5; ss!=w32+6; ss+=1) *rr++ = *ss;
  /* #1058: (@36[1] += @10) */
  for (rr=w36+1, ss=(&w10); rr!=w36+2; rr+=1) *rr += *ss++;
  /* #1059: @10 = 0 */
  w10 = 0.;
  /* #1060: (@32[5] = @10) */
  for (rr=w32+5, ss=(&w10); rr!=w32+6; rr+=1) *rr = *ss++;
  /* #1061: @10 = @32[2] */
  for (rr=(&w10), ss=w32+2; ss!=w32+3; ss+=1) *rr++ = *ss;
  /* #1062: @10 = (-@10) */
  w10 = (- w10 );
  /* #1063: (@36[2] += @10) */
  for (rr=w36+2, ss=(&w10); rr!=w36+3; rr+=1) *rr += *ss++;
  /* #1064: @10 = 0 */
  w10 = 0.;
  /* #1065: (@32[2] = @10) */
  for (rr=w32+2, ss=(&w10); rr!=w32+3; rr+=1) *rr = *ss++;
  /* #1066: @10 = @32[1] */
  for (rr=(&w10), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #1067: (@36[3] += @10) */
  for (rr=w36+3, ss=(&w10); rr!=w36+4; rr+=1) *rr += *ss++;
  /* #1068: @10 = 0 */
  w10 = 0.;
  /* #1069: (@32[1] = @10) */
  for (rr=w32+1, ss=(&w10); rr!=w32+2; rr+=1) *rr = *ss++;
  /* #1070: @10 = @32[7] */
  for (rr=(&w10), ss=w32+7; ss!=w32+8; ss+=1) *rr++ = *ss;
  /* #1071: @10 = (-@10) */
  w10 = (- w10 );
  /* #1072: (@36[1] += @10) */
  for (rr=w36+1, ss=(&w10); rr!=w36+2; rr+=1) *rr += *ss++;
  /* #1073: @10 = 0 */
  w10 = 0.;
  /* #1074: (@32[7] = @10) */
  for (rr=w32+7, ss=(&w10); rr!=w32+8; rr+=1) *rr = *ss++;
  /* #1075: @10 = @32[6] */
  for (rr=(&w10), ss=w32+6; ss!=w32+7; ss+=1) *rr++ = *ss;
  /* #1076: (@36[2] += @10) */
  for (rr=w36+2, ss=(&w10); rr!=w36+3; rr+=1) *rr += *ss++;
  /* #1077: @10 = 0 */
  w10 = 0.;
  /* #1078: (@32[6] = @10) */
  for (rr=w32+6, ss=(&w10); rr!=w32+7; rr+=1) *rr = *ss++;
  /* #1079: @10 = @32[3] */
  for (rr=(&w10), ss=w32+3; ss!=w32+4; ss+=1) *rr++ = *ss;
  /* #1080: @10 = (-@10) */
  w10 = (- w10 );
  /* #1081: (@36[3] += @10) */
  for (rr=w36+3, ss=(&w10); rr!=w36+4; rr+=1) *rr += *ss++;
  /* #1082: @25 = (@36/@7) */
  for (i=0, rr=w25, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)/w7);
  /* #1083: @10 = dot(@41, @36) */
  w10 = casadi_dot(4, w41, w36);
  /* #1084: @10 = (@10/@7) */
  w10 /= w7;
  /* #1085: @21 = (@21*@10) */
  for (i=0, rr=w21; i<4; ++i) (*rr++) *= w10;
  /* #1086: @25 = (@25+@21) */
  for (i=0, rr=w25, cs=w21; i<4; ++i) (*rr++) += (*cs++);
  /* #1087: (@1[6:10] += @25) */
  for (rr=w1+6, ss=w25; rr!=w1+10; rr+=1) *rr += *ss++;
  /* #1088: {@10, @7, @60, @48, @54, @62, @55, @44, @11, @45, @52, @47, @46} = vertsplit(@1) */
  w10 = w1[0];
  w7 = w1[1];
  w60 = w1[2];
  w48 = w1[3];
  w54 = w1[4];
  w62 = w1[5];
  w55 = w1[6];
  w44 = w1[7];
  w11 = w1[8];
  w45 = w1[9];
  w52 = w1[10];
  w47 = w1[11];
  w46 = w1[12];
  /* #1089: @68 = 00 */
  /* #1090: @71 = 00 */
  /* #1091: @70 = 00 */
  /* #1092: @69 = 00 */
  /* #1093: @72 = 00 */
  /* #1094: @73 = 00 */
  /* #1095: @74 = 00 */
  /* #1096: @75 = 00 */
  /* #1097: @76 = 00 */
  /* #1098: @77 = 00 */
  /* #1099: @78 = 00 */
  /* #1100: @79 = 00 */
  /* #1101: @80 = 00 */
  /* #1102: @81 = 00 */
  /* #1103: @82 = 00 */
  /* #1104: @83 = 00 */
  /* #1105: @88 = 00 */
  /* #1106: @1 = vertcat(@10, @7, @60, @48, @54, @62, @55, @44, @11, @45, @52, @47, @46, @68, @71, @70, @69, @72, @73, @74, @75, @76, @77, @78, @79, @80, @81, @82, @83, @88) */
  rr=w1;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w60;
  *rr++ = w48;
  *rr++ = w54;
  *rr++ = w62;
  *rr++ = w55;
  *rr++ = w44;
  *rr++ = w11;
  *rr++ = w45;
  *rr++ = w52;
  *rr++ = w47;
  *rr++ = w46;
  /* #1107: @25 = @1[6:10] */
  for (rr=w25, ss=w1+6; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #1108: (@0[7:39:8] = @25) */
  for (rr=w0+7, ss=w25; rr!=w0+39; rr+=8) *rr = *ss++;
  /* #1109: @90 = @0' */
  casadi_trans(w0,casadi_s28, w90, casadi_s28, iw);
  /* #1110: output[0][0] = @90 */
  casadi_copy(w90, 57, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s29;
    case 1: return casadi_s29;
    case 2: return casadi_s3;
    case 3: return casadi_s30;
    case 4: return casadi_s29;
    case 5: return casadi_s29;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s28;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 36;
  if (sz_res) *sz_res = 31;
  if (sz_iw) *sz_iw = 31;
  if (sz_w) *sz_w = 412;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
