/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s6[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[13] = {0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s8[13] = {0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28, 41, 42};
static const casadi_int casadi_s9[13] = {0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37, 41, 42};
static const casadi_int casadi_s10[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s11[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s12[11] = {4, 4, 0, 1, 2, 3, 4, 1, 0, 3, 2};
static const casadi_int casadi_s13[3] = {0, 3, 2};
static const casadi_int casadi_s14[11] = {0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13};
static const casadi_int casadi_s15[11] = {4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32};
static const casadi_int casadi_s16[11] = {1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38};
static const casadi_int casadi_s17[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s18[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s19[11] = {4, 4, 0, 1, 2, 3, 4, 2, 3, 0, 1};
static const casadi_int casadi_s20[3] = {3, 0, 1};
static const casadi_int casadi_s21[11] = {8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36};
static const casadi_int casadi_s22[11] = {2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39};
static const casadi_int casadi_s23[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s24[11] = {4, 4, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s25[3] = {2, 1, 0};
static const casadi_int casadi_s26[63] = {17, 17, 0, 4, 8, 12, 16, 19, 22, 25, 25, 25, 25, 29, 33, 37, 41, 42, 43, 43, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s27[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s28[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s29[3] = {0, 0, 0};
static const casadi_int casadi_s30[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s31[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s32[20] = {0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* quadrotor_cost_ext_cost_fun_jac_hess:(i0[13],i1[4],i2[],i3[13])->(o0,o1[17],o2[17x17,43nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+5, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+21, *w16=w+34, w17, w18, w19, w20, *w21=w+41, *w22=w+44, *w23=w+53, *w24=w+57, *w25=w+61, *w26=w+65, *w27=w+81, *w28=w+85, *w29=w+89, *w30=w+93, *w31=w+97, *w32=w+113, *w33=w+129, *w34=w+132, *w35=w+135, *w36=w+137, *w37=w+139, *w38=w+148, w39, w40, w41, w42, *w43=w+168, *w44=w+211, *w50=w+220, w52, w53, w54, w55, w56, w57, w58, w59, w60, *w61=w+237, *w62=w+254, *w67=w+265, *w68=w+273;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #16: @16 = @15[:3] */
  for (rr=w16, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #17: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #18: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #19: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #20: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #21: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #22: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #23: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #24: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #25: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #26: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #27: @18 = input[0][10] */
  w18 = arg[0] ? arg[0][10] : 0;
  /* #28: @19 = input[0][11] */
  w19 = arg[0] ? arg[0][11] : 0;
  /* #29: @20 = input[0][12] */
  w20 = arg[0] ? arg[0][12] : 0;
  /* #30: @15 = vertcat(@2, @3, @4, @5, @6, @7, @12, @13, @14, @17, @18, @19, @20) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #31: @21 = @15[:3] */
  for (rr=w21, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #32: @16 = (@16-@21) */
  for (i=0, rr=w16, cs=w21; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @21 = @16' */
  casadi_copy(w16, 3, w21);
  /* #34: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #35: @2 = 15.5 */
  w2 = 1.5500000000000000e+01;
  /* #36: (@22[0] = @2) */
  for (rr=w22+0, ss=(&w2); rr!=w22+1; rr+=1) *rr = *ss++;
  /* #37: @2 = 15.5 */
  w2 = 1.5500000000000000e+01;
  /* #38: (@22[4] = @2) */
  for (rr=w22+4, ss=(&w2); rr!=w22+5; rr+=1) *rr = *ss++;
  /* #39: @2 = 15.5 */
  w2 = 1.5500000000000000e+01;
  /* #40: (@22[8] = @2) */
  for (rr=w22+8, ss=(&w2); rr!=w22+9; rr+=1) *rr = *ss++;
  /* #41: @1 = mac(@21,@22,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #42: @0 = mac(@1,@16,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #43: @2 = 0 */
  w2 = 0.;
  /* #44: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #45: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #46: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #47: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #48: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #49: @24 = vertcat(@3, @4, @5, @6) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #50: @25 = @24' */
  casadi_copy(w24, 4, w25);
  /* #51: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #52: @3 = 0.033557 */
  w3 = 3.3557046979865772e-02;
  /* #53: (@26[0] = @3) */
  for (rr=w26+0, ss=(&w3); rr!=w26+1; rr+=1) *rr = *ss++;
  /* #54: @3 = 200 */
  w3 = 200.;
  /* #55: (@26[5] = @3) */
  for (rr=w26+5, ss=(&w3); rr!=w26+6; rr+=1) *rr = *ss++;
  /* #56: @3 = 200 */
  w3 = 200.;
  /* #57: (@26[10] = @3) */
  for (rr=w26+10, ss=(&w3); rr!=w26+11; rr+=1) *rr = *ss++;
  /* #58: @3 = 200 */
  w3 = 200.;
  /* #59: (@26[15] = @3) */
  for (rr=w26+15, ss=(&w3); rr!=w26+16; rr+=1) *rr = *ss++;
  /* #60: @23 = mac(@25,@26,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #61: @2 = mac(@23,@24,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #62: @0 = (@0+@2) */
  w0 += w2;
  /* #63: @2 = 1 */
  w2 = 1.;
  /* #64: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #65: @3 = (-@13) */
  w3 = (- w13 );
  /* #66: @4 = (-@14) */
  w4 = (- w14 );
  /* #67: @5 = (-@17) */
  w5 = (- w17 );
  /* #68: @27 = horzcat(@12, @3, @4, @5) */
  rr=w27;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #69: @27 = @27' */
  /* #70: @3 = (-@17) */
  w3 = (- w17 );
  /* #71: @28 = horzcat(@13, @12, @3, @14) */
  rr=w28;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w14;
  /* #72: @28 = @28' */
  /* #73: @3 = (-@13) */
  w3 = (- w13 );
  /* #74: @29 = horzcat(@14, @17, @12, @3) */
  rr=w29;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w12;
  *rr++ = w3;
  /* #75: @29 = @29' */
  /* #76: @14 = (-@14) */
  w14 = (- w14 );
  /* #77: @30 = horzcat(@17, @14, @13, @12) */
  rr=w30;
  *rr++ = w17;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w12;
  /* #78: @30 = @30' */
  /* #79: @31 = horzcat(@27, @28, @29, @30) */
  rr=w31;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #80: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #81: @9 = (-@9) */
  w9 = (- w9 );
  /* #82: @10 = (-@10) */
  w10 = (- w10 );
  /* #83: @11 = (-@11) */
  w11 = (- w11 );
  /* #84: @27 = vertcat(@8, @9, @10, @11) */
  rr=w27;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #85: @25 = mac(@32,@27,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w32+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #86: @8 = @25[0] */
  for (rr=(&w8), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #87: @2 = (@2-@8) */
  w2 -= w8;
  /* #88: @8 = 0 */
  w8 = 0.;
  /* #89: @21 = @25[1:4] */
  for (rr=w21, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #90: @33 = @21' */
  casadi_copy(w21, 3, w33);
  /* #91: @34 = @25[1:4] */
  for (rr=w34, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #92: @8 = mac(@33,@34,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #93: @2 = (@2+@8) */
  w2 += w8;
  /* #94: @0 = (@0+@2) */
  w0 += w2;
  /* #95: @2 = 0.2 */
  w2 = 2.0000000000000001e-01;
  /* #96: @8 = 0 */
  w8 = 0.;
  /* #97: @35 = @15[10:12] */
  for (rr=w35, ss=w15+10; ss!=w15+12; ss+=1) *rr++ = *ss;
  /* #98: @36 = @35' */
  casadi_copy(w35, 2, w36);
  /* #99: @8 = mac(@36,@35,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w36+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #100: @2 = (@2*@8) */
  w2 *= w8;
  /* #101: @0 = (@0+@2) */
  w0 += w2;
  /* #102: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #103: @23 = @23' */
  /* #104: @25 = zeros(1x4) */
  casadi_clear(w25, 4);
  /* #105: @24 = @24' */
  /* #106: @32 = @26' */
  for (i=0, rr=w32, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #107: @25 = mac(@24,@32,@25) */
  for (i=0, rr=w25; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w32+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #108: @25 = @25' */
  /* #109: @23 = (@23+@25) */
  for (i=0, rr=w23, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #110: {@0, @2, @8, @9} = vertsplit(@23) */
  w0 = w23[0];
  w2 = w23[1];
  w8 = w23[2];
  w9 = w23[3];
  /* #111: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #112: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #113: output[1][2] = @8 */
  if (res[1]) res[1][2] = w8;
  /* #114: output[1][3] = @9 */
  if (res[1]) res[1][3] = w9;
  /* #115: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #116: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #117: @36 = (@9*@35) */
  for (i=0, rr=w36, cs=w35; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #118: @35 = @35' */
  /* #119: @35 = (@9*@35) */
  for (i=0, rr=w35, cs=w35; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #120: @35 = @35' */
  /* #121: @36 = (@36+@35) */
  for (i=0, rr=w36, cs=w35; i<2; ++i) (*rr++) += (*cs++);
  /* #122: (@15[10:12] += @36) */
  for (rr=w15+10, ss=w36; rr!=w15+12; rr+=1) *rr += *ss++;
  /* #123: @1 = @1' */
  /* #124: @33 = zeros(1x3) */
  casadi_clear(w33, 3);
  /* #125: @16 = @16' */
  /* #126: @37 = @22' */
  for (i=0, rr=w37, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #127: @33 = mac(@16,@37,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #128: @33 = @33' */
  /* #129: @1 = (@1+@33) */
  for (i=0, rr=w1, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #130: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #131: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #132: {@8, @2, @0, @10, @11, @17, @14, @13, @12, @3, @4, @5, @6} = vertsplit(@15) */
  w8 = w15[0];
  w2 = w15[1];
  w0 = w15[2];
  w10 = w15[3];
  w11 = w15[4];
  w17 = w15[5];
  w14 = w15[6];
  w13 = w15[7];
  w12 = w15[8];
  w3 = w15[9];
  w4 = w15[10];
  w5 = w15[11];
  w6 = w15[12];
  /* #133: output[1][4] = @8 */
  if (res[1]) res[1][4] = w8;
  /* #134: output[1][5] = @2 */
  if (res[1]) res[1][5] = w2;
  /* #135: output[1][6] = @0 */
  if (res[1]) res[1][6] = w0;
  /* #136: output[1][7] = @10 */
  if (res[1]) res[1][7] = w10;
  /* #137: output[1][8] = @11 */
  if (res[1]) res[1][8] = w11;
  /* #138: output[1][9] = @17 */
  if (res[1]) res[1][9] = w17;
  /* #139: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #140: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #141: (@23[1:4] += @21) */
  for (rr=w23+1, ss=w21; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #142: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #143: @17 = -1 */
  w17 = -1.;
  /* #144: (@23[0] += @17) */
  for (rr=w23+0, ss=(&w17); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #145: @25 = @27' */
  casadi_copy(w27, 4, w25);
  /* #146: @31 = mac(@23,@25,@31) */
  for (i=0, rr=w31; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #147: @38 = @31' */
  for (i=0, rr=w38, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #148: {@23, @24, @28, @29} = horzsplit(@38) */
  casadi_copy(w38, 4, w23);
  casadi_copy(w38+4, 4, w24);
  casadi_copy(w38+8, 4, w28);
  casadi_copy(w38+12, 4, w29);
  /* #149: @29 = @29' */
  /* #150: {@17, @11, @10, @0} = horzsplit(@29) */
  w17 = w29[0];
  w11 = w29[1];
  w10 = w29[2];
  w0 = w29[3];
  /* #151: @28 = @28' */
  /* #152: {@2, @8, @7, @18} = horzsplit(@28) */
  w2 = w28[0];
  w8 = w28[1];
  w7 = w28[2];
  w18 = w28[3];
  /* #153: @0 = (@0+@7) */
  w0 += w7;
  /* #154: @24 = @24' */
  /* #155: {@7, @19, @20, @39} = horzsplit(@24) */
  w7 = w24[0];
  w19 = w24[1];
  w20 = w24[2];
  w39 = w24[3];
  /* #156: @0 = (@0+@19) */
  w0 += w19;
  /* #157: @23 = @23' */
  /* #158: {@19, @40, @41, @42} = horzsplit(@23) */
  w19 = w23[0];
  w40 = w23[1];
  w41 = w23[2];
  w42 = w23[3];
  /* #159: @0 = (@0+@19) */
  w0 += w19;
  /* #160: @0 = (@0+@14) */
  w0 += w14;
  /* #161: output[1][10] = @0 */
  if (res[1]) res[1][10] = w0;
  /* #162: @10 = (@10-@18) */
  w10 -= w18;
  /* #163: @10 = (@10+@7) */
  w10 += w7;
  /* #164: @10 = (@10-@40) */
  w10 -= w40;
  /* #165: @10 = (@10+@13) */
  w10 += w13;
  /* #166: output[1][11] = @10 */
  if (res[1]) res[1][11] = w10;
  /* #167: @2 = (@2-@11) */
  w2 -= w11;
  /* #168: @2 = (@2+@39) */
  w2 += w39;
  /* #169: @2 = (@2-@41) */
  w2 -= w41;
  /* #170: @2 = (@2+@12) */
  w2 += w12;
  /* #171: output[1][12] = @2 */
  if (res[1]) res[1][12] = w2;
  /* #172: @17 = (@17+@8) */
  w17 += w8;
  /* #173: @17 = (@17-@20) */
  w17 -= w20;
  /* #174: @17 = (@17-@42) */
  w17 -= w42;
  /* #175: @17 = (@17+@3) */
  w17 += w3;
  /* #176: output[1][13] = @17 */
  if (res[1]) res[1][13] = w17;
  /* #177: output[1][14] = @4 */
  if (res[1]) res[1][14] = w4;
  /* #178: output[1][15] = @5 */
  if (res[1]) res[1][15] = w5;
  /* #179: output[1][16] = @6 */
  if (res[1]) res[1][16] = w6;
  /* #180: @43 = zeros(17x17,43nz) */
  casadi_clear(w43, 43);
  /* #181: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #182: @44 = ones(17x1,9nz) */
  casadi_fill(w44, 9, 1.);
  /* #183: {@6, NULL, NULL, NULL, @5, NULL, NULL, @4, @17, @3, @42, NULL, NULL, NULL, @20, @8, @2} = vertsplit(@44) */
  w6 = w44[0];
  w5 = w44[1];
  w4 = w44[2];
  w17 = w44[3];
  w3 = w44[4];
  w42 = w44[5];
  w20 = w44[6];
  w8 = w44[7];
  w2 = w44[8];
  /* #184: @45 = 00 */
  /* #185: @46 = 00 */
  /* #186: @47 = 00 */
  /* #187: @12 = vertcat(@6, @45, @46, @47) */
  rr=(&w12);
  *rr++ = w6;
  /* #188: @6 = @12' */
  casadi_copy((&w12), 1, (&w6));
  /* #189: @23 = mac(@6,@26,@23) */
  casadi_mtimes((&w6), casadi_s2, w26, casadi_s1, w23, casadi_s0, w, 0);
  /* #190: @23 = @23' */
  /* #191: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #192: @12 = @12' */
  /* #193: @24 = mac(@12,@32,@24) */
  casadi_mtimes((&w12), casadi_s2, w32, casadi_s1, w24, casadi_s0, w, 0);
  /* #194: @24 = @24' */
  /* #195: @23 = (@23+@24) */
  for (i=0, rr=w23, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #196: {@12, @6, @41, @39} = vertsplit(@23) */
  w12 = w23[0];
  w6 = w23[1];
  w41 = w23[2];
  w39 = w23[3];
  /* #197: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #198: @45 = 00 */
  /* #199: @46 = 00 */
  /* #200: @47 = 00 */
  /* #201: @48 = 00 */
  /* #202: @49 = 00 */
  /* #203: @50 = vertcat(@5, @45, @46, @4, @17, @3, @42, @47, @48, @49, @20, @8, @2) */
  rr=w50;
  *rr++ = w5;
  *rr++ = w4;
  *rr++ = w17;
  *rr++ = w3;
  *rr++ = w42;
  *rr++ = w20;
  *rr++ = w8;
  *rr++ = w2;
  /* #204: @36 = @50[5:7] */
  for (rr=w36, ss=w50+5; ss!=w50+7; ss+=1) *rr++ = *ss;
  /* #205: @35 = (@9*@36) */
  for (i=0, rr=w35, cs=w36; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #206: @36 = @36' */
  /* #207: @36 = (@9*@36) */
  for (i=0, rr=w36, cs=w36; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #208: @36 = @36' */
  /* #209: @35 = (@35+@36) */
  for (i=0, rr=w35, cs=w36; i<2; ++i) (*rr++) += (*cs++);
  /* #210: (@15[10:12] += @35) */
  for (rr=w15+10, ss=w35; rr!=w15+12; rr+=1) *rr += *ss++;
  /* #211: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #212: @5 = sparsity_cast(@5) */
  /* #213: @5 = (-@5) */
  w5 = (- w5 );
  /* #214: @9 = @5' */
  casadi_copy((&w5), 1, (&w9));
  /* #215: @34 = mac(@9,@22,@34) */
  casadi_mtimes((&w9), casadi_s5, w22, casadi_s4, w34, casadi_s3, w, 0);
  /* #216: @34 = @34' */
  /* #217: @21 = zeros(1x3) */
  casadi_clear(w21, 3);
  /* #218: @5 = @5' */
  /* #219: @21 = mac(@5,@37,@21) */
  casadi_mtimes((&w5), casadi_s5, w37, casadi_s4, w21, casadi_s3, w, 0);
  /* #220: @21 = @21' */
  /* #221: @34 = (@34+@21) */
  for (i=0, rr=w34, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #222: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #223: (@15[:3] += @34) */
  for (rr=w15+0, ss=w34; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #224: {@5, @9, @4, @17, @3, @20, @8, @2, @11, @10, @13, @40, @7} = vertsplit(@15) */
  w5 = w15[0];
  w9 = w15[1];
  w4 = w15[2];
  w17 = w15[3];
  w3 = w15[4];
  w20 = w15[5];
  w8 = w15[6];
  w2 = w15[7];
  w11 = w15[8];
  w10 = w15[9];
  w13 = w15[10];
  w40 = w15[11];
  w7 = w15[12];
  /* #225: @38 = zeros(4x4) */
  casadi_clear(w38, 16);
  /* #226: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #227: @45 = 00 */
  /* #228: @46 = 00 */
  /* #229: @51 = 00 */
  /* #230: @18 = horzcat(@42, @45, @46, @51) */
  rr=(&w18);
  *rr++ = w42;
  /* #231: @18 = @18' */
  /* #232: @45 = 00 */
  /* #233: @0 = horzcat(@47, @42, @45, @48) */
  rr=(&w0);
  *rr++ = w42;
  /* #234: @0 = @0' */
  /* #235: @45 = 00 */
  /* #236: @14 = horzcat(@48, @49, @42, @45) */
  rr=(&w14);
  *rr++ = w42;
  /* #237: @14 = @14' */
  /* #238: @48 = 00 */
  /* #239: @19 = horzcat(@49, @48, @47, @42) */
  rr=(&w19);
  *rr++ = w42;
  /* #240: @19 = @19' */
  /* #241: @24 = horzcat(@18, @0, @14, @19) */
  rr=w24;
  *rr++ = w18;
  *rr++ = w0;
  *rr++ = w14;
  *rr++ = w19;
  /* #242: @28 = @24' */
  casadi_trans(w24,casadi_s6, w28, casadi_s6, iw);
  /* #243: @28 = nonzeros(@28) */
  /* #244: @28 = (@28*@27) */
  for (i=0, rr=w28, cs=w27; i<4; ++i) (*rr++) *= (*cs++);
  /* #245: @34 = @28[1:4] */
  for (rr=w34, ss=w28+1; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #246: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #247: @34 = @28[1:4] */
  for (rr=w34, ss=w28+1; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #248: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #249: @38 = mac(@23,@25,@38) */
  for (i=0, rr=w38; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #250: @31 = @38' */
  for (i=0, rr=w31, cs=w38; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #251: {@23, @28, @24, @29} = horzsplit(@31) */
  casadi_copy(w31, 4, w23);
  casadi_copy(w31+4, 4, w28);
  casadi_copy(w31+8, 4, w24);
  casadi_copy(w31+12, 4, w29);
  /* #252: @29 = @29' */
  /* #253: {@18, @0, @14, @19} = horzsplit(@29) */
  w18 = w29[0];
  w0 = w29[1];
  w14 = w29[2];
  w19 = w29[3];
  /* #254: @24 = @24' */
  /* #255: {@42, @52, @53, @54} = horzsplit(@24) */
  w42 = w24[0];
  w52 = w24[1];
  w53 = w24[2];
  w54 = w24[3];
  /* #256: @19 = (@19+@53) */
  w19 += w53;
  /* #257: @28 = @28' */
  /* #258: {@53, @55, @56, @57} = horzsplit(@28) */
  w53 = w28[0];
  w55 = w28[1];
  w56 = w28[2];
  w57 = w28[3];
  /* #259: @19 = (@19+@55) */
  w19 += w55;
  /* #260: @23 = @23' */
  /* #261: {@55, @58, @59, @60} = horzsplit(@23) */
  w55 = w23[0];
  w58 = w23[1];
  w59 = w23[2];
  w60 = w23[3];
  /* #262: @19 = (@19+@55) */
  w19 += w55;
  /* #263: @19 = (@19+@8) */
  w19 += w8;
  /* #264: @14 = (@14-@54) */
  w14 -= w54;
  /* #265: @14 = (@14+@53) */
  w14 += w53;
  /* #266: @14 = (@14-@58) */
  w14 -= w58;
  /* #267: @14 = (@14+@2) */
  w14 += w2;
  /* #268: @42 = (@42-@0) */
  w42 -= w0;
  /* #269: @42 = (@42+@57) */
  w42 += w57;
  /* #270: @42 = (@42-@59) */
  w42 -= w59;
  /* #271: @42 = (@42+@11) */
  w42 += w11;
  /* #272: @18 = (@18+@52) */
  w18 += w52;
  /* #273: @18 = (@18-@56) */
  w18 -= w56;
  /* #274: @18 = (@18-@60) */
  w18 -= w60;
  /* #275: @18 = (@18+@10) */
  w18 += w10;
  /* #276: @61 = vertcat(@12, @6, @41, @39, @5, @9, @4, @17, @3, @20, @19, @14, @42, @18, @13, @40, @7) */
  rr=w61;
  *rr++ = w12;
  *rr++ = w6;
  *rr++ = w41;
  *rr++ = w39;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w4;
  *rr++ = w17;
  *rr++ = w3;
  *rr++ = w20;
  *rr++ = w19;
  *rr++ = w14;
  *rr++ = w42;
  *rr++ = w18;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w7;
  /* #277: @15 = @61[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14, 15] */
  for (cii=casadi_s7, rr=w15, ss=w61; cii!=casadi_s7+13; ++cii) *rr++ = ss[*cii];
  /* #278: (@43[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28, 41, 42] = @15) */
  for (cii=casadi_s8, rr=w43, ss=w15; cii!=casadi_s8+13; ++cii, ++ss) rr[*cii] = *ss;
  /* #279: @15 = @61[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14, 15] */
  for (cii=casadi_s7, rr=w15, ss=w61; cii!=casadi_s7+13; ++cii) *rr++ = ss[*cii];
  /* #280: (@43[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37, 41, 42] = @15) */
  for (cii=casadi_s9, rr=w43, ss=w15; cii!=casadi_s9+13; ++cii, ++ss) rr[*cii] = *ss;
  /* #281: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #282: @49 = 00 */
  /* #283: @34 = ones(17x1,3nz) */
  casadi_fill(w34, 3, 1.);
  /* #284: {NULL, @12, NULL, NULL, NULL, @6, NULL, NULL, NULL, NULL, NULL, @41, NULL, NULL, NULL, NULL, NULL} = vertsplit(@34) */
  w12 = w34[0];
  w6 = w34[1];
  w41 = w34[2];
  /* #285: @48 = 00 */
  /* #286: @47 = 00 */
  /* #287: @39 = vertcat(@49, @12, @48, @47) */
  rr=(&w39);
  *rr++ = w12;
  /* #288: @12 = @39' */
  casadi_copy((&w39), 1, (&w12));
  /* #289: @23 = mac(@12,@26,@23) */
  casadi_mtimes((&w12), casadi_s10, w26, casadi_s1, w23, casadi_s0, w, 0);
  /* #290: @23 = @23' */
  /* #291: @28 = zeros(1x4) */
  casadi_clear(w28, 4);
  /* #292: @39 = @39' */
  /* #293: @28 = mac(@39,@32,@28) */
  casadi_mtimes((&w39), casadi_s10, w32, casadi_s1, w28, casadi_s0, w, 0);
  /* #294: @28 = @28' */
  /* #295: @23 = (@23+@28) */
  for (i=0, rr=w23, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #296: {@39, @12, @5, @9} = vertsplit(@23) */
  w39 = w23[0];
  w12 = w23[1];
  w5 = w23[2];
  w9 = w23[3];
  /* #297: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #298: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #299: @6 = sparsity_cast(@6) */
  /* #300: @6 = (-@6) */
  w6 = (- w6 );
  /* #301: @4 = @6' */
  casadi_copy((&w6), 1, (&w4));
  /* #302: @34 = mac(@4,@22,@34) */
  casadi_mtimes((&w4), casadi_s11, w22, casadi_s4, w34, casadi_s3, w, 0);
  /* #303: @34 = @34' */
  /* #304: @21 = zeros(1x3) */
  casadi_clear(w21, 3);
  /* #305: @6 = @6' */
  /* #306: @21 = mac(@6,@37,@21) */
  casadi_mtimes((&w6), casadi_s11, w37, casadi_s4, w21, casadi_s3, w, 0);
  /* #307: @21 = @21' */
  /* #308: @34 = (@34+@21) */
  for (i=0, rr=w34, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #309: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #310: (@15[:3] += @34) */
  for (rr=w15+0, ss=w34; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #311: {@6, @4, @17, @3, @20, @19, @14, @42, @18, @13, @40, @7, @10} = vertsplit(@15) */
  w6 = w15[0];
  w4 = w15[1];
  w17 = w15[2];
  w3 = w15[3];
  w20 = w15[4];
  w19 = w15[5];
  w14 = w15[6];
  w42 = w15[7];
  w18 = w15[8];
  w13 = w15[9];
  w40 = w15[10];
  w7 = w15[11];
  w10 = w15[12];
  /* #312: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #313: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #314: @49 = 00 */
  /* #315: @60 = (-@41) */
  w60 = (- w41 );
  /* #316: @48 = 00 */
  /* #317: @47 = 00 */
  /* #318: @56 = horzcat(@49, @60, @48, @47) */
  rr=(&w56);
  *rr++ = w60;
  /* #319: @56 = @56' */
  /* #320: @48 = 00 */
  /* #321: @47 = 00 */
  /* #322: @60 = horzcat(@41, @49, @48, @47) */
  rr=(&w60);
  *rr++ = w41;
  /* #323: @60 = @60' */
  /* #324: @48 = 00 */
  /* #325: @52 = (-@41) */
  w52 = (- w41 );
  /* #326: @11 = horzcat(@47, @48, @49, @52) */
  rr=(&w11);
  *rr++ = w52;
  /* #327: @11 = @11' */
  /* #328: @47 = 00 */
  /* #329: @52 = horzcat(@48, @47, @41, @49) */
  rr=(&w52);
  *rr++ = w41;
  /* #330: @52 = @52' */
  /* #331: @28 = horzcat(@56, @60, @11, @52) */
  rr=w28;
  *rr++ = w56;
  *rr++ = w60;
  *rr++ = w11;
  *rr++ = w52;
  /* #332: @24 = @28' */
  casadi_trans(w28,casadi_s12, w24, casadi_s12, iw);
  /* #333: @24 = nonzeros(@24) */
  /* #334: @24 = (@24*@27) */
  for (i=0, rr=w24, cs=w27; i<4; ++i) (*rr++) *= (*cs++);
  /* #335: @34 = @24[0, 3, 2] */
  for (cii=casadi_s13, rr=w34, ss=w24; cii!=casadi_s13+3; ++cii) *rr++ = ss[*cii];
  /* #336: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #337: @34 = @24[0, 3, 2] */
  for (cii=casadi_s13, rr=w34, ss=w24; cii!=casadi_s13+3; ++cii) *rr++ = ss[*cii];
  /* #338: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #339: @31 = mac(@23,@25,@31) */
  for (i=0, rr=w31; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #340: @38 = @31' */
  for (i=0, rr=w38, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #341: {@23, @24, @28, @29} = horzsplit(@38) */
  casadi_copy(w38, 4, w23);
  casadi_copy(w38+4, 4, w24);
  casadi_copy(w38+8, 4, w28);
  casadi_copy(w38+12, 4, w29);
  /* #342: @29 = @29' */
  /* #343: {@56, @60, @11, @52} = horzsplit(@29) */
  w56 = w29[0];
  w60 = w29[1];
  w11 = w29[2];
  w52 = w29[3];
  /* #344: @28 = @28' */
  /* #345: {@41, @59, @57, @0} = horzsplit(@28) */
  w41 = w28[0];
  w59 = w28[1];
  w57 = w28[2];
  w0 = w28[3];
  /* #346: @52 = (@52+@57) */
  w52 += w57;
  /* #347: @24 = @24' */
  /* #348: {@57, @2, @58, @53} = horzsplit(@24) */
  w57 = w24[0];
  w2 = w24[1];
  w58 = w24[2];
  w53 = w24[3];
  /* #349: @52 = (@52+@2) */
  w52 += w2;
  /* #350: @23 = @23' */
  /* #351: {@2, @54, @8, @55} = horzsplit(@23) */
  w2 = w23[0];
  w54 = w23[1];
  w8 = w23[2];
  w55 = w23[3];
  /* #352: @52 = (@52+@2) */
  w52 += w2;
  /* #353: @52 = (@52+@14) */
  w52 += w14;
  /* #354: @11 = (@11-@0) */
  w11 -= w0;
  /* #355: @11 = (@11+@57) */
  w11 += w57;
  /* #356: @11 = (@11-@54) */
  w11 -= w54;
  /* #357: @11 = (@11+@42) */
  w11 += w42;
  /* #358: @41 = (@41-@60) */
  w41 -= w60;
  /* #359: @41 = (@41+@53) */
  w41 += w53;
  /* #360: @41 = (@41-@8) */
  w41 -= w8;
  /* #361: @41 = (@41+@18) */
  w41 += w18;
  /* #362: @56 = (@56+@59) */
  w56 += w59;
  /* #363: @56 = (@56-@58) */
  w56 -= w58;
  /* #364: @56 = (@56-@55) */
  w56 -= w55;
  /* #365: @56 = (@56+@13) */
  w56 += w13;
  /* #366: @61 = vertcat(@39, @12, @5, @9, @6, @4, @17, @3, @20, @19, @52, @11, @41, @56, @40, @7, @10) */
  rr=w61;
  *rr++ = w39;
  *rr++ = w12;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w4;
  *rr++ = w17;
  *rr++ = w3;
  *rr++ = w20;
  *rr++ = w19;
  *rr++ = w52;
  *rr++ = w11;
  *rr++ = w41;
  *rr++ = w56;
  *rr++ = w40;
  *rr++ = w7;
  *rr++ = w10;
  /* #367: @62 = @61[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s14, rr=w62, ss=w61; cii!=casadi_s14+11; ++cii) *rr++ = ss[*cii];
  /* #368: (@43[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @62) */
  for (cii=casadi_s15, rr=w43, ss=w62; cii!=casadi_s15+11; ++cii, ++ss) rr[*cii] = *ss;
  /* #369: @62 = @61[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s14, rr=w62, ss=w61; cii!=casadi_s14+11; ++cii) *rr++ = ss[*cii];
  /* #370: (@43[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @62) */
  for (cii=casadi_s16, rr=w43, ss=w62; cii!=casadi_s16+11; ++cii, ++ss) rr[*cii] = *ss;
  /* #371: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #372: @48 = 00 */
  /* #373: @47 = 00 */
  /* #374: @34 = ones(17x1,3nz) */
  casadi_fill(w34, 3, 1.);
  /* #375: {NULL, NULL, @39, NULL, NULL, NULL, @12, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL} = vertsplit(@34) */
  w39 = w34[0];
  w12 = w34[1];
  w5 = w34[2];
  /* #376: @49 = 00 */
  /* #377: @9 = vertcat(@48, @47, @39, @49) */
  rr=(&w9);
  *rr++ = w39;
  /* #378: @39 = @9' */
  casadi_copy((&w9), 1, (&w39));
  /* #379: @23 = mac(@39,@26,@23) */
  casadi_mtimes((&w39), casadi_s17, w26, casadi_s1, w23, casadi_s0, w, 0);
  /* #380: @23 = @23' */
  /* #381: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #382: @9 = @9' */
  /* #383: @24 = mac(@9,@32,@24) */
  casadi_mtimes((&w9), casadi_s17, w32, casadi_s1, w24, casadi_s0, w, 0);
  /* #384: @24 = @24' */
  /* #385: @23 = (@23+@24) */
  for (i=0, rr=w23, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #386: {@9, @39, @6, @4} = vertsplit(@23) */
  w9 = w23[0];
  w39 = w23[1];
  w6 = w23[2];
  w4 = w23[3];
  /* #387: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #388: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #389: @12 = sparsity_cast(@12) */
  /* #390: @12 = (-@12) */
  w12 = (- w12 );
  /* #391: @17 = @12' */
  casadi_copy((&w12), 1, (&w17));
  /* #392: @34 = mac(@17,@22,@34) */
  casadi_mtimes((&w17), casadi_s18, w22, casadi_s4, w34, casadi_s3, w, 0);
  /* #393: @34 = @34' */
  /* #394: @21 = zeros(1x3) */
  casadi_clear(w21, 3);
  /* #395: @12 = @12' */
  /* #396: @21 = mac(@12,@37,@21) */
  casadi_mtimes((&w12), casadi_s18, w37, casadi_s4, w21, casadi_s3, w, 0);
  /* #397: @21 = @21' */
  /* #398: @34 = (@34+@21) */
  for (i=0, rr=w34, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #399: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #400: (@15[:3] += @34) */
  for (rr=w15+0, ss=w34; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #401: {@12, @17, @3, @20, @19, @52, @11, @41, @56, @40, @7, @10, @13} = vertsplit(@15) */
  w12 = w15[0];
  w17 = w15[1];
  w3 = w15[2];
  w20 = w15[3];
  w19 = w15[4];
  w52 = w15[5];
  w11 = w15[6];
  w41 = w15[7];
  w56 = w15[8];
  w40 = w15[9];
  w7 = w15[10];
  w10 = w15[11];
  w13 = w15[12];
  /* #402: @38 = zeros(4x4) */
  casadi_clear(w38, 16);
  /* #403: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #404: @48 = 00 */
  /* #405: @47 = 00 */
  /* #406: @55 = (-@5) */
  w55 = (- w5 );
  /* #407: @49 = 00 */
  /* #408: @58 = horzcat(@48, @47, @55, @49) */
  rr=(&w58);
  *rr++ = w55;
  /* #409: @58 = @58' */
  /* #410: @47 = 00 */
  /* #411: @49 = 00 */
  /* #412: @55 = horzcat(@47, @48, @49, @5) */
  rr=(&w55);
  *rr++ = w5;
  /* #413: @55 = @55' */
  /* #414: @49 = 00 */
  /* #415: @45 = 00 */
  /* #416: @59 = horzcat(@5, @49, @48, @45) */
  rr=(&w59);
  *rr++ = w5;
  /* #417: @59 = @59' */
  /* #418: @5 = (-@5) */
  w5 = (- w5 );
  /* #419: @18 = horzcat(@49, @5, @47, @48) */
  rr=(&w18);
  *rr++ = w5;
  /* #420: @18 = @18' */
  /* #421: @24 = horzcat(@58, @55, @59, @18) */
  rr=w24;
  *rr++ = w58;
  *rr++ = w55;
  *rr++ = w59;
  *rr++ = w18;
  /* #422: @28 = @24' */
  casadi_trans(w24,casadi_s19, w28, casadi_s19, iw);
  /* #423: @28 = nonzeros(@28) */
  /* #424: @28 = (@28*@27) */
  for (i=0, rr=w28, cs=w27; i<4; ++i) (*rr++) *= (*cs++);
  /* #425: @34 = @28[3, 0, 1] */
  for (cii=casadi_s20, rr=w34, ss=w28; cii!=casadi_s20+3; ++cii) *rr++ = ss[*cii];
  /* #426: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #427: @34 = @28[3, 0, 1] */
  for (cii=casadi_s20, rr=w34, ss=w28; cii!=casadi_s20+3; ++cii) *rr++ = ss[*cii];
  /* #428: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #429: @38 = mac(@23,@25,@38) */
  for (i=0, rr=w38; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #430: @31 = @38' */
  for (i=0, rr=w31, cs=w38; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #431: {@23, @28, @24, @29} = horzsplit(@31) */
  casadi_copy(w31, 4, w23);
  casadi_copy(w31+4, 4, w28);
  casadi_copy(w31+8, 4, w24);
  casadi_copy(w31+12, 4, w29);
  /* #432: @29 = @29' */
  /* #433: {@58, @55, @59, @18} = horzsplit(@29) */
  w58 = w29[0];
  w55 = w29[1];
  w59 = w29[2];
  w18 = w29[3];
  /* #434: @24 = @24' */
  /* #435: {@5, @8, @53, @60} = horzsplit(@24) */
  w5 = w24[0];
  w8 = w24[1];
  w53 = w24[2];
  w60 = w24[3];
  /* #436: @18 = (@18+@53) */
  w18 += w53;
  /* #437: @28 = @28' */
  /* #438: {@53, @42, @54, @57} = horzsplit(@28) */
  w53 = w28[0];
  w42 = w28[1];
  w54 = w28[2];
  w57 = w28[3];
  /* #439: @18 = (@18+@42) */
  w18 += w42;
  /* #440: @23 = @23' */
  /* #441: {@42, @0, @14, @2} = horzsplit(@23) */
  w42 = w23[0];
  w0 = w23[1];
  w14 = w23[2];
  w2 = w23[3];
  /* #442: @18 = (@18+@42) */
  w18 += w42;
  /* #443: @18 = (@18+@11) */
  w18 += w11;
  /* #444: @59 = (@59-@60) */
  w59 -= w60;
  /* #445: @59 = (@59+@53) */
  w59 += w53;
  /* #446: @59 = (@59-@0) */
  w59 -= w0;
  /* #447: @59 = (@59+@41) */
  w59 += w41;
  /* #448: @5 = (@5-@55) */
  w5 -= w55;
  /* #449: @5 = (@5+@57) */
  w5 += w57;
  /* #450: @5 = (@5-@14) */
  w5 -= w14;
  /* #451: @5 = (@5+@56) */
  w5 += w56;
  /* #452: @58 = (@58+@8) */
  w58 += w8;
  /* #453: @58 = (@58-@54) */
  w58 -= w54;
  /* #454: @58 = (@58-@2) */
  w58 -= w2;
  /* #455: @58 = (@58+@40) */
  w58 += w40;
  /* #456: @61 = vertcat(@9, @39, @6, @4, @12, @17, @3, @20, @19, @52, @18, @59, @5, @58, @7, @10, @13) */
  rr=w61;
  *rr++ = w9;
  *rr++ = w39;
  *rr++ = w6;
  *rr++ = w4;
  *rr++ = w12;
  *rr++ = w17;
  *rr++ = w3;
  *rr++ = w20;
  *rr++ = w19;
  *rr++ = w52;
  *rr++ = w18;
  *rr++ = w59;
  *rr++ = w5;
  *rr++ = w58;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w13;
  /* #457: @62 = @61[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s14, rr=w62, ss=w61; cii!=casadi_s14+11; ++cii) *rr++ = ss[*cii];
  /* #458: (@43[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @62) */
  for (cii=casadi_s21, rr=w43, ss=w62; cii!=casadi_s21+11; ++cii, ++ss) rr[*cii] = *ss;
  /* #459: @62 = @61[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s14, rr=w62, ss=w61; cii!=casadi_s14+11; ++cii) *rr++ = ss[*cii];
  /* #460: (@43[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @62) */
  for (cii=casadi_s22, rr=w43, ss=w62; cii!=casadi_s22+11; ++cii, ++ss) rr[*cii] = *ss;
  /* #461: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #462: @49 = 00 */
  /* #463: @47 = 00 */
  /* #464: @48 = 00 */
  /* #465: @35 = ones(17x1,2nz) */
  casadi_fill(w35, 2, 1.);
  /* #466: {NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @39, NULL, NULL, NULL} = vertsplit(@35) */
  w9 = w35[0];
  w39 = w35[1];
  /* #467: @6 = vertcat(@49, @47, @48, @9) */
  rr=(&w6);
  *rr++ = w9;
  /* #468: @9 = @6' */
  casadi_copy((&w6), 1, (&w9));
  /* #469: @23 = mac(@9,@26,@23) */
  casadi_mtimes((&w9), casadi_s23, w26, casadi_s1, w23, casadi_s0, w, 0);
  /* #470: @23 = @23' */
  /* #471: @28 = zeros(1x4) */
  casadi_clear(w28, 4);
  /* #472: @6 = @6' */
  /* #473: @28 = mac(@6,@32,@28) */
  casadi_mtimes((&w6), casadi_s23, w32, casadi_s1, w28, casadi_s0, w, 0);
  /* #474: @28 = @28' */
  /* #475: @23 = (@23+@28) */
  for (i=0, rr=w23, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #476: {@6, @9, @4, @12} = vertsplit(@23) */
  w6 = w23[0];
  w9 = w23[1];
  w4 = w23[2];
  w12 = w23[3];
  /* #477: @49 = 00 */
  /* #478: @47 = 00 */
  /* #479: @48 = 00 */
  /* #480: @45 = 00 */
  /* #481: @46 = 00 */
  /* #482: @51 = 00 */
  /* #483: @32 = zeros(4x4) */
  casadi_clear(w32, 16);
  /* #484: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #485: @63 = 00 */
  /* #486: @64 = 00 */
  /* #487: @65 = 00 */
  /* #488: @17 = (-@39) */
  w17 = (- w39 );
  /* #489: @3 = horzcat(@63, @64, @65, @17) */
  rr=(&w3);
  *rr++ = w17;
  /* #490: @3 = @3' */
  /* #491: @64 = 00 */
  /* #492: @17 = (-@39) */
  w17 = (- w39 );
  /* #493: @65 = 00 */
  /* #494: @20 = horzcat(@64, @63, @17, @65) */
  rr=(&w20);
  *rr++ = w17;
  /* #495: @20 = @20' */
  /* #496: @66 = 00 */
  /* #497: @17 = horzcat(@65, @39, @63, @66) */
  rr=(&w17);
  *rr++ = w39;
  /* #498: @17 = @17' */
  /* #499: @65 = 00 */
  /* #500: @19 = horzcat(@39, @65, @64, @63) */
  rr=(&w19);
  *rr++ = w39;
  /* #501: @19 = @19' */
  /* #502: @28 = horzcat(@3, @20, @17, @19) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w20;
  *rr++ = w17;
  *rr++ = w19;
  /* #503: @24 = @28' */
  casadi_trans(w28,casadi_s24, w24, casadi_s24, iw);
  /* #504: @24 = nonzeros(@24) */
  /* #505: @24 = (@24*@27) */
  for (i=0, rr=w24, cs=w27; i<4; ++i) (*rr++) *= (*cs++);
  /* #506: @34 = @24[2, 1, 0] */
  for (cii=casadi_s25, rr=w34, ss=w24; cii!=casadi_s25+3; ++cii) *rr++ = ss[*cii];
  /* #507: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #508: @34 = @24[2, 1, 0] */
  for (cii=casadi_s25, rr=w34, ss=w24; cii!=casadi_s25+3; ++cii) *rr++ = ss[*cii];
  /* #509: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #510: @32 = mac(@23,@25,@32) */
  for (i=0, rr=w32; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #511: @26 = @32' */
  for (i=0, rr=w26, cs=w32; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #512: {@23, @25, @24, @27} = horzsplit(@26) */
  casadi_copy(w26, 4, w23);
  casadi_copy(w26+4, 4, w25);
  casadi_copy(w26+8, 4, w24);
  casadi_copy(w26+12, 4, w27);
  /* #513: @27 = @27' */
  /* #514: {@3, @20, @17, @19} = horzsplit(@27) */
  w3 = w27[0];
  w20 = w27[1];
  w17 = w27[2];
  w19 = w27[3];
  /* #515: @24 = @24' */
  /* #516: {@39, @52, @18, @59} = horzsplit(@24) */
  w39 = w24[0];
  w52 = w24[1];
  w18 = w24[2];
  w59 = w24[3];
  /* #517: @19 = (@19+@18) */
  w19 += w18;
  /* #518: @25 = @25' */
  /* #519: {@18, @5, @58, @7} = horzsplit(@25) */
  w18 = w25[0];
  w5 = w25[1];
  w58 = w25[2];
  w7 = w25[3];
  /* #520: @19 = (@19+@5) */
  w19 += w5;
  /* #521: @23 = @23' */
  /* #522: {@5, @10, @13, @40} = horzsplit(@23) */
  w5 = w23[0];
  w10 = w23[1];
  w13 = w23[2];
  w40 = w23[3];
  /* #523: @19 = (@19+@5) */
  w19 += w5;
  /* #524: @17 = (@17-@59) */
  w17 -= w59;
  /* #525: @17 = (@17+@18) */
  w17 += w18;
  /* #526: @17 = (@17-@10) */
  w17 -= w10;
  /* #527: @39 = (@39-@20) */
  w39 -= w20;
  /* #528: @39 = (@39+@7) */
  w39 += w7;
  /* #529: @39 = (@39-@13) */
  w39 -= w13;
  /* #530: @3 = (@3+@52) */
  w3 += w52;
  /* #531: @3 = (@3-@58) */
  w3 -= w58;
  /* #532: @3 = (@3-@40) */
  w3 -= w40;
  /* #533: @65 = 00 */
  /* #534: @64 = 00 */
  /* #535: @63 = 00 */
  /* #536: @50 = vertcat(@6, @9, @4, @12, @49, @47, @48, @45, @46, @51, @19, @17, @39, @3, @65, @64, @63) */
  rr=w50;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w4;
  *rr++ = w12;
  *rr++ = w19;
  *rr++ = w17;
  *rr++ = w39;
  *rr++ = w3;
  /* #537: @67 = @50[:8] */
  for (rr=w67, ss=w50+0; ss!=w50+8; ss+=1) *rr++ = *ss;
  /* #538: (@43[:50:25;12:16] = @67) */
  for (rr=w43+0, ss=w67; rr!=w43+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *ss++;
  /* #539: @67 = @50[:8] */
  for (rr=w67, ss=w50+0; ss!=w50+8; ss+=1) *rr++ = *ss;
  /* #540: (@43[:50:25;3:19:4] = @67) */
  for (rr=w43+0, ss=w67; rr!=w43+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *ss++;
  /* #541: @68 = @43' */
  casadi_trans(w43,casadi_s26, w68, casadi_s26, iw);
  /* #542: output[2][0] = @68 */
  casadi_copy(w68, 43, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s27;
    case 1: return casadi_s28;
    case 2: return casadi_s29;
    case 3: return casadi_s27;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s30;
    case 1: return casadi_s31;
    case 2: return casadi_s26;
    case 3: return casadi_s29;
    case 4: return casadi_s32;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 316;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
