/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

/* quadrotor_cost_ext_cost_fun_jac:(i0[13],i1[4],i2[],i3[13])->(o0,o1[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+5, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+21, *w16=w+34, w17, w18, w19, w20, *w21=w+41, *w22=w+44, *w23=w+53, *w24=w+57, *w25=w+61, *w26=w+65, *w27=w+81, *w28=w+85, *w29=w+89, *w30=w+93, *w31=w+97, *w32=w+113, *w33=w+129, *w34=w+132, *w35=w+135, *w36=w+137, *w37=w+139, w38, w39, w40;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #16: @16 = @15[:3] */
  for (rr=w16, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #17: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #18: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #19: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #20: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #21: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #22: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #23: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #24: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #25: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #26: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #27: @18 = input[0][10] */
  w18 = arg[0] ? arg[0][10] : 0;
  /* #28: @19 = input[0][11] */
  w19 = arg[0] ? arg[0][11] : 0;
  /* #29: @20 = input[0][12] */
  w20 = arg[0] ? arg[0][12] : 0;
  /* #30: @15 = vertcat(@2, @3, @4, @5, @6, @7, @12, @13, @14, @17, @18, @19, @20) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #31: @21 = @15[:3] */
  for (rr=w21, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #32: @16 = (@16-@21) */
  for (i=0, rr=w16, cs=w21; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @21 = @16' */
  casadi_copy(w16, 3, w21);
  /* #34: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #35: @2 = 15.5 */
  w2 = 1.5500000000000000e+01;
  /* #36: (@22[0] = @2) */
  for (rr=w22+0, ss=(&w2); rr!=w22+1; rr+=1) *rr = *ss++;
  /* #37: @2 = 15.5 */
  w2 = 1.5500000000000000e+01;
  /* #38: (@22[4] = @2) */
  for (rr=w22+4, ss=(&w2); rr!=w22+5; rr+=1) *rr = *ss++;
  /* #39: @2 = 15.5 */
  w2 = 1.5500000000000000e+01;
  /* #40: (@22[8] = @2) */
  for (rr=w22+8, ss=(&w2); rr!=w22+9; rr+=1) *rr = *ss++;
  /* #41: @1 = mac(@21,@22,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #42: @0 = mac(@1,@16,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #43: @2 = 0 */
  w2 = 0.;
  /* #44: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #45: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #46: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #47: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #48: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #49: @24 = vertcat(@3, @4, @5, @6) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #50: @25 = @24' */
  casadi_copy(w24, 4, w25);
  /* #51: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #52: @3 = 0.033557 */
  w3 = 3.3557046979865772e-02;
  /* #53: (@26[0] = @3) */
  for (rr=w26+0, ss=(&w3); rr!=w26+1; rr+=1) *rr = *ss++;
  /* #54: @3 = 200 */
  w3 = 200.;
  /* #55: (@26[5] = @3) */
  for (rr=w26+5, ss=(&w3); rr!=w26+6; rr+=1) *rr = *ss++;
  /* #56: @3 = 200 */
  w3 = 200.;
  /* #57: (@26[10] = @3) */
  for (rr=w26+10, ss=(&w3); rr!=w26+11; rr+=1) *rr = *ss++;
  /* #58: @3 = 200 */
  w3 = 200.;
  /* #59: (@26[15] = @3) */
  for (rr=w26+15, ss=(&w3); rr!=w26+16; rr+=1) *rr = *ss++;
  /* #60: @23 = mac(@25,@26,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #61: @2 = mac(@23,@24,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #62: @0 = (@0+@2) */
  w0 += w2;
  /* #63: @2 = 1 */
  w2 = 1.;
  /* #64: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #65: @3 = (-@13) */
  w3 = (- w13 );
  /* #66: @4 = (-@14) */
  w4 = (- w14 );
  /* #67: @5 = (-@17) */
  w5 = (- w17 );
  /* #68: @27 = horzcat(@12, @3, @4, @5) */
  rr=w27;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #69: @27 = @27' */
  /* #70: @3 = (-@17) */
  w3 = (- w17 );
  /* #71: @28 = horzcat(@13, @12, @3, @14) */
  rr=w28;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w14;
  /* #72: @28 = @28' */
  /* #73: @3 = (-@13) */
  w3 = (- w13 );
  /* #74: @29 = horzcat(@14, @17, @12, @3) */
  rr=w29;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w12;
  *rr++ = w3;
  /* #75: @29 = @29' */
  /* #76: @14 = (-@14) */
  w14 = (- w14 );
  /* #77: @30 = horzcat(@17, @14, @13, @12) */
  rr=w30;
  *rr++ = w17;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w12;
  /* #78: @30 = @30' */
  /* #79: @31 = horzcat(@27, @28, @29, @30) */
  rr=w31;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #80: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #81: @9 = (-@9) */
  w9 = (- w9 );
  /* #82: @10 = (-@10) */
  w10 = (- w10 );
  /* #83: @11 = (-@11) */
  w11 = (- w11 );
  /* #84: @27 = vertcat(@8, @9, @10, @11) */
  rr=w27;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #85: @25 = mac(@32,@27,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w32+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #86: @8 = @25[0] */
  for (rr=(&w8), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #87: @2 = (@2-@8) */
  w2 -= w8;
  /* #88: @8 = 0 */
  w8 = 0.;
  /* #89: @21 = @25[1:4] */
  for (rr=w21, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #90: @33 = @21' */
  casadi_copy(w21, 3, w33);
  /* #91: @34 = @25[1:4] */
  for (rr=w34, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #92: @8 = mac(@33,@34,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #93: @2 = (@2+@8) */
  w2 += w8;
  /* #94: @0 = (@0+@2) */
  w0 += w2;
  /* #95: @2 = 0.2 */
  w2 = 2.0000000000000001e-01;
  /* #96: @8 = 0 */
  w8 = 0.;
  /* #97: @35 = @15[10:12] */
  for (rr=w35, ss=w15+10; ss!=w15+12; ss+=1) *rr++ = *ss;
  /* #98: @36 = @35' */
  casadi_copy(w35, 2, w36);
  /* #99: @8 = mac(@36,@35,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w36+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #100: @2 = (@2*@8) */
  w2 *= w8;
  /* #101: @0 = (@0+@2) */
  w0 += w2;
  /* #102: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #103: @23 = @23' */
  /* #104: @25 = zeros(1x4) */
  casadi_clear(w25, 4);
  /* #105: @24 = @24' */
  /* #106: @32 = @26' */
  for (i=0, rr=w32, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #107: @25 = mac(@24,@32,@25) */
  for (i=0, rr=w25; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w32+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #108: @25 = @25' */
  /* #109: @23 = (@23+@25) */
  for (i=0, rr=w23, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #110: {@0, @2, @8, @9} = vertsplit(@23) */
  w0 = w23[0];
  w2 = w23[1];
  w8 = w23[2];
  w9 = w23[3];
  /* #111: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #112: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #113: output[1][2] = @8 */
  if (res[1]) res[1][2] = w8;
  /* #114: output[1][3] = @9 */
  if (res[1]) res[1][3] = w9;
  /* #115: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #116: @9 = 0.2 */
  w9 = 2.0000000000000001e-01;
  /* #117: @36 = (@9*@35) */
  for (i=0, rr=w36, cs=w35; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #118: @35 = @35' */
  /* #119: @35 = (@9*@35) */
  for (i=0, rr=w35, cs=w35; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #120: @35 = @35' */
  /* #121: @36 = (@36+@35) */
  for (i=0, rr=w36, cs=w35; i<2; ++i) (*rr++) += (*cs++);
  /* #122: (@15[10:12] += @36) */
  for (rr=w15+10, ss=w36; rr!=w15+12; rr+=1) *rr += *ss++;
  /* #123: @1 = @1' */
  /* #124: @33 = zeros(1x3) */
  casadi_clear(w33, 3);
  /* #125: @16 = @16' */
  /* #126: @37 = @22' */
  for (i=0, rr=w37, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #127: @33 = mac(@16,@37,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #128: @33 = @33' */
  /* #129: @1 = (@1+@33) */
  for (i=0, rr=w1, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #130: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #131: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #132: {@9, @8, @2, @0, @10, @11, @17, @14, @13, @12, @3, @4, @5} = vertsplit(@15) */
  w9 = w15[0];
  w8 = w15[1];
  w2 = w15[2];
  w0 = w15[3];
  w10 = w15[4];
  w11 = w15[5];
  w17 = w15[6];
  w14 = w15[7];
  w13 = w15[8];
  w12 = w15[9];
  w3 = w15[10];
  w4 = w15[11];
  w5 = w15[12];
  /* #133: output[1][4] = @9 */
  if (res[1]) res[1][4] = w9;
  /* #134: output[1][5] = @8 */
  if (res[1]) res[1][5] = w8;
  /* #135: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #136: output[1][7] = @0 */
  if (res[1]) res[1][7] = w0;
  /* #137: output[1][8] = @10 */
  if (res[1]) res[1][8] = w10;
  /* #138: output[1][9] = @11 */
  if (res[1]) res[1][9] = w11;
  /* #139: @32 = zeros(4x4) */
  casadi_clear(w32, 16);
  /* #140: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #141: (@23[1:4] += @21) */
  for (rr=w23+1, ss=w21; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #142: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #143: @11 = -1 */
  w11 = -1.;
  /* #144: (@23[0] += @11) */
  for (rr=w23+0, ss=(&w11); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #145: @27 = @27' */
  /* #146: @32 = mac(@23,@27,@32) */
  for (i=0, rr=w32; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w27+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #147: @26 = @32' */
  for (i=0, rr=w26, cs=w32; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #148: {@23, @27, @25, @24} = horzsplit(@26) */
  casadi_copy(w26, 4, w23);
  casadi_copy(w26+4, 4, w27);
  casadi_copy(w26+8, 4, w25);
  casadi_copy(w26+12, 4, w24);
  /* #149: @24 = @24' */
  /* #150: {@11, @10, @0, @2} = horzsplit(@24) */
  w11 = w24[0];
  w10 = w24[1];
  w0 = w24[2];
  w2 = w24[3];
  /* #151: @25 = @25' */
  /* #152: {@8, @9, @6, @7} = horzsplit(@25) */
  w8 = w25[0];
  w9 = w25[1];
  w6 = w25[2];
  w7 = w25[3];
  /* #153: @2 = (@2+@6) */
  w2 += w6;
  /* #154: @27 = @27' */
  /* #155: {@6, @18, @19, @20} = horzsplit(@27) */
  w6 = w27[0];
  w18 = w27[1];
  w19 = w27[2];
  w20 = w27[3];
  /* #156: @2 = (@2+@18) */
  w2 += w18;
  /* #157: @23 = @23' */
  /* #158: {@18, @38, @39, @40} = horzsplit(@23) */
  w18 = w23[0];
  w38 = w23[1];
  w39 = w23[2];
  w40 = w23[3];
  /* #159: @2 = (@2+@18) */
  w2 += w18;
  /* #160: @2 = (@2+@17) */
  w2 += w17;
  /* #161: output[1][10] = @2 */
  if (res[1]) res[1][10] = w2;
  /* #162: @0 = (@0-@7) */
  w0 -= w7;
  /* #163: @0 = (@0+@6) */
  w0 += w6;
  /* #164: @0 = (@0-@38) */
  w0 -= w38;
  /* #165: @0 = (@0+@14) */
  w0 += w14;
  /* #166: output[1][11] = @0 */
  if (res[1]) res[1][11] = w0;
  /* #167: @8 = (@8-@10) */
  w8 -= w10;
  /* #168: @8 = (@8+@20) */
  w8 += w20;
  /* #169: @8 = (@8-@39) */
  w8 -= w39;
  /* #170: @8 = (@8+@13) */
  w8 += w13;
  /* #171: output[1][12] = @8 */
  if (res[1]) res[1][12] = w8;
  /* #172: @11 = (@11+@9) */
  w11 += w9;
  /* #173: @11 = (@11-@19) */
  w11 -= w19;
  /* #174: @11 = (@11-@40) */
  w11 -= w40;
  /* #175: @11 = (@11+@12) */
  w11 += w12;
  /* #176: output[1][13] = @11 */
  if (res[1]) res[1][13] = w11;
  /* #177: output[1][14] = @3 */
  if (res[1]) res[1][14] = w3;
  /* #178: output[1][15] = @4 */
  if (res[1]) res[1][15] = w4;
  /* #179: output[1][16] = @5 */
  if (res[1]) res[1][16] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 151;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
