/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
static const casadi_int casadi_s3[12] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
static const casadi_int casadi_s4[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* quadrotor_expl_vde_adj:(i0[13],i1[13],i2[4],i3[13])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+4, *w1=w+17, *w2=w+20, w3, *w4=w+30, *w5=w+39, *w6=w+42, *w7=w+45, *w8=w+54, *w9=w+63, *w10=w+76, *w11=w+79, *w12=w+82, *w13=w+86, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, *w26=w+101, *w27=w+105, w28, *w29=w+110, *w30=w+114, *w31=w+118, *w32=w+122, *w33=w+126, w34, w35, *w36=w+144, *w37=w+153, w38, w39, w40, w41, w42, *w43=w+167;
  /* #0: @0 = zeros(13x1) */
  casadi_clear(w0, 13);
  /* #1: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #3: @3 = 0.00264 */
  w3 = 2.6400000000000000e-03;
  /* #4: (@2[0] = @3) */
  for (rr=w2+0, ss=(&w3); rr!=w2+1; rr+=1) *rr = *ss++;
  /* #5: @3 = 0.00264 */
  w3 = 2.6400000000000000e-03;
  /* #6: (@2[4] = @3) */
  for (rr=w2+4, ss=(&w3); rr!=w2+5; rr+=1) *rr = *ss++;
  /* #7: @3 = 0.00496 */
  w3 = 4.9600000000000000e-03;
  /* #8: (@2[8] = @3) */
  for (rr=w2+8, ss=(&w3); rr!=w2+9; rr+=1) *rr = *ss++;
  /* #9: @4 = @2' */
  for (i=0, rr=w4, cs=w2; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #10: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #11: @3 = input[0][12] */
  w3 = arg[0] ? arg[0][12] : 0;
  /* #12: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #13: @7 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w7);
  /* #14: @7 = (@2\@7) */
  rr = w7;
  ss = w2;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #15: @8 = @7' */
  for (i=0, rr=w8, cs=w7; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #16: @9 = input[1][0] */
  casadi_copy(arg[1], 13, w9);
  /* #17: {@10, @11, @12, @13} = vertsplit(@9) */
  casadi_copy(w9, 3, w10);
  casadi_copy(w9+3, 3, w11);
  casadi_copy(w9+6, 4, w12);
  casadi_copy(w9+10, 3, w13);
  /* #18: @6 = mac(@8,@13,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #19: @13 = (-@6) */
  for (i=0, rr=w13, cs=w6; i<3; ++i) *rr++ = (- *cs++ );
  /* #20: {@14, @15, @16} = vertsplit(@13) */
  w14 = w13[0];
  w15 = w13[1];
  w16 = w13[2];
  /* #21: @17 = (@3*@15) */
  w17  = (w3*w15);
  /* #22: @18 = input[0][11] */
  w18 = arg[0] ? arg[0][11] : 0;
  /* #23: @19 = (@18*@16) */
  w19  = (w18*w16);
  /* #24: @17 = (@17-@19) */
  w17 -= w19;
  /* #25: (@5[0] += @17) */
  for (rr=w5+0, ss=(&w17); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #26: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #27: @19 = (@17*@16) */
  w19  = (w17*w16);
  /* #28: @20 = (@3*@14) */
  w20  = (w3*w14);
  /* #29: @19 = (@19-@20) */
  w19 -= w20;
  /* #30: (@5[1] += @19) */
  for (rr=w5+1, ss=(&w19); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #31: @19 = (@18*@14) */
  w19  = (w18*w14);
  /* #32: @20 = (@17*@15) */
  w20  = (w17*w15);
  /* #33: @19 = (@19-@20) */
  w19 -= w20;
  /* #34: (@5[2] += @19) */
  for (rr=w5+2, ss=(&w19); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #35: @1 = mac(@4,@5,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #36: (@0[10:13] += @1) */
  for (rr=w0+10, ss=w1; rr!=w0+13; rr+=1) *rr += *ss++;
  /* #37: @19 = 1 */
  w19 = 1.;
  /* #38: @20 = input[0][6] */
  w20 = arg[0] ? arg[0][6] : 0;
  /* #39: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #40: @22 = input[0][7] */
  w22 = arg[0] ? arg[0][7] : 0;
  /* #41: @23 = sq(@22) */
  w23 = casadi_sq( w22 );
  /* #42: @21 = (@21+@23) */
  w21 += w23;
  /* #43: @23 = input[0][8] */
  w23 = arg[0] ? arg[0][8] : 0;
  /* #44: @24 = sq(@23) */
  w24 = casadi_sq( w23 );
  /* #45: @21 = (@21+@24) */
  w21 += w24;
  /* #46: @24 = input[0][9] */
  w24 = arg[0] ? arg[0][9] : 0;
  /* #47: @25 = sq(@24) */
  w25 = casadi_sq( w24 );
  /* #48: @21 = (@21+@25) */
  w21 += w25;
  /* #49: @19 = (@19-@21) */
  w19 -= w21;
  /* #50: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #51: @26 = (@19*@12) */
  for (i=0, rr=w26, cs=w12; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #52: @27 = zeros(4x1) */
  casadi_clear(w27, 4);
  /* #53: @19 = 0 */
  w19 = 0.;
  /* #54: @21 = (-@17) */
  w21 = (- w17 );
  /* #55: @25 = (-@18) */
  w25 = (- w18 );
  /* #56: @28 = (-@3) */
  w28 = (- w3 );
  /* #57: @29 = horzcat(@19, @21, @25, @28) */
  rr=w29;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w25;
  *rr++ = w28;
  /* #58: @29 = @29' */
  /* #59: @19 = 0 */
  w19 = 0.;
  /* #60: @21 = (-@18) */
  w21 = (- w18 );
  /* #61: @30 = horzcat(@17, @19, @3, @21) */
  rr=w30;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w3;
  *rr++ = w21;
  /* #62: @30 = @30' */
  /* #63: @19 = (-@3) */
  w19 = (- w3 );
  /* #64: @21 = 0 */
  w21 = 0.;
  /* #65: @31 = horzcat(@18, @19, @21, @17) */
  rr=w31;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w17;
  /* #66: @31 = @31' */
  /* #67: @19 = (-@17) */
  w19 = (- w17 );
  /* #68: @21 = 0 */
  w21 = 0.;
  /* #69: @32 = horzcat(@3, @18, @19, @21) */
  rr=w32;
  *rr++ = w3;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w21;
  /* #70: @32 = @32' */
  /* #71: @33 = horzcat(@29, @30, @31, @32) */
  rr=w33;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  /* #72: @19 = 0.5 */
  w19 = 5.0000000000000000e-01;
  /* #73: @29 = (@19*@12) */
  for (i=0, rr=w29, cs=w12; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #74: @27 = mac(@33,@29,@27) */
  for (i=0, rr=w27; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w33+j, tt=w29+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #75: @26 = (@26+@27) */
  for (i=0, rr=w26, cs=w27; i<4; ++i) (*rr++) += (*cs++);
  /* #76: @27 = zeros(4x1) */
  casadi_clear(w27, 4);
  /* #77: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #78: @19 = input[0][0] */
  w19 = arg[0] ? arg[0][0] : 0;
  /* #79: @21 = input[0][1] */
  w21 = arg[0] ? arg[0][1] : 0;
  /* #80: @25 = input[0][2] */
  w25 = arg[0] ? arg[0][2] : 0;
  /* #81: @28 = input[0][3] */
  w28 = arg[0] ? arg[0][3] : 0;
  /* #82: @34 = input[0][4] */
  w34 = arg[0] ? arg[0][4] : 0;
  /* #83: @35 = input[0][5] */
  w35 = arg[0] ? arg[0][5] : 0;
  /* #84: @9 = vertcat(@19, @21, @25, @28, @34, @35, @20, @22, @23, @24, @17, @18, @3) */
  rr=w9;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w25;
  *rr++ = w28;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w3;
  /* #85: @30 = @9[6:10] */
  for (rr=w30, ss=w9+6; ss!=w9+10; ss+=1) *rr++ = *ss;
  /* #86: @19 = ||@30||_F */
  w19 = sqrt(casadi_dot(4, w30, w30));
  /* #87: @31 = (@30/@19) */
  for (i=0, rr=w31, cr=w30; i<4; ++i) (*rr++)  = ((*cr++)/w19);
  /* #88: @21 = @31[3] */
  for (rr=(&w21), ss=w31+3; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #89: @21 = (-@21) */
  w21 = (- w21 );
  /* #90: (@4[3] = @21) */
  for (rr=w4+3, ss=(&w21); rr!=w4+4; rr+=1) *rr = *ss++;
  /* #91: @21 = @31[2] */
  for (rr=(&w21), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #92: (@4[6] = @21) */
  for (rr=w4+6, ss=(&w21); rr!=w4+7; rr+=1) *rr = *ss++;
  /* #93: @21 = @31[1] */
  for (rr=(&w21), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #94: @21 = (-@21) */
  w21 = (- w21 );
  /* #95: (@4[7] = @21) */
  for (rr=w4+7, ss=(&w21); rr!=w4+8; rr+=1) *rr = *ss++;
  /* #96: @21 = @31[3] */
  for (rr=(&w21), ss=w31+3; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #97: (@4[1] = @21) */
  for (rr=w4+1, ss=(&w21); rr!=w4+2; rr+=1) *rr = *ss++;
  /* #98: @21 = @31[2] */
  for (rr=(&w21), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #99: @21 = (-@21) */
  w21 = (- w21 );
  /* #100: (@4[2] = @21) */
  for (rr=w4+2, ss=(&w21); rr!=w4+3; rr+=1) *rr = *ss++;
  /* #101: @21 = @31[1] */
  for (rr=(&w21), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #102: (@4[5] = @21) */
  for (rr=w4+5, ss=(&w21); rr!=w4+6; rr+=1) *rr = *ss++;
  /* #103: @8 = zeros(3x3) */
  casadi_clear(w8, 9);
  /* #104: @21 = input[2][0] */
  w21 = arg[2] ? arg[2][0] : 0;
  /* #105: @1 = (@21*@11) */
  for (i=0, rr=w1, cs=w11; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #106: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #107: @21 = 1 */
  w21 = 1.;
  /* #108: (@5[2] = @21) */
  for (rr=w5+2, ss=(&w21); rr!=w5+3; rr+=1) *rr = *ss++;
  /* #109: @13 = @5' */
  casadi_copy(w5, 3, w13);
  /* #110: @8 = mac(@1,@13,@8) */
  for (i=0, rr=w8; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w13+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #111: @21 = dot(@4, @8) */
  w21 = casadi_dot(9, w4, w8);
  /* #112: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #113: (@27[0] += @21) */
  for (rr=w27+0, ss=(&w21); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #114: @21 = @31[0] */
  for (rr=(&w21), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #115: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #116: @7 = (@21*@8) */
  for (i=0, rr=w7, cs=w8; i<9; ++i) (*rr++)  = (w21*(*cs++));
  /* #117: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #118: @8 = (2.*@8) */
  for (i=0, rr=w8, cs=w8; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #119: @37 = @4' */
  for (i=0, rr=w37, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #120: @36 = mac(@8,@37,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #121: @7 = (@7+@36) */
  for (i=0, rr=w7, cs=w36; i<9; ++i) (*rr++) += (*cs++);
  /* #122: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #123: @37 = @4' */
  for (i=0, rr=w37, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #124: @36 = mac(@37,@8,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w37+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #125: @7 = (@7+@36) */
  for (i=0, rr=w7, cs=w36; i<9; ++i) (*rr++) += (*cs++);
  /* #126: @25 = @7[5] */
  for (rr=(&w25), ss=w7+5; ss!=w7+6; ss+=1) *rr++ = *ss;
  /* #127: (@27[1] += @25) */
  for (rr=w27+1, ss=(&w25); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #128: @25 = 0 */
  w25 = 0.;
  /* #129: (@7[5] = @25) */
  for (rr=w7+5, ss=(&w25); rr!=w7+6; rr+=1) *rr = *ss++;
  /* #130: @25 = @7[2] */
  for (rr=(&w25), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #131: @25 = (-@25) */
  w25 = (- w25 );
  /* #132: (@27[2] += @25) */
  for (rr=w27+2, ss=(&w25); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #133: @25 = 0 */
  w25 = 0.;
  /* #134: (@7[2] = @25) */
  for (rr=w7+2, ss=(&w25); rr!=w7+3; rr+=1) *rr = *ss++;
  /* #135: @25 = @7[1] */
  for (rr=(&w25), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #136: (@27[3] += @25) */
  for (rr=w27+3, ss=(&w25); rr!=w27+4; rr+=1) *rr += *ss++;
  /* #137: @25 = 0 */
  w25 = 0.;
  /* #138: (@7[1] = @25) */
  for (rr=w7+1, ss=(&w25); rr!=w7+2; rr+=1) *rr = *ss++;
  /* #139: @25 = @7[7] */
  for (rr=(&w25), ss=w7+7; ss!=w7+8; ss+=1) *rr++ = *ss;
  /* #140: @25 = (-@25) */
  w25 = (- w25 );
  /* #141: (@27[1] += @25) */
  for (rr=w27+1, ss=(&w25); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #142: @25 = 0 */
  w25 = 0.;
  /* #143: (@7[7] = @25) */
  for (rr=w7+7, ss=(&w25); rr!=w7+8; rr+=1) *rr = *ss++;
  /* #144: @25 = @7[6] */
  for (rr=(&w25), ss=w7+6; ss!=w7+7; ss+=1) *rr++ = *ss;
  /* #145: (@27[2] += @25) */
  for (rr=w27+2, ss=(&w25); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #146: @25 = 0 */
  w25 = 0.;
  /* #147: (@7[6] = @25) */
  for (rr=w7+6, ss=(&w25); rr!=w7+7; rr+=1) *rr = *ss++;
  /* #148: @25 = @7[3] */
  for (rr=(&w25), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #149: @25 = (-@25) */
  w25 = (- w25 );
  /* #150: (@27[3] += @25) */
  for (rr=w27+3, ss=(&w25); rr!=w27+4; rr+=1) *rr += *ss++;
  /* #151: @32 = (@27/@19) */
  for (i=0, rr=w32, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)/w19);
  /* #152: @26 = (@26+@32) */
  for (i=0, rr=w26, cs=w32; i<4; ++i) (*rr++) += (*cs++);
  /* #153: @31 = (@31/@19) */
  for (i=0, rr=w31; i<4; ++i) (*rr++) /= w19;
  /* #154: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) *rr++ = (- *cs++ );
  /* #155: @25 = dot(@31, @27) */
  w25 = casadi_dot(4, w31, w27);
  /* #156: @25 = (@25/@19) */
  w25 /= w19;
  /* #157: @31 = (@25*@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) (*rr++)  = (w25*(*cs++));
  /* #158: @26 = (@26+@31) */
  for (i=0, rr=w26, cs=w31; i<4; ++i) (*rr++) += (*cs++);
  /* #159: (@0[6:10] += @26) */
  for (rr=w0+6, ss=w26; rr!=w0+10; rr+=1) *rr += *ss++;
  /* #160: (@0[3:6] += @10) */
  for (rr=w0+3, ss=w10; rr!=w0+6; rr+=1) *rr += *ss++;
  /* #161: {@25, @19, @28, @34, @35, @17, @18, @3, @38, @39, @40, @41, @42} = vertsplit(@0) */
  w25 = w0[0];
  w19 = w0[1];
  w28 = w0[2];
  w34 = w0[3];
  w35 = w0[4];
  w17 = w0[5];
  w18 = w0[6];
  w3 = w0[7];
  w38 = w0[8];
  w39 = w0[9];
  w40 = w0[10];
  w41 = w0[11];
  w42 = w0[12];
  /* #162: output[0][0] = @25 */
  if (res[0]) res[0][0] = w25;
  /* #163: output[0][1] = @19 */
  if (res[0]) res[0][1] = w19;
  /* #164: output[0][2] = @28 */
  if (res[0]) res[0][2] = w28;
  /* #165: output[0][3] = @34 */
  if (res[0]) res[0][3] = w34;
  /* #166: output[0][4] = @35 */
  if (res[0]) res[0][4] = w35;
  /* #167: output[0][5] = @17 */
  if (res[0]) res[0][5] = w17;
  /* #168: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #169: @17 = dot(@30, @12) */
  w17 = casadi_dot(4, w30, w12);
  /* #170: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #171: @20 = (@20*@17) */
  w20 *= w17;
  /* #172: @18 = (@18-@20) */
  w18 -= w20;
  /* #173: output[0][6] = @18 */
  if (res[0]) res[0][6] = w18;
  /* #174: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #175: @22 = (@22*@17) */
  w22 *= w17;
  /* #176: @3 = (@3-@22) */
  w3 -= w22;
  /* #177: output[0][7] = @3 */
  if (res[0]) res[0][7] = w3;
  /* #178: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #179: @23 = (@23*@17) */
  w23 *= w17;
  /* #180: @38 = (@38-@23) */
  w38 -= w23;
  /* #181: output[0][8] = @38 */
  if (res[0]) res[0][8] = w38;
  /* #182: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #183: @24 = (@24*@17) */
  w24 *= w17;
  /* #184: @39 = (@39-@24) */
  w39 -= w24;
  /* #185: output[0][9] = @39 */
  if (res[0]) res[0][9] = w39;
  /* #186: @10 = zeros(3x1) */
  casadi_clear(w10, 3);
  /* #187: @1 = @9[10:13] */
  for (rr=w1, ss=w9+10; ss!=w9+13; ss+=1) *rr++ = *ss;
  /* #188: @10 = mac(@2,@1,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #189: @39 = @10[1] */
  for (rr=(&w39), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #190: @24 = (@39*@16) */
  w24  = (w39*w16);
  /* #191: @17 = @10[2] */
  for (rr=(&w17), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #192: @38 = (@17*@15) */
  w38  = (w17*w15);
  /* #193: @24 = (@24-@38) */
  w24 -= w38;
  /* #194: @33 = zeros(4x4) */
  casadi_clear(w33, 16);
  /* #195: @30 = @30' */
  /* #196: @33 = mac(@29,@30,@33) */
  for (i=0, rr=w33; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w29+j, tt=w30+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #197: @43 = @33' */
  for (i=0, rr=w43, cs=w33; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #198: {@29, @30, @12, @26} = horzsplit(@43) */
  casadi_copy(w43, 4, w29);
  casadi_copy(w43+4, 4, w30);
  casadi_copy(w43+8, 4, w12);
  casadi_copy(w43+12, 4, w26);
  /* #199: @26 = @26' */
  /* #200: {@38, @23, @3, NULL} = horzsplit(@26) */
  w38 = w26[0];
  w23 = w26[1];
  w3 = w26[2];
  /* #201: @24 = (@24-@3) */
  w24 -= w3;
  /* #202: @12 = @12' */
  /* #203: {@3, @22, NULL, @18} = horzsplit(@12) */
  w3 = w12[0];
  w22 = w12[1];
  w18 = w12[3];
  /* #204: @24 = (@24+@18) */
  w24 += w18;
  /* #205: @30 = @30' */
  /* #206: {@18, NULL, @20, @35} = horzsplit(@30) */
  w18 = w30[0];
  w20 = w30[2];
  w35 = w30[3];
  /* #207: @24 = (@24+@18) */
  w24 += w18;
  /* #208: @29 = @29' */
  /* #209: {NULL, @18, @34, @28} = horzsplit(@29) */
  w18 = w29[1];
  w34 = w29[2];
  w28 = w29[3];
  /* #210: @24 = (@24-@18) */
  w24 -= w18;
  /* #211: @24 = (@24+@40) */
  w24 += w40;
  /* #212: output[0][10] = @24 */
  if (res[0]) res[0][10] = w24;
  /* #213: @17 = (@17*@14) */
  w17 *= w14;
  /* #214: @24 = @10[0] */
  for (rr=(&w24), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #215: @16 = (@24*@16) */
  w16  = (w24*w16);
  /* #216: @17 = (@17-@16) */
  w17 -= w16;
  /* #217: @17 = (@17+@23) */
  w17 += w23;
  /* #218: @17 = (@17+@3) */
  w17 += w3;
  /* #219: @17 = (@17-@35) */
  w17 -= w35;
  /* #220: @17 = (@17-@34) */
  w17 -= w34;
  /* #221: @17 = (@17+@41) */
  w17 += w41;
  /* #222: output[0][11] = @17 */
  if (res[0]) res[0][11] = w17;
  /* #223: @24 = (@24*@15) */
  w24 *= w15;
  /* #224: @39 = (@39*@14) */
  w39 *= w14;
  /* #225: @24 = (@24-@39) */
  w24 -= w39;
  /* #226: @24 = (@24+@38) */
  w24 += w38;
  /* #227: @24 = (@24-@22) */
  w24 -= w22;
  /* #228: @24 = (@24+@20) */
  w24 += w20;
  /* #229: @24 = (@24-@28) */
  w24 -= w28;
  /* #230: @24 = (@24+@42) */
  w24 += w42;
  /* #231: output[0][12] = @24 */
  if (res[0]) res[0][12] = w24;
  /* #232: @29 = zeros(4x1) */
  casadi_clear(w29, 4);
  /* #233: (@29[1:4] += @6) */
  for (rr=w29+1, ss=w6; rr!=w29+4; rr+=1) *rr += *ss++;
  /* #234: {@24, @42, @28, @20} = vertsplit(@29) */
  w24 = w29[0];
  w42 = w29[1];
  w28 = w29[2];
  w20 = w29[3];
  /* #235: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #236: @2 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w2);
  /* #237: @7 = zeros(3x3) */
  casadi_clear(w7, 9);
  /* #238: @7 = mac(@4,@4,@7) */
  for (i=0, rr=w7; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #239: @7 = (2.*@7) */
  for (i=0, rr=w7, cs=w7; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #240: @2 = (@2+@7) */
  for (i=0, rr=w2, cs=w7; i<9; ++i) (*rr++) += (*cs++);
  /* #241: @4 = (@21*@4) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) (*rr++)  = (w21*(*cs++));
  /* #242: @2 = (@2+@4) */
  for (i=0, rr=w2, cs=w4; i<9; ++i) (*rr++) += (*cs++);
  /* #243: @6 = mac(@2,@5,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #244: @21 = dot(@6, @11) */
  w21 = casadi_dot(3, w6, w11);
  /* #245: @24 = (@24+@21) */
  w24 += w21;
  /* #246: output[0][13] = @24 */
  if (res[0]) res[0][13] = w24;
  /* #247: output[0][14] = @42 */
  if (res[0]) res[0][14] = w42;
  /* #248: output[0][15] = @28 */
  if (res[0]) res[0][15] = w28;
  /* #249: output[0][16] = @20 */
  if (res[0]) res[0][16] = w20;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 183;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
