/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
static const casadi_int casadi_s3[12] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
static const casadi_int casadi_s4[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* quadrotor_expl_vde_adj:(i0[13],i1[13],i2[4],i3[13])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+4, *w1=w+17, *w2=w+20, w3, *w4=w+30, *w5=w+39, *w6=w+42, *w7=w+45, *w8=w+54, *w9=w+63, *w10=w+76, *w11=w+79, *w12=w+82, *w13=w+86, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, *w26=w+101, *w27=w+105, w28, *w29=w+110, *w30=w+114, *w31=w+118, *w32=w+122, *w33=w+126, w34, w35, *w36=w+144, w37, w38, w39, w40, w41, w42, w43, w44, *w45=w+155;
  /* #0: @0 = zeros(13x1) */
  casadi_clear(w0, 13);
  /* #1: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #3: @3 = 0.00264 */
  w3 = 2.6400000000000000e-03;
  /* #4: (@2[0] = @3) */
  for (rr=w2+0, ss=(&w3); rr!=w2+1; rr+=1) *rr = *ss++;
  /* #5: @3 = 0.00264 */
  w3 = 2.6400000000000000e-03;
  /* #6: (@2[4] = @3) */
  for (rr=w2+4, ss=(&w3); rr!=w2+5; rr+=1) *rr = *ss++;
  /* #7: @3 = 0.00496 */
  w3 = 4.9600000000000000e-03;
  /* #8: (@2[8] = @3) */
  for (rr=w2+8, ss=(&w3); rr!=w2+9; rr+=1) *rr = *ss++;
  /* #9: @4 = @2' */
  for (i=0, rr=w4, cs=w2; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #10: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #11: @3 = input[0][12] */
  w3 = arg[0] ? arg[0][12] : 0;
  /* #12: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #13: @7 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w7);
  /* #14: @7 = (@2\@7) */
  rr = w7;
  ss = w2;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #15: @8 = @7' */
  for (i=0, rr=w8, cs=w7; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #16: @9 = input[1][0] */
  casadi_copy(arg[1], 13, w9);
  /* #17: {@10, @11, @12, @13} = vertsplit(@9) */
  casadi_copy(w9, 3, w10);
  casadi_copy(w9+3, 3, w11);
  casadi_copy(w9+6, 4, w12);
  casadi_copy(w9+10, 3, w13);
  /* #18: @6 = mac(@8,@13,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #19: @13 = (-@6) */
  for (i=0, rr=w13, cs=w6; i<3; ++i) *rr++ = (- *cs++ );
  /* #20: {@14, @15, @16} = vertsplit(@13) */
  w14 = w13[0];
  w15 = w13[1];
  w16 = w13[2];
  /* #21: @17 = (@3*@15) */
  w17  = (w3*w15);
  /* #22: @18 = input[0][11] */
  w18 = arg[0] ? arg[0][11] : 0;
  /* #23: @19 = (@18*@16) */
  w19  = (w18*w16);
  /* #24: @17 = (@17-@19) */
  w17 -= w19;
  /* #25: (@5[0] += @17) */
  for (rr=w5+0, ss=(&w17); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #26: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #27: @19 = (@17*@16) */
  w19  = (w17*w16);
  /* #28: @20 = (@3*@14) */
  w20  = (w3*w14);
  /* #29: @19 = (@19-@20) */
  w19 -= w20;
  /* #30: (@5[1] += @19) */
  for (rr=w5+1, ss=(&w19); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #31: @19 = (@18*@14) */
  w19  = (w18*w14);
  /* #32: @20 = (@17*@15) */
  w20  = (w17*w15);
  /* #33: @19 = (@19-@20) */
  w19 -= w20;
  /* #34: (@5[2] += @19) */
  for (rr=w5+2, ss=(&w19); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #35: @1 = mac(@4,@5,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #36: (@0[10:13] += @1) */
  for (rr=w0+10, ss=w1; rr!=w0+13; rr+=1) *rr += *ss++;
  /* #37: @19 = 1 */
  w19 = 1.;
  /* #38: @20 = input[0][6] */
  w20 = arg[0] ? arg[0][6] : 0;
  /* #39: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #40: @22 = input[0][7] */
  w22 = arg[0] ? arg[0][7] : 0;
  /* #41: @23 = sq(@22) */
  w23 = casadi_sq( w22 );
  /* #42: @21 = (@21+@23) */
  w21 += w23;
  /* #43: @23 = input[0][8] */
  w23 = arg[0] ? arg[0][8] : 0;
  /* #44: @24 = sq(@23) */
  w24 = casadi_sq( w23 );
  /* #45: @21 = (@21+@24) */
  w21 += w24;
  /* #46: @24 = input[0][9] */
  w24 = arg[0] ? arg[0][9] : 0;
  /* #47: @25 = sq(@24) */
  w25 = casadi_sq( w24 );
  /* #48: @21 = (@21+@25) */
  w21 += w25;
  /* #49: @19 = (@19-@21) */
  w19 -= w21;
  /* #50: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #51: @26 = (@19*@12) */
  for (i=0, rr=w26, cs=w12; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #52: @27 = zeros(4x1) */
  casadi_clear(w27, 4);
  /* #53: @19 = 0 */
  w19 = 0.;
  /* #54: @21 = (-@17) */
  w21 = (- w17 );
  /* #55: @25 = (-@18) */
  w25 = (- w18 );
  /* #56: @28 = (-@3) */
  w28 = (- w3 );
  /* #57: @29 = horzcat(@19, @21, @25, @28) */
  rr=w29;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w25;
  *rr++ = w28;
  /* #58: @29 = @29' */
  /* #59: @19 = 0 */
  w19 = 0.;
  /* #60: @21 = (-@18) */
  w21 = (- w18 );
  /* #61: @30 = horzcat(@17, @19, @3, @21) */
  rr=w30;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w3;
  *rr++ = w21;
  /* #62: @30 = @30' */
  /* #63: @19 = (-@3) */
  w19 = (- w3 );
  /* #64: @21 = 0 */
  w21 = 0.;
  /* #65: @31 = horzcat(@18, @19, @21, @17) */
  rr=w31;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w17;
  /* #66: @31 = @31' */
  /* #67: @19 = (-@17) */
  w19 = (- w17 );
  /* #68: @21 = 0 */
  w21 = 0.;
  /* #69: @32 = horzcat(@3, @18, @19, @21) */
  rr=w32;
  *rr++ = w3;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w21;
  /* #70: @32 = @32' */
  /* #71: @33 = horzcat(@29, @30, @31, @32) */
  rr=w33;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  /* #72: @19 = 0.5 */
  w19 = 5.0000000000000000e-01;
  /* #73: @29 = (@19*@12) */
  for (i=0, rr=w29, cs=w12; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #74: @27 = mac(@33,@29,@27) */
  for (i=0, rr=w27; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w33+j, tt=w29+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #75: @26 = (@26+@27) */
  for (i=0, rr=w26, cs=w27; i<4; ++i) (*rr++) += (*cs++);
  /* #76: @27 = zeros(4x1) */
  casadi_clear(w27, 4);
  /* #77: @19 = input[0][0] */
  w19 = arg[0] ? arg[0][0] : 0;
  /* #78: @21 = input[0][1] */
  w21 = arg[0] ? arg[0][1] : 0;
  /* #79: @25 = input[0][2] */
  w25 = arg[0] ? arg[0][2] : 0;
  /* #80: @28 = input[0][3] */
  w28 = arg[0] ? arg[0][3] : 0;
  /* #81: @34 = input[0][4] */
  w34 = arg[0] ? arg[0][4] : 0;
  /* #82: @35 = input[0][5] */
  w35 = arg[0] ? arg[0][5] : 0;
  /* #83: @9 = vertcat(@19, @21, @25, @28, @34, @35, @20, @22, @23, @24, @17, @18, @3) */
  rr=w9;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w25;
  *rr++ = w28;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w3;
  /* #84: @30 = @9[6:10] */
  for (rr=w30, ss=w9+6; ss!=w9+10; ss+=1) *rr++ = *ss;
  /* #85: @19 = 0 */
  w19 = 0.;
  /* #86: @31 = @30' */
  casadi_copy(w30, 4, w31);
  /* #87: @19 = mac(@31,@30,@19) */
  for (i=0, rr=(&w19); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #88: @31 = (@30/@19) */
  for (i=0, rr=w31, cr=w30; i<4; ++i) (*rr++)  = ((*cr++)/w19);
  /* #89: @21 = @31[3] */
  for (rr=(&w21), ss=w31+3; ss!=w31+4; ss+=1) *rr++ = *ss;
  /* #90: @25 = (2.*@21) */
  w25 = (2.* w21 );
  /* #91: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #92: @28 = input[2][0] */
  w28 = arg[2] ? arg[2][0] : 0;
  /* #93: @1 = (@28*@11) */
  for (i=0, rr=w1, cs=w11; i<3; ++i) (*rr++)  = (w28*(*cs++));
  /* #94: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #95: @28 = 1 */
  w28 = 1.;
  /* #96: (@5[2] = @28) */
  for (rr=w5+2, ss=(&w28); rr!=w5+3; rr+=1) *rr = *ss++;
  /* #97: @13 = @5' */
  casadi_copy(w5, 3, w13);
  /* #98: @4 = mac(@1,@13,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w13+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #99: @8 = @4' */
  for (i=0, rr=w8, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #100: {@1, @13, @36} = horzsplit(@8) */
  casadi_copy(w8, 3, w1);
  casadi_copy(w8+3, 3, w13);
  casadi_copy(w8+6, 3, w36);
  /* #101: @36 = @36' */
  /* #102: {@28, @34, @35} = horzsplit(@36) */
  w28 = w36[0];
  w34 = w36[1];
  w35 = w36[2];
  /* #103: @25 = (@25*@35) */
  w25 *= w35;
  /* #104: @17 = @31[2] */
  for (rr=(&w17), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #105: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #106: @18 = (@17*@34) */
  w18  = (w17*w34);
  /* #107: @25 = (@25+@18) */
  w25 += w18;
  /* #108: @18 = @31[1] */
  for (rr=(&w18), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #109: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #110: @3 = (@18*@28) */
  w3  = (w18*w28);
  /* #111: @25 = (@25+@3) */
  w25 += w3;
  /* #112: @13 = @13' */
  /* #113: {@3, @37, @38} = horzsplit(@13) */
  w3 = w13[0];
  w37 = w13[1];
  w38 = w13[2];
  /* #114: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #115: @39 = (@17*@38) */
  w39  = (w17*w38);
  /* #116: @25 = (@25+@39) */
  w25 += w39;
  /* #117: @39 = (2.*@21) */
  w39 = (2.* w21 );
  /* #118: @39 = (@39*@37) */
  w39 *= w37;
  /* #119: @25 = (@25-@39) */
  w25 -= w39;
  /* #120: @39 = @31[0] */
  for (rr=(&w39), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #121: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #122: @40 = (@39*@3) */
  w40  = (w39*w3);
  /* #123: @25 = (@25+@40) */
  w25 += w40;
  /* #124: @1 = @1' */
  /* #125: {@40, @41, @42} = horzsplit(@1) */
  w40 = w1[0];
  w41 = w1[1];
  w42 = w1[2];
  /* #126: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #127: @43 = (@18*@42) */
  w43  = (w18*w42);
  /* #128: @25 = (@25+@43) */
  w25 += w43;
  /* #129: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #130: @43 = (@39*@41) */
  w43  = (w39*w41);
  /* #131: @25 = (@25-@43) */
  w25 -= w43;
  /* #132: @43 = (2.*@21) */
  w43 = (2.* w21 );
  /* #133: @43 = (@43*@40) */
  w43 *= w40;
  /* #134: @25 = (@25-@43) */
  w25 -= w43;
  /* #135: (@27[3] += @25) */
  for (rr=w27+3, ss=(&w25); rr!=w27+4; rr+=1) *rr += *ss++;
  /* #136: @25 = (@21*@34) */
  w25  = (w21*w34);
  /* #137: @43 = (2.*@17) */
  w43 = (2.* w17 );
  /* #138: @43 = (@43*@35) */
  w43 *= w35;
  /* #139: @25 = (@25-@43) */
  w25 -= w43;
  /* #140: @43 = (@39*@28) */
  w43  = (w39*w28);
  /* #141: @25 = (@25-@43) */
  w25 -= w43;
  /* #142: @43 = (@21*@38) */
  w43  = (w21*w38);
  /* #143: @25 = (@25+@43) */
  w25 += w43;
  /* #144: @43 = (2.*@17) */
  w43 = (2.* w17 );
  /* #145: @43 = (@43*@37) */
  w43 *= w37;
  /* #146: @25 = (@25+@43) */
  w25 += w43;
  /* #147: @43 = (@18*@3) */
  w43  = (w18*w3);
  /* #148: @25 = (@25+@43) */
  w25 += w43;
  /* #149: @43 = (@39*@42) */
  w43  = (w39*w42);
  /* #150: @25 = (@25+@43) */
  w25 += w43;
  /* #151: @43 = (@18*@41) */
  w43  = (w18*w41);
  /* #152: @25 = (@25+@43) */
  w25 += w43;
  /* #153: @43 = (2.*@17) */
  w43 = (2.* w17 );
  /* #154: @43 = (@43*@40) */
  w43 *= w40;
  /* #155: @25 = (@25-@43) */
  w25 -= w43;
  /* #156: (@27[2] += @25) */
  for (rr=w27+2, ss=(&w25); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #157: @25 = (@39*@34) */
  w25  = (w39*w34);
  /* #158: @43 = (2.*@18) */
  w43 = (2.* w18 );
  /* #159: @43 = (@43*@35) */
  w43 *= w35;
  /* #160: @25 = (@25-@43) */
  w25 -= w43;
  /* #161: @43 = (@21*@28) */
  w43  = (w21*w28);
  /* #162: @25 = (@25+@43) */
  w25 += w43;
  /* #163: @43 = (@39*@38) */
  w43  = (w39*w38);
  /* #164: @25 = (@25-@43) */
  w25 -= w43;
  /* #165: @43 = (2.*@18) */
  w43 = (2.* w18 );
  /* #166: @43 = (@43*@37) */
  w43 *= w37;
  /* #167: @25 = (@25-@43) */
  w25 -= w43;
  /* #168: @43 = (@17*@3) */
  w43  = (w17*w3);
  /* #169: @25 = (@25+@43) */
  w25 += w43;
  /* #170: @43 = (@21*@42) */
  w43  = (w21*w42);
  /* #171: @25 = (@25+@43) */
  w25 += w43;
  /* #172: @43 = (@17*@41) */
  w43  = (w17*w41);
  /* #173: @25 = (@25+@43) */
  w25 += w43;
  /* #174: @43 = (2.*@18) */
  w43 = (2.* w18 );
  /* #175: @43 = (@43*@40) */
  w43 *= w40;
  /* #176: @25 = (@25+@43) */
  w25 += w43;
  /* #177: (@27[1] += @25) */
  for (rr=w27+1, ss=(&w25); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #178: @25 = (2.*@39) */
  w25 = (2.* w39 );
  /* #179: @25 = (@25*@35) */
  w25 *= w35;
  /* #180: @34 = (@18*@34) */
  w34  = (w18*w34);
  /* #181: @25 = (@25+@34) */
  w25 += w34;
  /* #182: @28 = (@17*@28) */
  w28  = (w17*w28);
  /* #183: @25 = (@25-@28) */
  w25 -= w28;
  /* #184: @38 = (@18*@38) */
  w38  = (w18*w38);
  /* #185: @25 = (@25-@38) */
  w25 -= w38;
  /* #186: @38 = (2.*@39) */
  w38 = (2.* w39 );
  /* #187: @38 = (@38*@37) */
  w38 *= w37;
  /* #188: @25 = (@25+@38) */
  w25 += w38;
  /* #189: @3 = (@21*@3) */
  w3  = (w21*w3);
  /* #190: @25 = (@25+@3) */
  w25 += w3;
  /* #191: @42 = (@17*@42) */
  w42  = (w17*w42);
  /* #192: @25 = (@25+@42) */
  w25 += w42;
  /* #193: @41 = (@21*@41) */
  w41  = (w21*w41);
  /* #194: @25 = (@25-@41) */
  w25 -= w41;
  /* #195: @41 = (2.*@39) */
  w41 = (2.* w39 );
  /* #196: @41 = (@41*@40) */
  w41 *= w40;
  /* #197: @25 = (@25+@41) */
  w25 += w41;
  /* #198: (@27[0] += @25) */
  for (rr=w27+0, ss=(&w25); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #199: @32 = (@27/@19) */
  for (i=0, rr=w32, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)/w19);
  /* #200: @26 = (@26+@32) */
  for (i=0, rr=w26, cs=w32; i<4; ++i) (*rr++) += (*cs++);
  /* #201: @31 = (@31/@19) */
  for (i=0, rr=w31; i<4; ++i) (*rr++) /= w19;
  /* #202: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) *rr++ = (- *cs++ );
  /* #203: @19 = dot(@31, @27) */
  w19 = casadi_dot(4, w31, w27);
  /* #204: @31 = (@30*@19) */
  for (i=0, rr=w31, cr=w30; i<4; ++i) (*rr++)  = ((*cr++)*w19);
  /* #205: @26 = (@26+@31) */
  for (i=0, rr=w26, cs=w31; i<4; ++i) (*rr++) += (*cs++);
  /* #206: @31 = @30' */
  casadi_copy(w30, 4, w31);
  /* #207: @31 = (@19*@31) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #208: @31 = @31' */
  /* #209: @26 = (@26+@31) */
  for (i=0, rr=w26, cs=w31; i<4; ++i) (*rr++) += (*cs++);
  /* #210: (@0[6:10] += @26) */
  for (rr=w0+6, ss=w26; rr!=w0+10; rr+=1) *rr += *ss++;
  /* #211: (@0[3:6] += @10) */
  for (rr=w0+3, ss=w10; rr!=w0+6; rr+=1) *rr += *ss++;
  /* #212: {@19, @25, @41, @40, @42, @3, @38, @37, @28, @34, @35, @43, @44} = vertsplit(@0) */
  w19 = w0[0];
  w25 = w0[1];
  w41 = w0[2];
  w40 = w0[3];
  w42 = w0[4];
  w3 = w0[5];
  w38 = w0[6];
  w37 = w0[7];
  w28 = w0[8];
  w34 = w0[9];
  w35 = w0[10];
  w43 = w0[11];
  w44 = w0[12];
  /* #213: output[0][0] = @19 */
  if (res[0]) res[0][0] = w19;
  /* #214: output[0][1] = @25 */
  if (res[0]) res[0][1] = w25;
  /* #215: output[0][2] = @41 */
  if (res[0]) res[0][2] = w41;
  /* #216: output[0][3] = @40 */
  if (res[0]) res[0][3] = w40;
  /* #217: output[0][4] = @42 */
  if (res[0]) res[0][4] = w42;
  /* #218: output[0][5] = @3 */
  if (res[0]) res[0][5] = w3;
  /* #219: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #220: @3 = dot(@30, @12) */
  w3 = casadi_dot(4, w30, w12);
  /* #221: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #222: @20 = (@20*@3) */
  w20 *= w3;
  /* #223: @38 = (@38-@20) */
  w38 -= w20;
  /* #224: output[0][6] = @38 */
  if (res[0]) res[0][6] = w38;
  /* #225: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #226: @22 = (@22*@3) */
  w22 *= w3;
  /* #227: @37 = (@37-@22) */
  w37 -= w22;
  /* #228: output[0][7] = @37 */
  if (res[0]) res[0][7] = w37;
  /* #229: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #230: @23 = (@23*@3) */
  w23 *= w3;
  /* #231: @28 = (@28-@23) */
  w28 -= w23;
  /* #232: output[0][8] = @28 */
  if (res[0]) res[0][8] = w28;
  /* #233: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #234: @24 = (@24*@3) */
  w24 *= w3;
  /* #235: @34 = (@34-@24) */
  w34 -= w24;
  /* #236: output[0][9] = @34 */
  if (res[0]) res[0][9] = w34;
  /* #237: @10 = zeros(3x1) */
  casadi_clear(w10, 3);
  /* #238: @1 = @9[10:13] */
  for (rr=w1, ss=w9+10; ss!=w9+13; ss+=1) *rr++ = *ss;
  /* #239: @10 = mac(@2,@1,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #240: @34 = @10[1] */
  for (rr=(&w34), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #241: @24 = (@34*@16) */
  w24  = (w34*w16);
  /* #242: @3 = @10[2] */
  for (rr=(&w3), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #243: @28 = (@3*@15) */
  w28  = (w3*w15);
  /* #244: @24 = (@24-@28) */
  w24 -= w28;
  /* #245: @33 = zeros(4x4) */
  casadi_clear(w33, 16);
  /* #246: @30 = @30' */
  /* #247: @33 = mac(@29,@30,@33) */
  for (i=0, rr=w33; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w29+j, tt=w30+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #248: @45 = @33' */
  for (i=0, rr=w45, cs=w33; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #249: {@29, @30, @12, @26} = horzsplit(@45) */
  casadi_copy(w45, 4, w29);
  casadi_copy(w45+4, 4, w30);
  casadi_copy(w45+8, 4, w12);
  casadi_copy(w45+12, 4, w26);
  /* #250: @26 = @26' */
  /* #251: {@28, @23, @37, NULL} = horzsplit(@26) */
  w28 = w26[0];
  w23 = w26[1];
  w37 = w26[2];
  /* #252: @24 = (@24-@37) */
  w24 -= w37;
  /* #253: @12 = @12' */
  /* #254: {@37, @22, NULL, @38} = horzsplit(@12) */
  w37 = w12[0];
  w22 = w12[1];
  w38 = w12[3];
  /* #255: @24 = (@24+@38) */
  w24 += w38;
  /* #256: @30 = @30' */
  /* #257: {@38, NULL, @20, @42} = horzsplit(@30) */
  w38 = w30[0];
  w20 = w30[2];
  w42 = w30[3];
  /* #258: @24 = (@24+@38) */
  w24 += w38;
  /* #259: @29 = @29' */
  /* #260: {NULL, @38, @40, @41} = horzsplit(@29) */
  w38 = w29[1];
  w40 = w29[2];
  w41 = w29[3];
  /* #261: @24 = (@24-@38) */
  w24 -= w38;
  /* #262: @24 = (@24+@35) */
  w24 += w35;
  /* #263: output[0][10] = @24 */
  if (res[0]) res[0][10] = w24;
  /* #264: @3 = (@3*@14) */
  w3 *= w14;
  /* #265: @24 = @10[0] */
  for (rr=(&w24), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #266: @16 = (@24*@16) */
  w16  = (w24*w16);
  /* #267: @3 = (@3-@16) */
  w3 -= w16;
  /* #268: @3 = (@3+@23) */
  w3 += w23;
  /* #269: @3 = (@3+@37) */
  w3 += w37;
  /* #270: @3 = (@3-@42) */
  w3 -= w42;
  /* #271: @3 = (@3-@40) */
  w3 -= w40;
  /* #272: @3 = (@3+@43) */
  w3 += w43;
  /* #273: output[0][11] = @3 */
  if (res[0]) res[0][11] = w3;
  /* #274: @24 = (@24*@15) */
  w24 *= w15;
  /* #275: @34 = (@34*@14) */
  w34 *= w14;
  /* #276: @24 = (@24-@34) */
  w24 -= w34;
  /* #277: @24 = (@24+@28) */
  w24 += w28;
  /* #278: @24 = (@24-@22) */
  w24 -= w22;
  /* #279: @24 = (@24+@20) */
  w24 += w20;
  /* #280: @24 = (@24-@41) */
  w24 -= w41;
  /* #281: @24 = (@24+@44) */
  w24 += w44;
  /* #282: output[0][12] = @24 */
  if (res[0]) res[0][12] = w24;
  /* #283: @29 = zeros(4x1) */
  casadi_clear(w29, 4);
  /* #284: (@29[1:4] += @6) */
  for (rr=w29+1, ss=w6; rr!=w29+4; rr+=1) *rr += *ss++;
  /* #285: {@24, @44, @41, @20} = vertsplit(@29) */
  w24 = w29[0];
  w44 = w29[1];
  w41 = w29[2];
  w20 = w29[3];
  /* #286: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #287: @22 = sq(@39) */
  w22 = casadi_sq( w39 );
  /* #288: @28 = sq(@18) */
  w28 = casadi_sq( w18 );
  /* #289: @22 = (@22+@28) */
  w22 += w28;
  /* #290: @28 = sq(@17) */
  w28 = casadi_sq( w17 );
  /* #291: @22 = (@22-@28) */
  w22 -= w28;
  /* #292: @28 = sq(@21) */
  w28 = casadi_sq( w21 );
  /* #293: @22 = (@22-@28) */
  w22 -= w28;
  /* #294: @28 = (@18*@17) */
  w28  = (w18*w17);
  /* #295: @34 = (@39*@21) */
  w34  = (w39*w21);
  /* #296: @28 = (@28-@34) */
  w28 -= w34;
  /* #297: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #298: @34 = (@18*@21) */
  w34  = (w18*w21);
  /* #299: @14 = (@39*@17) */
  w14  = (w39*w17);
  /* #300: @34 = (@34+@14) */
  w34 += w14;
  /* #301: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #302: @10 = horzcat(@22, @28, @34) */
  rr=w10;
  *rr++ = w22;
  *rr++ = w28;
  *rr++ = w34;
  /* #303: @10 = @10' */
  /* #304: @22 = (@18*@17) */
  w22  = (w18*w17);
  /* #305: @28 = (@39*@21) */
  w28  = (w39*w21);
  /* #306: @22 = (@22+@28) */
  w22 += w28;
  /* #307: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #308: @28 = sq(@39) */
  w28 = casadi_sq( w39 );
  /* #309: @34 = sq(@17) */
  w34 = casadi_sq( w17 );
  /* #310: @28 = (@28+@34) */
  w28 += w34;
  /* #311: @34 = sq(@18) */
  w34 = casadi_sq( w18 );
  /* #312: @28 = (@28-@34) */
  w28 -= w34;
  /* #313: @34 = sq(@21) */
  w34 = casadi_sq( w21 );
  /* #314: @28 = (@28-@34) */
  w28 -= w34;
  /* #315: @34 = (@17*@21) */
  w34  = (w17*w21);
  /* #316: @14 = (@39*@18) */
  w14  = (w39*w18);
  /* #317: @34 = (@34-@14) */
  w34 -= w14;
  /* #318: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #319: @1 = horzcat(@22, @28, @34) */
  rr=w1;
  *rr++ = w22;
  *rr++ = w28;
  *rr++ = w34;
  /* #320: @1 = @1' */
  /* #321: @22 = (@18*@21) */
  w22  = (w18*w21);
  /* #322: @28 = (@39*@17) */
  w28  = (w39*w17);
  /* #323: @22 = (@22-@28) */
  w22 -= w28;
  /* #324: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #325: @28 = (@17*@21) */
  w28  = (w17*w21);
  /* #326: @34 = (@39*@18) */
  w34  = (w39*w18);
  /* #327: @28 = (@28+@34) */
  w28 += w34;
  /* #328: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #329: @39 = sq(@39) */
  w39 = casadi_sq( w39 );
  /* #330: @21 = sq(@21) */
  w21 = casadi_sq( w21 );
  /* #331: @39 = (@39+@21) */
  w39 += w21;
  /* #332: @18 = sq(@18) */
  w18 = casadi_sq( w18 );
  /* #333: @39 = (@39-@18) */
  w39 -= w18;
  /* #334: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #335: @39 = (@39-@17) */
  w39 -= w17;
  /* #336: @13 = horzcat(@22, @28, @39) */
  rr=w13;
  *rr++ = w22;
  *rr++ = w28;
  *rr++ = w39;
  /* #337: @13 = @13' */
  /* #338: @2 = horzcat(@10, @1, @13) */
  rr=w2;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #339: @8 = @2' */
  for (i=0, rr=w8, cs=w2; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #340: @6 = mac(@8,@5,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #341: @22 = dot(@6, @11) */
  w22 = casadi_dot(3, w6, w11);
  /* #342: @24 = (@24+@22) */
  w24 += w22;
  /* #343: output[0][13] = @24 */
  if (res[0]) res[0][13] = w24;
  /* #344: output[0][14] = @44 */
  if (res[0]) res[0][14] = w44;
  /* #345: output[0][15] = @41 */
  if (res[0]) res[0][15] = w41;
  /* #346: output[0][16] = @20 */
  if (res[0]) res[0][16] = w20;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 171;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
