/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s3[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s4[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s5[25] = {13, 13, 0, 3, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s9[16] = {0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* quadrotor_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[],i2[],i3[13])->(o0,o1[13],o2[13x13,9nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+18, *w16=w+31, *w17=w+34, *w18=w+37, *w19=w+46, *w20=w+55, *w21=w+64;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #16: @16 = @15[:3] */
  for (rr=w16, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #17: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #18: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #19: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #20: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #21: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #22: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #23: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #24: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #25: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #26: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #27: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #28: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #29: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #30: @15 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #31: @17 = @15[:3] */
  for (rr=w17, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #32: @16 = (@16-@17) */
  for (i=0, rr=w16, cs=w17; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @17 = @16' */
  casadi_copy(w16, 3, w17);
  /* #34: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #35: @2 = 1 */
  w2 = 1.;
  /* #36: (@18[0] = @2) */
  for (rr=w18+0, ss=(&w2); rr!=w18+1; rr+=1) *rr = *ss++;
  /* #37: @2 = 1 */
  w2 = 1.;
  /* #38: (@18[4] = @2) */
  for (rr=w18+4, ss=(&w2); rr!=w18+5; rr+=1) *rr = *ss++;
  /* #39: @2 = 1 */
  w2 = 1.;
  /* #40: (@18[8] = @2) */
  for (rr=w18+8, ss=(&w2); rr!=w18+9; rr+=1) *rr = *ss++;
  /* #41: @1 = mac(@17,@18,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #42: @0 = mac(@1,@16,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #43: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #44: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #45: @1 = @1' */
  /* #46: @17 = zeros(1x3) */
  casadi_clear(w17, 3);
  /* #47: @16 = @16' */
  /* #48: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #49: @17 = mac(@16,@19,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #50: @17 = @17' */
  /* #51: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #52: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #53: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #54: output[1][0] = @15 */
  casadi_copy(w15, 13, res[1]);
  /* #55: @20 = zeros(13x13,9nz) */
  casadi_clear(w20, 9);
  /* #56: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #57: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #58: @21 = ones(13x1,11nz) */
  casadi_fill(w21, 11, 1.);
  /* #59: {@0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@21) */
  w0 = w21[0];
  /* #60: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #61: @2 = (-@2) */
  w2 = (- w2 );
  /* #62: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #63: @1 = mac(@0,@18,@1) */
  casadi_mtimes((&w0), casadi_s2, w18, casadi_s1, w1, casadi_s0, w, 0);
  /* #64: @1 = @1' */
  /* #65: @17 = zeros(1x3) */
  casadi_clear(w17, 3);
  /* #66: @2 = @2' */
  /* #67: @17 = mac(@2,@19,@17) */
  casadi_mtimes((&w2), casadi_s2, w19, casadi_s1, w17, casadi_s0, w, 0);
  /* #68: @17 = @17' */
  /* #69: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #70: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #71: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #72: @1 = @15[:3] */
  for (rr=w1, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #73: (@20[:3] = @1) */
  for (rr=w20+0, ss=w1; rr!=w20+3; rr+=1) *rr = *ss++;
  /* #74: @1 = @15[:3] */
  for (rr=w1, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #75: (@20[:9:3] = @1) */
  for (rr=w20+0, ss=w1; rr!=w20+9; rr+=3) *rr = *ss++;
  /* #76: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #77: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #78: @2 = ones(13x1,1nz) */
  w2 = 1.;
  /* #79: {NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #80: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #81: @2 = (-@2) */
  w2 = (- w2 );
  /* #82: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #83: @1 = mac(@0,@18,@1) */
  casadi_mtimes((&w0), casadi_s3, w18, casadi_s1, w1, casadi_s0, w, 0);
  /* #84: @1 = @1' */
  /* #85: @17 = zeros(1x3) */
  casadi_clear(w17, 3);
  /* #86: @2 = @2' */
  /* #87: @17 = mac(@2,@19,@17) */
  casadi_mtimes((&w2), casadi_s3, w19, casadi_s1, w17, casadi_s0, w, 0);
  /* #88: @17 = @17' */
  /* #89: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #90: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #91: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #92: @1 = @15[:3] */
  for (rr=w1, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #93: (@20[3:6] = @1) */
  for (rr=w20+3, ss=w1; rr!=w20+6; rr+=1) *rr = *ss++;
  /* #94: @1 = @15[:3] */
  for (rr=w1, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #95: (@20[1:10:3] = @1) */
  for (rr=w20+1, ss=w1; rr!=w20+10; rr+=3) *rr = *ss++;
  /* #96: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #97: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #98: @2 = ones(13x1,1nz) */
  w2 = 1.;
  /* #99: {NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #100: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #101: @2 = (-@2) */
  w2 = (- w2 );
  /* #102: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #103: @1 = mac(@0,@18,@1) */
  casadi_mtimes((&w0), casadi_s4, w18, casadi_s1, w1, casadi_s0, w, 0);
  /* #104: @1 = @1' */
  /* #105: @17 = zeros(1x3) */
  casadi_clear(w17, 3);
  /* #106: @2 = @2' */
  /* #107: @17 = mac(@2,@19,@17) */
  casadi_mtimes((&w2), casadi_s4, w19, casadi_s1, w17, casadi_s0, w, 0);
  /* #108: @17 = @17' */
  /* #109: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #110: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #111: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #112: @1 = @15[:3] */
  for (rr=w1, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #113: (@20[6:9] = @1) */
  for (rr=w20+6, ss=w1; rr!=w20+9; rr+=1) *rr = *ss++;
  /* #114: @1 = @15[:3] */
  for (rr=w1, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #115: (@20[2:11:3] = @1) */
  for (rr=w20+2, ss=w1; rr!=w20+11; rr+=3) *rr = *ss++;
  /* #116: @19 = @20' */
  casadi_trans(w20,casadi_s5, w19, casadi_s5, iw);
  /* #117: output[2][0] = @19 */
  casadi_copy(w19, 9, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s7;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s6;
    case 2: return casadi_s5;
    case 3: return casadi_s7;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 75;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
