/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* f_error:(i0[4])->(o0[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, *w3=w+6;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #4: @3 = (@0?@1:0) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++)  = (w0?cs[i]:0);
  /* #5: @0 = (!@0) */
  w0 = (! w0 );
  /* #6: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #7: @1 = (@0?@1:0) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0?cs[i]:0);
  /* #8: @3 = (@3+@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #9: output[0][0] = @3 */
  casadi_copy(w3, 4, res[0]);
  return 0;
}

/* adj1_f_error:(i0[4],out_o0[4x1,0nz],adj_o0[4])->(adj_i0[4]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, *w3=w+6;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #4: @2 = (!@0) */
  w2 = (! w0 );
  /* #5: @1 = input[2][0] */
  casadi_copy(arg[2], 4, w1);
  /* #6: @3 = (-@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #7: @3 = (@2?@3:0) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #8: @1 = (@0?@1:0) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0?cs[i]:0);
  /* #9: @3 = (@3+@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #10: output[0][0] = @3 */
  casadi_copy(w3, 4, res[0]);
  return 0;
}

/* quadrotor_cost_ext_cost_fun_jac:(i0[13],i1[4],i2[],i3[17])->(o0,o1[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+2, *rr, *ss, *tt;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real w0, *w1=w+11, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+31, *w20=w+48, *w21=w+51, *w22=w+64, *w23=w+67, *w24=w+76, *w25=w+80, *w26=w+84, *w27=w+88, *w28=w+104, *w29=w+108, *w30=w+112, *w31=w+116, *w32=w+120, *w33=w+136, *w34=w+152, *w35=w+155, *w36=w+158, w38, w39, w40;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #21: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #27: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #28: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #29: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #30: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #31: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #32: @17 = input[0][11] */
  w17 = arg[0] ? arg[0][11] : 0;
  /* #33: @18 = input[0][12] */
  w18 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @12, @13, @14, @15, @16, @17, @18) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #35: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 10.5 */
  w2 = 1.0500000000000000e+01;
  /* #40: (@23[0] = @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #41: @2 = 10.5 */
  w2 = 1.0500000000000000e+01;
  /* #42: (@23[4] = @2) */
  for (rr=w23+4, ss=(&w2); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #43: @2 = 40.5 */
  w2 = 4.0500000000000000e+01;
  /* #44: (@23[8] = @2) */
  for (rr=w23+8, ss=(&w2); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #45: @1 = mac(@22,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #46: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #47: @2 = 0 */
  w2 = 0.;
  /* #48: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #49: @25 = @19[13:17] */
  for (rr=w25, ss=w19+13; ss!=w19+17; ss+=1) *rr++ = *ss;
  /* #50: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #51: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #52: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #53: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #54: @26 = vertcat(@3, @4, @5, @6) */
  rr=w26;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #55: @25 = (@25-@26) */
  for (i=0, rr=w25, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #56: @26 = @25' */
  casadi_copy(w25, 4, w26);
  /* #57: @27 = zeros(4x4) */
  casadi_clear(w27, 16);
  /* #58: @3 = 0.671141 */
  w3 = 6.7114093959731547e-01;
  /* #59: (@27[0] = @3) */
  for (rr=w27+0, ss=(&w3); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #60: @3 = 200 */
  w3 = 200.;
  /* #61: (@27[5] = @3) */
  for (rr=w27+5, ss=(&w3); rr!=w27+6; rr+=1) *rr = *ss++;
  /* #62: @3 = 200 */
  w3 = 200.;
  /* #63: (@27[10] = @3) */
  for (rr=w27+10, ss=(&w3); rr!=w27+11; rr+=1) *rr = *ss++;
  /* #64: @3 = 200 */
  w3 = 200.;
  /* #65: (@27[15] = @3) */
  for (rr=w27+15, ss=(&w3); rr!=w27+16; rr+=1) *rr = *ss++;
  /* #66: @24 = mac(@26,@27,@24) */
  for (i=0, rr=w24; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #67: @2 = mac(@24,@25,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #68: @0 = (@0+@2) */
  w0 += w2;
  /* #69: @2 = 1 */
  w2 = 1.;
  /* #70: @26 = zeros(4x1) */
  casadi_clear(w26, 4);
  /* #71: @3 = (-@13) */
  w3 = (- w13 );
  /* #72: @4 = (-@14) */
  w4 = (- w14 );
  /* #73: @5 = (-@15) */
  w5 = (- w15 );
  /* #74: @28 = horzcat(@12, @3, @4, @5) */
  rr=w28;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #75: @28 = @28' */
  /* #76: @3 = (-@15) */
  w3 = (- w15 );
  /* #77: @29 = horzcat(@13, @12, @3, @14) */
  rr=w29;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w14;
  /* #78: @29 = @29' */
  /* #79: @3 = (-@13) */
  w3 = (- w13 );
  /* #80: @30 = horzcat(@14, @15, @12, @3) */
  rr=w30;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w12;
  *rr++ = w3;
  /* #81: @30 = @30' */
  /* #82: @14 = (-@14) */
  w14 = (- w14 );
  /* #83: @31 = horzcat(@15, @14, @13, @12) */
  rr=w31;
  *rr++ = w15;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w12;
  /* #84: @31 = @31' */
  /* #85: @32 = horzcat(@28, @29, @30, @31) */
  rr=w32;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  /* #86: @33 = @32' */
  for (i=0, rr=w33, cs=w32; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #87: @9 = (-@9) */
  w9 = (- w9 );
  /* #88: @10 = (-@10) */
  w10 = (- w10 );
  /* #89: @11 = (-@11) */
  w11 = (- w11 );
  /* #90: @28 = vertcat(@8, @9, @10, @11) */
  rr=w28;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #91: @26 = mac(@33,@28,@26) */
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w33+j, tt=w28+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #92: @29 = f_error(@26) */
  arg1[0]=w26;
  res1[0]=w29;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #93: @8 = @29[0] */
  for (rr=(&w8), ss=w29+0; ss!=w29+1; ss+=1) *rr++ = *ss;
  /* #94: @2 = (@2-@8) */
  w2 -= w8;
  /* #95: @8 = 0 */
  w8 = 0.;
  /* #96: @22 = @29[1:4] */
  for (rr=w22, ss=w29+1; ss!=w29+4; ss+=1) *rr++ = *ss;
  /* #97: @34 = @22' */
  casadi_copy(w22, 3, w34);
  /* #98: @35 = @29[1:4] */
  for (rr=w35, ss=w29+1; ss!=w29+4; ss+=1) *rr++ = *ss;
  /* #99: @8 = mac(@34,@35,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #100: @2 = (@2+@8) */
  w2 += w8;
  /* #101: @0 = (@0+@2) */
  w0 += w2;
  /* #102: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #103: @24 = @24' */
  /* #104: @29 = zeros(1x4) */
  casadi_clear(w29, 4);
  /* #105: @25 = @25' */
  /* #106: @33 = @27' */
  for (i=0, rr=w33, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #107: @29 = mac(@25,@33,@29) */
  for (i=0, rr=w29; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w33+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #108: @29 = @29' */
  /* #109: @24 = (@24+@29) */
  for (i=0, rr=w24, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #110: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #111: {@0, @2, @8, @9} = vertsplit(@24) */
  w0 = w24[0];
  w2 = w24[1];
  w8 = w24[2];
  w9 = w24[3];
  /* #112: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #113: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #114: output[1][2] = @8 */
  if (res[1]) res[1][2] = w8;
  /* #115: output[1][3] = @9 */
  if (res[1]) res[1][3] = w9;
  /* #116: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #117: @1 = @1' */
  /* #118: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #119: @20 = @20' */
  /* #120: @36 = @23' */
  for (i=0, rr=w36, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #121: @34 = mac(@20,@36,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #122: @34 = @34' */
  /* #123: @1 = (@1+@34) */
  for (i=0, rr=w1, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #124: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #125: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #126: {@9, @8, @2, @0, @10, @11, @15, @14, @13, @12, @3, @4, @5} = vertsplit(@21) */
  w9 = w21[0];
  w8 = w21[1];
  w2 = w21[2];
  w0 = w21[3];
  w10 = w21[4];
  w11 = w21[5];
  w15 = w21[6];
  w14 = w21[7];
  w13 = w21[8];
  w12 = w21[9];
  w3 = w21[10];
  w4 = w21[11];
  w5 = w21[12];
  /* #127: output[1][4] = @9 */
  if (res[1]) res[1][4] = w9;
  /* #128: output[1][5] = @8 */
  if (res[1]) res[1][5] = w8;
  /* #129: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #130: output[1][7] = @0 */
  if (res[1]) res[1][7] = w0;
  /* #131: output[1][8] = @10 */
  if (res[1]) res[1][8] = w10;
  /* #132: output[1][9] = @11 */
  if (res[1]) res[1][9] = w11;
  /* #133: @33 = zeros(4x4) */
  casadi_clear(w33, 16);
  /* #134: @37 = zeros(4x1,0nz) */
  /* #135: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #136: (@24[1:4] += @22) */
  for (rr=w24+1, ss=w22; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #137: (@24[1:4] += @35) */
  for (rr=w24+1, ss=w35; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #138: @11 = -1 */
  w11 = -1.;
  /* #139: (@24[0] += @11) */
  for (rr=w24+0, ss=(&w11); rr!=w24+1; rr+=1) *rr += *ss++;
  /* #140: @29 = adj1_f_error(@26, @37, @24) */
  arg1[0]=w26;
  arg1[1]=0;
  arg1[2]=w24;
  res1[0]=w29;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #141: @28 = @28' */
  /* #142: @33 = mac(@29,@28,@33) */
  for (i=0, rr=w33; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w29+j, tt=w28+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #143: @27 = @33' */
  for (i=0, rr=w27, cs=w33; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #144: {@29, @28, @26, @24} = horzsplit(@27) */
  casadi_copy(w27, 4, w29);
  casadi_copy(w27+4, 4, w28);
  casadi_copy(w27+8, 4, w26);
  casadi_copy(w27+12, 4, w24);
  /* #145: @24 = @24' */
  /* #146: {@11, @10, @0, @2} = horzsplit(@24) */
  w11 = w24[0];
  w10 = w24[1];
  w0 = w24[2];
  w2 = w24[3];
  /* #147: @26 = @26' */
  /* #148: {@8, @9, @6, @7} = horzsplit(@26) */
  w8 = w26[0];
  w9 = w26[1];
  w6 = w26[2];
  w7 = w26[3];
  /* #149: @2 = (@2+@6) */
  w2 += w6;
  /* #150: @28 = @28' */
  /* #151: {@6, @16, @17, @18} = horzsplit(@28) */
  w6 = w28[0];
  w16 = w28[1];
  w17 = w28[2];
  w18 = w28[3];
  /* #152: @2 = (@2+@16) */
  w2 += w16;
  /* #153: @29 = @29' */
  /* #154: {@16, @38, @39, @40} = horzsplit(@29) */
  w16 = w29[0];
  w38 = w29[1];
  w39 = w29[2];
  w40 = w29[3];
  /* #155: @2 = (@2+@16) */
  w2 += w16;
  /* #156: @2 = (@2+@15) */
  w2 += w15;
  /* #157: output[1][10] = @2 */
  if (res[1]) res[1][10] = w2;
  /* #158: @0 = (@0-@7) */
  w0 -= w7;
  /* #159: @0 = (@0+@6) */
  w0 += w6;
  /* #160: @0 = (@0-@38) */
  w0 -= w38;
  /* #161: @0 = (@0+@14) */
  w0 += w14;
  /* #162: output[1][11] = @0 */
  if (res[1]) res[1][11] = w0;
  /* #163: @8 = (@8-@10) */
  w8 -= w10;
  /* #164: @8 = (@8+@18) */
  w8 += w18;
  /* #165: @8 = (@8-@39) */
  w8 -= w39;
  /* #166: @8 = (@8+@13) */
  w8 += w13;
  /* #167: output[1][12] = @8 */
  if (res[1]) res[1][12] = w8;
  /* #168: @11 = (@11+@9) */
  w11 += w9;
  /* #169: @11 = (@11-@17) */
  w11 -= w17;
  /* #170: @11 = (@11-@40) */
  w11 -= w40;
  /* #171: @11 = (@11+@12) */
  w11 += w12;
  /* #172: output[1][13] = @11 */
  if (res[1]) res[1][13] = w11;
  /* #173: output[1][14] = @3 */
  if (res[1]) res[1][14] = w3;
  /* #174: output[1][15] = @4 */
  if (res[1]) res[1][15] = w4;
  /* #175: output[1][16] = @5 */
  if (res[1]) res[1][16] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 170;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
