/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s3[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[11] = {4, 4, 0, 1, 2, 3, 4, 1, 0, 3, 2};
static const casadi_int casadi_s6[11] = {4, 4, 0, 1, 2, 3, 4, 2, 3, 0, 1};
static const casadi_int casadi_s7[11] = {4, 4, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s8[7] = {0, 1, 2, 6, 7, 8, 9};
static const casadi_int casadi_s9[7] = {0, 1, 2, 9, 10, 11, 12};
static const casadi_int casadi_s10[7] = {0, 3, 6, 9, 13, 17, 21};
static const casadi_int casadi_s11[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s12[7] = {3, 4, 5, 13, 14, 15, 16};
static const casadi_int casadi_s13[7] = {1, 4, 7, 10, 14, 18, 22};
static const casadi_int casadi_s14[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s15[7] = {6, 7, 8, 17, 18, 19, 20};
static const casadi_int casadi_s16[7] = {2, 5, 8, 11, 15, 19, 23};
static const casadi_int casadi_s17[41] = {13, 13, 0, 3, 6, 9, 9, 9, 9, 13, 17, 21, 25, 25, 25, 25, 0, 1, 2, 0, 1, 2, 0, 1, 2, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9};
static const casadi_int casadi_s18[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s19[3] = {0, 0, 0};
static const casadi_int casadi_s20[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s21[16] = {0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* f_error:(i0[4])->(o0[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, *w3=w+6;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #4: @3 = (@0?@1:0) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++)  = (w0?(*cs++):0);
  /* #5: @0 = (!@0) */
  w0 = (! w0 );
  /* #6: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #7: @1 = (@0?@1:0) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0?(*cs++):0);
  /* #8: @3 = (@3+@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #9: output[0][0] = @3 */
  casadi_copy(w3, 4, res[0]);
  return 0;
}

/* adj1_f_error:(i0[4],out_o0[4x1,0nz],adj_o0[4])->(adj_i0[4]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, *w3=w+6;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #4: @2 = 1 */
  w2 = 1.;
  /* #5: @2 = (@0?@2:0) */
  w2  = (w0?w2:0);
  /* #6: @1 = input[2][0] */
  casadi_copy(arg[2], 4, w1);
  /* #7: @3 = (@2*@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #8: @0 = (!@0) */
  w0 = (! w0 );
  /* #9: @2 = 1 */
  w2 = 1.;
  /* #10: @0 = (@0?@2:0) */
  w0  = (w0?w2:0);
  /* #11: @1 = (@0*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #12: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) -= (*cs++);
  /* #13: output[0][0] = @3 */
  casadi_copy(w3, 4, res[0]);
  return 0;
}

/* fwd4_f_error:(i0[4],out_o0[4x1,0nz],fwd_i0[4x4])->(fwd_o0[4x4]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, *w3=w+6, w4;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #4: @2 = 1 */
  w2 = 1.;
  /* #5: @2 = (@0?@2:0) */
  w2  = (w0?w2:0);
  /* #6: @1 = input[2][0] */
  casadi_copy(arg[2], 4, w1);
  /* #7: @3 = (@2*@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #8: @0 = (!@0) */
  w0 = (! w0 );
  /* #9: @4 = 1 */
  w4 = 1.;
  /* #10: @0 = (@0?@4:0) */
  w0  = (w0?w4:0);
  /* #11: @1 = (@0*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #12: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) -= (*cs++);
  /* #13: output[0][0] = @3 */
  casadi_copy(w3, 4, res[0]);
  /* #14: @3 = input[2][1] */
  casadi_copy(arg[2] ? arg[2]+4 : 0, 4, w3);
  /* #15: @1 = (@2*@3) */
  for (i=0, rr=w1, cs=w3; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #16: @3 = (@0*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #17: @1 = (@1-@3) */
  for (i=0, rr=w1, cs=w3; i<4; ++i) (*rr++) -= (*cs++);
  /* #18: output[0][1] = @1 */
  if (res[0]) casadi_copy(w1, 4, res[0]+4);
  /* #19: @1 = input[2][2] */
  casadi_copy(arg[2] ? arg[2]+8 : 0, 4, w1);
  /* #20: @3 = (@2*@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #21: @1 = (@0*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #22: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) -= (*cs++);
  /* #23: output[0][2] = @3 */
  if (res[0]) casadi_copy(w3, 4, res[0]+8);
  /* #24: @3 = input[2][3] */
  casadi_copy(arg[2] ? arg[2]+12 : 0, 4, w3);
  /* #25: @1 = (@2*@3) */
  for (i=0, rr=w1, cs=w3; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #26: @3 = (@0*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #27: @1 = (@1-@3) */
  for (i=0, rr=w1, cs=w3; i<4; ++i) (*rr++) -= (*cs++);
  /* #28: output[0][3] = @1 */
  if (res[0]) casadi_copy(w1, 4, res[0]+12);
  return 0;
}

/* fwd4_adj1_f_error:(i0[4],out_o0[4x1,0nz],adj_o0[4],out_adj_i0[4x1,0nz],fwd_i0[4x4],fwd_out_o0[4x4,0nz],fwd_adj_o0[4x4])->(fwd_adj_i0[4x4]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, *w3=w+6, w4;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #4: @2 = 1 */
  w2 = 1.;
  /* #5: @2 = (@0?@2:0) */
  w2  = (w0?w2:0);
  /* #6: @1 = input[6][0] */
  casadi_copy(arg[6], 4, w1);
  /* #7: @3 = (@2*@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #8: @0 = (!@0) */
  w0 = (! w0 );
  /* #9: @4 = 1 */
  w4 = 1.;
  /* #10: @0 = (@0?@4:0) */
  w0  = (w0?w4:0);
  /* #11: @1 = (@0*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #12: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) -= (*cs++);
  /* #13: output[0][0] = @3 */
  casadi_copy(w3, 4, res[0]);
  /* #14: @3 = input[6][1] */
  casadi_copy(arg[6] ? arg[6]+4 : 0, 4, w3);
  /* #15: @1 = (@2*@3) */
  for (i=0, rr=w1, cs=w3; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #16: @3 = (@0*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #17: @1 = (@1-@3) */
  for (i=0, rr=w1, cs=w3; i<4; ++i) (*rr++) -= (*cs++);
  /* #18: output[0][1] = @1 */
  if (res[0]) casadi_copy(w1, 4, res[0]+4);
  /* #19: @1 = input[6][2] */
  casadi_copy(arg[6] ? arg[6]+8 : 0, 4, w1);
  /* #20: @3 = (@2*@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #21: @1 = (@0*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #22: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) -= (*cs++);
  /* #23: output[0][2] = @3 */
  if (res[0]) casadi_copy(w3, 4, res[0]+8);
  /* #24: @3 = input[6][3] */
  casadi_copy(arg[6] ? arg[6]+12 : 0, 4, w3);
  /* #25: @1 = (@2*@3) */
  for (i=0, rr=w1, cs=w3; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #26: @3 = (@0*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #27: @1 = (@1-@3) */
  for (i=0, rr=w1, cs=w3; i<4; ++i) (*rr++) -= (*cs++);
  /* #28: output[0][3] = @1 */
  if (res[0]) casadi_copy(w1, 4, res[0]+12);
  return 0;
}

/* quadrotor_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[],i2[],i3[13])->(o0,o1[13],o2[13x13,25nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+5, *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real w0, *w1=w+12, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+28, *w16=w+41, w17, w18, w19, w20, *w21=w+48, *w22=w+51, *w23=w+60, *w24=w+64, *w25=w+68, *w26=w+72, *w27=w+76, *w28=w+80, *w29=w+96, *w30=w+112, *w31=w+115, *w32=w+118, *w34=w+127, *w35=w+131, *w36=w+135, w37, w38, w39, w40, *w41=w+143, *w42=w+168, *w48=w+176, *w49=w+178, *w50=w+182, *w51=w+186, *w52=w+202, w53, w54, w55, w56, w57, w58, w59, *w60=w+225, *w64=w+232;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #16: @16 = @15[:3] */
  for (rr=w16, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #17: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #18: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #19: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #20: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #21: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #22: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #23: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #24: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #25: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #26: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #27: @18 = input[0][10] */
  w18 = arg[0] ? arg[0][10] : 0;
  /* #28: @19 = input[0][11] */
  w19 = arg[0] ? arg[0][11] : 0;
  /* #29: @20 = input[0][12] */
  w20 = arg[0] ? arg[0][12] : 0;
  /* #30: @15 = vertcat(@2, @3, @4, @5, @6, @7, @12, @13, @14, @17, @18, @19, @20) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #31: @21 = @15[:3] */
  for (rr=w21, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #32: @16 = (@16-@21) */
  for (i=0, rr=w16, cs=w21; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @21 = @16' */
  casadi_copy(w16, 3, w21);
  /* #34: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #35: @2 = 1.5 */
  w2 = 1.5000000000000000e+00;
  /* #36: (@22[0] = @2) */
  for (rr=w22+0, ss=(&w2); rr!=w22+1; rr+=1) *rr = *ss++;
  /* #37: @2 = 1.5 */
  w2 = 1.5000000000000000e+00;
  /* #38: (@22[4] = @2) */
  for (rr=w22+4, ss=(&w2); rr!=w22+5; rr+=1) *rr = *ss++;
  /* #39: @2 = 10 */
  w2 = 10.;
  /* #40: (@22[8] = @2) */
  for (rr=w22+8, ss=(&w2); rr!=w22+9; rr+=1) *rr = *ss++;
  /* #41: @1 = mac(@21,@22,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #42: @0 = mac(@1,@16,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #43: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #44: @3 = 1 */
  w3 = 1.;
  /* #45: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #46: @4 = (-@13) */
  w4 = (- w13 );
  /* #47: @5 = (-@14) */
  w5 = (- w14 );
  /* #48: @6 = (-@17) */
  w6 = (- w17 );
  /* #49: @24 = horzcat(@12, @4, @5, @6) */
  rr=w24;
  *rr++ = w12;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #50: @24 = @24' */
  /* #51: @4 = (-@17) */
  w4 = (- w17 );
  /* #52: @25 = horzcat(@13, @12, @4, @14) */
  rr=w25;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w4;
  *rr++ = w14;
  /* #53: @25 = @25' */
  /* #54: @4 = (-@13) */
  w4 = (- w13 );
  /* #55: @26 = horzcat(@14, @17, @12, @4) */
  rr=w26;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w12;
  *rr++ = w4;
  /* #56: @26 = @26' */
  /* #57: @14 = (-@14) */
  w14 = (- w14 );
  /* #58: @27 = horzcat(@17, @14, @13, @12) */
  rr=w27;
  *rr++ = w17;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w12;
  /* #59: @27 = @27' */
  /* #60: @28 = horzcat(@24, @25, @26, @27) */
  rr=w28;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  /* #61: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #62: @9 = (-@9) */
  w9 = (- w9 );
  /* #63: @10 = (-@10) */
  w10 = (- w10 );
  /* #64: @11 = (-@11) */
  w11 = (- w11 );
  /* #65: @24 = vertcat(@8, @9, @10, @11) */
  rr=w24;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #66: @23 = mac(@29,@24,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w29+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #67: @25 = f_error(@23) */
  arg1[0]=w23;
  res1[0]=w25;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #68: @8 = @25[0] */
  for (rr=(&w8), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #69: @3 = (@3-@8) */
  w3 -= w8;
  /* #70: @8 = 0 */
  w8 = 0.;
  /* #71: @21 = @25[1:4] */
  for (rr=w21, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #72: @30 = @21' */
  casadi_copy(w21, 3, w30);
  /* #73: @31 = @25[1:4] */
  for (rr=w31, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #74: @8 = mac(@30,@31,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #75: @3 = (@3+@8) */
  w3 += w8;
  /* #76: @2 = (@2*@3) */
  w2 *= w3;
  /* #77: @0 = (@0+@2) */
  w0 += w2;
  /* #78: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #79: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #80: @1 = @1' */
  /* #81: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #82: @16 = @16' */
  /* #83: @32 = @22' */
  for (i=0, rr=w32, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #84: @30 = mac(@16,@32,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #85: @30 = @30' */
  /* #86: @1 = (@1+@30) */
  for (i=0, rr=w1, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #87: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #88: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #89: {@0, @2, @3, @8, @9, @10, @11, @17, @14, @13, @12, @4, @5} = vertsplit(@15) */
  w0 = w15[0];
  w2 = w15[1];
  w3 = w15[2];
  w8 = w15[3];
  w9 = w15[4];
  w10 = w15[5];
  w11 = w15[6];
  w17 = w15[7];
  w14 = w15[8];
  w13 = w15[9];
  w12 = w15[10];
  w4 = w15[11];
  w5 = w15[12];
  /* #90: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #91: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #92: output[1][2] = @3 */
  if (res[1]) res[1][2] = w3;
  /* #93: output[1][3] = @8 */
  if (res[1]) res[1][3] = w8;
  /* #94: output[1][4] = @9 */
  if (res[1]) res[1][4] = w9;
  /* #95: output[1][5] = @10 */
  if (res[1]) res[1][5] = w10;
  /* #96: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #97: @33 = zeros(4x1,0nz) */
  /* #98: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #99: @10 = 0.5 */
  w10 = 5.0000000000000000e-01;
  /* #100: @21 = (@10*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #101: (@25[1:4] += @21) */
  for (rr=w25+1, ss=w21; rr!=w25+4; rr+=1) *rr += *ss++;
  /* #102: @31 = @31' */
  /* #103: @31 = (@10*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #104: @31 = @31' */
  /* #105: (@25[1:4] += @31) */
  for (rr=w25+1, ss=w31; rr!=w25+4; rr+=1) *rr += *ss++;
  /* #106: @9 = -0.5 */
  w9 = -5.0000000000000000e-01;
  /* #107: (@25[0] += @9) */
  for (rr=w25+0, ss=(&w9); rr!=w25+1; rr+=1) *rr += *ss++;
  /* #108: @26 = adj1_f_error(@23, @33, @25) */
  arg1[0]=w23;
  arg1[1]=0;
  arg1[2]=w25;
  res1[0]=w26;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #109: @27 = @24' */
  casadi_copy(w24, 4, w27);
  /* #110: @29 = mac(@26,@27,@29) */
  for (i=0, rr=w29; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #111: @28 = @29' */
  for (i=0, rr=w28, cs=w29; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #112: {@26, @34, @35, @36} = horzsplit(@28) */
  casadi_copy(w28, 4, w26);
  casadi_copy(w28+4, 4, w34);
  casadi_copy(w28+8, 4, w35);
  casadi_copy(w28+12, 4, w36);
  /* #113: @36 = @36' */
  /* #114: {@9, @8, @3, @2} = horzsplit(@36) */
  w9 = w36[0];
  w8 = w36[1];
  w3 = w36[2];
  w2 = w36[3];
  /* #115: @35 = @35' */
  /* #116: {@0, @6, @7, @18} = horzsplit(@35) */
  w0 = w35[0];
  w6 = w35[1];
  w7 = w35[2];
  w18 = w35[3];
  /* #117: @2 = (@2+@7) */
  w2 += w7;
  /* #118: @34 = @34' */
  /* #119: {@7, @19, @20, @37} = horzsplit(@34) */
  w7 = w34[0];
  w19 = w34[1];
  w20 = w34[2];
  w37 = w34[3];
  /* #120: @2 = (@2+@19) */
  w2 += w19;
  /* #121: @26 = @26' */
  /* #122: {@19, @38, @39, @40} = horzsplit(@26) */
  w19 = w26[0];
  w38 = w26[1];
  w39 = w26[2];
  w40 = w26[3];
  /* #123: @2 = (@2+@19) */
  w2 += w19;
  /* #124: @2 = (@2+@11) */
  w2 += w11;
  /* #125: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #126: @3 = (@3-@18) */
  w3 -= w18;
  /* #127: @3 = (@3+@7) */
  w3 += w7;
  /* #128: @3 = (@3-@38) */
  w3 -= w38;
  /* #129: @3 = (@3+@17) */
  w3 += w17;
  /* #130: output[1][7] = @3 */
  if (res[1]) res[1][7] = w3;
  /* #131: @0 = (@0-@8) */
  w0 -= w8;
  /* #132: @0 = (@0+@37) */
  w0 += w37;
  /* #133: @0 = (@0-@39) */
  w0 -= w39;
  /* #134: @0 = (@0+@14) */
  w0 += w14;
  /* #135: output[1][8] = @0 */
  if (res[1]) res[1][8] = w0;
  /* #136: @9 = (@9+@6) */
  w9 += w6;
  /* #137: @9 = (@9-@20) */
  w9 -= w20;
  /* #138: @9 = (@9-@40) */
  w9 -= w40;
  /* #139: @9 = (@9+@13) */
  w9 += w13;
  /* #140: output[1][9] = @9 */
  if (res[1]) res[1][9] = w9;
  /* #141: output[1][10] = @12 */
  if (res[1]) res[1][10] = w12;
  /* #142: output[1][11] = @4 */
  if (res[1]) res[1][11] = w4;
  /* #143: output[1][12] = @5 */
  if (res[1]) res[1][12] = w5;
  /* #144: @41 = zeros(13x13,25nz) */
  casadi_clear(w41, 25);
  /* #145: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #146: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #147: @42 = ones(13x1,8nz) */
  casadi_fill(w42, 8, 1.);
  /* #148: {@5, NULL, NULL, NULL, NULL, NULL, @4, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@42) */
  w5 = w42[0];
  w4 = w42[4];
  /* #149: @12 = @5[0] */
  for (rr=(&w12), ss=(&w5)+0; ss!=(&w5)+1; ss+=1) *rr++ = *ss;
  /* #150: @12 = (-@12) */
  w12 = (- w12 );
  /* #151: @5 = @12' */
  casadi_copy((&w12), 1, (&w5));
  /* #152: @31 = mac(@5,@22,@31) */
  casadi_mtimes((&w5), casadi_s2, w22, casadi_s1, w31, casadi_s0, w, 0);
  /* #153: @31 = @31' */
  /* #154: @21 = zeros(1x3) */
  casadi_clear(w21, 3);
  /* #155: @12 = @12' */
  /* #156: @21 = mac(@12,@32,@21) */
  casadi_mtimes((&w12), casadi_s2, w32, casadi_s1, w21, casadi_s0, w, 0);
  /* #157: @21 = @21' */
  /* #158: @31 = (@31+@21) */
  for (i=0, rr=w31, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #159: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #160: (@15[:3] += @31) */
  for (rr=w15+0, ss=w31; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #161: {@12, @5, @9, @13, @40, @20, @6, @0, @14, @39, @37, @8, @3} = vertsplit(@15) */
  w12 = w15[0];
  w5 = w15[1];
  w9 = w15[2];
  w13 = w15[3];
  w40 = w15[4];
  w20 = w15[5];
  w6 = w15[6];
  w0 = w15[7];
  w14 = w15[8];
  w39 = w15[9];
  w37 = w15[10];
  w8 = w15[11];
  w3 = w15[12];
  /* #162: @28 = zeros(4x4) */
  casadi_clear(w28, 16);
  /* #163: @43 = zeros(4x1,0nz) */
  /* #164: @26 = zeros(4x1) */
  casadi_clear(w26, 4);
  /* #165: @44 = 00 */
  /* #166: @45 = 00 */
  /* #167: @46 = 00 */
  /* #168: @17 = horzcat(@4, @44, @45, @46) */
  rr=(&w17);
  *rr++ = w4;
  /* #169: @17 = @17' */
  /* #170: @44 = 00 */
  /* #171: @45 = 00 */
  /* #172: @46 = 00 */
  /* #173: @38 = horzcat(@44, @4, @45, @46) */
  rr=(&w38);
  *rr++ = w4;
  /* #174: @38 = @38' */
  /* #175: @45 = 00 */
  /* #176: @47 = 00 */
  /* #177: @7 = horzcat(@46, @45, @4, @47) */
  rr=(&w7);
  *rr++ = w4;
  /* #178: @7 = @7' */
  /* #179: @46 = 00 */
  /* #180: @18 = horzcat(@45, @46, @44, @4) */
  rr=(&w18);
  *rr++ = w4;
  /* #181: @18 = @18' */
  /* #182: @34 = horzcat(@17, @38, @7, @18) */
  rr=w34;
  *rr++ = w17;
  *rr++ = w38;
  *rr++ = w7;
  *rr++ = w18;
  /* #183: @35 = @34' */
  casadi_trans(w34,casadi_s3, w35, casadi_s3, iw);
  /* #184: @26 = mac(@35,@24,@26) */
  casadi_mtimes(w35, casadi_s3, w24, casadi_s4, w26, casadi_s4, w, 0);
  /* #185: @35 = zeros(4x1) */
  casadi_clear(w35, 4);
  /* #186: @45 = 00 */
  /* #187: @48 = ones(13x1,2nz) */
  casadi_fill(w48, 2, 1.);
  /* #188: {NULL, @17, NULL, NULL, NULL, NULL, NULL, @38, NULL, NULL, NULL, NULL, NULL} = vertsplit(@48) */
  w17 = w48[0];
  w38 = w48[1];
  /* #189: @7 = (-@38) */
  w7 = (- w38 );
  /* #190: @46 = 00 */
  /* #191: @44 = 00 */
  /* #192: @18 = horzcat(@45, @7, @46, @44) */
  rr=(&w18);
  *rr++ = w7;
  /* #193: @18 = @18' */
  /* #194: @46 = 00 */
  /* #195: @44 = 00 */
  /* #196: @7 = horzcat(@38, @45, @46, @44) */
  rr=(&w7);
  *rr++ = w38;
  /* #197: @7 = @7' */
  /* #198: @46 = 00 */
  /* #199: @4 = (-@38) */
  w4 = (- w38 );
  /* #200: @2 = horzcat(@44, @46, @45, @4) */
  rr=(&w2);
  *rr++ = w4;
  /* #201: @2 = @2' */
  /* #202: @44 = 00 */
  /* #203: @4 = horzcat(@46, @44, @38, @45) */
  rr=(&w4);
  *rr++ = w38;
  /* #204: @4 = @4' */
  /* #205: @34 = horzcat(@18, @7, @2, @4) */
  rr=w34;
  *rr++ = w18;
  *rr++ = w7;
  *rr++ = w2;
  *rr++ = w4;
  /* #206: @36 = @34' */
  casadi_trans(w34,casadi_s5, w36, casadi_s5, iw);
  /* #207: @35 = mac(@36,@24,@35) */
  casadi_mtimes(w36, casadi_s5, w24, casadi_s4, w35, casadi_s4, w, 0);
  /* #208: @36 = zeros(4x1) */
  casadi_clear(w36, 4);
  /* #209: @46 = 00 */
  /* #210: @44 = 00 */
  /* #211: @48 = ones(13x1,2nz) */
  casadi_fill(w48, 2, 1.);
  /* #212: {NULL, NULL, @18, NULL, NULL, NULL, NULL, NULL, @7, NULL, NULL, NULL, NULL} = vertsplit(@48) */
  w18 = w48[0];
  w7 = w48[1];
  /* #213: @2 = (-@7) */
  w2 = (- w7 );
  /* #214: @45 = 00 */
  /* #215: @4 = horzcat(@46, @44, @2, @45) */
  rr=(&w4);
  *rr++ = w2;
  /* #216: @4 = @4' */
  /* #217: @44 = 00 */
  /* #218: @45 = 00 */
  /* #219: @2 = horzcat(@44, @46, @45, @7) */
  rr=(&w2);
  *rr++ = w7;
  /* #220: @2 = @2' */
  /* #221: @45 = 00 */
  /* #222: @47 = 00 */
  /* #223: @38 = horzcat(@7, @45, @46, @47) */
  rr=(&w38);
  *rr++ = w7;
  /* #224: @38 = @38' */
  /* #225: @7 = (-@7) */
  w7 = (- w7 );
  /* #226: @11 = horzcat(@45, @7, @44, @46) */
  rr=(&w11);
  *rr++ = w7;
  /* #227: @11 = @11' */
  /* #228: @34 = horzcat(@4, @2, @38, @11) */
  rr=w34;
  *rr++ = w4;
  *rr++ = w2;
  *rr++ = w38;
  *rr++ = w11;
  /* #229: @49 = @34' */
  casadi_trans(w34,casadi_s6, w49, casadi_s6, iw);
  /* #230: @36 = mac(@49,@24,@36) */
  casadi_mtimes(w49, casadi_s6, w24, casadi_s4, w36, casadi_s4, w, 0);
  /* #231: @49 = zeros(4x1) */
  casadi_clear(w49, 4);
  /* #232: @45 = 00 */
  /* #233: @44 = 00 */
  /* #234: @46 = 00 */
  /* #235: @4 = ones(13x1,1nz) */
  w4 = 1.;
  /* #236: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @2, NULL, NULL, NULL} = vertsplit(@4) */
  w2 = w4;
  /* #237: @4 = (-@2) */
  w4 = (- w2 );
  /* #238: @38 = horzcat(@45, @44, @46, @4) */
  rr=(&w38);
  *rr++ = w4;
  /* #239: @38 = @38' */
  /* #240: @44 = 00 */
  /* #241: @4 = (-@2) */
  w4 = (- w2 );
  /* #242: @46 = 00 */
  /* #243: @11 = horzcat(@44, @45, @4, @46) */
  rr=(&w11);
  *rr++ = w4;
  /* #244: @11 = @11' */
  /* #245: @47 = 00 */
  /* #246: @4 = horzcat(@46, @2, @45, @47) */
  rr=(&w4);
  *rr++ = w2;
  /* #247: @4 = @4' */
  /* #248: @46 = 00 */
  /* #249: @7 = horzcat(@2, @46, @44, @45) */
  rr=(&w7);
  *rr++ = w2;
  /* #250: @7 = @7' */
  /* #251: @34 = horzcat(@38, @11, @4, @7) */
  rr=w34;
  *rr++ = w38;
  *rr++ = w11;
  *rr++ = w4;
  *rr++ = w7;
  /* #252: @50 = @34' */
  casadi_trans(w34,casadi_s7, w50, casadi_s7, iw);
  /* #253: @49 = mac(@50,@24,@49) */
  casadi_mtimes(w50, casadi_s7, w24, casadi_s4, w49, casadi_s4, w, 0);
  /* #254: @29 = horzcat(@26, @35, @36, @49) */
  rr=w29;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<4; ++i) *rr++ = *cs++;
  /* #255: @46 = zeros(4x4,0nz) */
  /* #256: @50 = zeros(4x1) */
  casadi_clear(w50, 4);
  /* #257: @44 = zeros(4x1,0nz) */
  /* #258: @51 = horzcat(@26, @35, @36, @49) */
  rr=w51;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<4; ++i) *rr++ = *cs++;
  /* #259: @52 = fwd4_f_error(@23, @44, @51) */
  arg1[0]=w23;
  arg1[1]=0;
  arg1[2]=w51;
  res1[0]=w52;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #260: {@26, @35, @36, @49} = horzsplit(@52) */
  casadi_copy(w52, 4, w26);
  casadi_copy(w52+4, 4, w35);
  casadi_copy(w52+8, 4, w36);
  casadi_copy(w52+12, 4, w49);
  /* #261: @31 = @26[1:4] */
  for (rr=w31, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #262: @31 = (@10*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #263: (@50[1:4] += @31) */
  for (rr=w50+1, ss=w31; rr!=w50+4; rr+=1) *rr += *ss++;
  /* #264: @31 = @26[1:4] */
  for (rr=w31, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #265: @31 = @31' */
  /* #266: @31 = (@10*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #267: @31 = @31' */
  /* #268: (@50[1:4] += @31) */
  for (rr=w50+1, ss=w31; rr!=w50+4; rr+=1) *rr += *ss++;
  /* #269: @26 = zeros(4x1) */
  casadi_clear(w26, 4);
  /* #270: @31 = @35[1:4] */
  for (rr=w31, ss=w35+1; ss!=w35+4; ss+=1) *rr++ = *ss;
  /* #271: @31 = (@10*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #272: (@26[1:4] += @31) */
  for (rr=w26+1, ss=w31; rr!=w26+4; rr+=1) *rr += *ss++;
  /* #273: @31 = @35[1:4] */
  for (rr=w31, ss=w35+1; ss!=w35+4; ss+=1) *rr++ = *ss;
  /* #274: @31 = @31' */
  /* #275: @31 = (@10*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #276: @31 = @31' */
  /* #277: (@26[1:4] += @31) */
  for (rr=w26+1, ss=w31; rr!=w26+4; rr+=1) *rr += *ss++;
  /* #278: @35 = zeros(4x1) */
  casadi_clear(w35, 4);
  /* #279: @31 = @36[1:4] */
  for (rr=w31, ss=w36+1; ss!=w36+4; ss+=1) *rr++ = *ss;
  /* #280: @31 = (@10*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #281: (@35[1:4] += @31) */
  for (rr=w35+1, ss=w31; rr!=w35+4; rr+=1) *rr += *ss++;
  /* #282: @31 = @36[1:4] */
  for (rr=w31, ss=w36+1; ss!=w36+4; ss+=1) *rr++ = *ss;
  /* #283: @31 = @31' */
  /* #284: @31 = (@10*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #285: @31 = @31' */
  /* #286: (@35[1:4] += @31) */
  for (rr=w35+1, ss=w31; rr!=w35+4; rr+=1) *rr += *ss++;
  /* #287: @36 = zeros(4x1) */
  casadi_clear(w36, 4);
  /* #288: @31 = @49[1:4] */
  for (rr=w31, ss=w49+1; ss!=w49+4; ss+=1) *rr++ = *ss;
  /* #289: @31 = (@10*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #290: (@36[1:4] += @31) */
  for (rr=w36+1, ss=w31; rr!=w36+4; rr+=1) *rr += *ss++;
  /* #291: @31 = @49[1:4] */
  for (rr=w31, ss=w49+1; ss!=w49+4; ss+=1) *rr++ = *ss;
  /* #292: @31 = @31' */
  /* #293: @31 = (@10*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #294: @31 = @31' */
  /* #295: (@36[1:4] += @31) */
  for (rr=w36+1, ss=w31; rr!=w36+4; rr+=1) *rr += *ss++;
  /* #296: @52 = horzcat(@50, @26, @35, @36) */
  rr=w52;
  for (i=0, cs=w50; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<4; ++i) *rr++ = *cs++;
  /* #297: @51 = fwd4_adj1_f_error(@23, @33, @25, @43, @29, @46, @52) */
  arg1[0]=w23;
  arg1[1]=0;
  arg1[2]=w25;
  arg1[3]=0;
  arg1[4]=w29;
  arg1[5]=0;
  arg1[6]=w52;
  res1[0]=w51;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #298: {@23, @25, @50, @26} = horzsplit(@51) */
  casadi_copy(w51, 4, w23);
  casadi_copy(w51+4, 4, w25);
  casadi_copy(w51+8, 4, w50);
  casadi_copy(w51+12, 4, w26);
  /* #299: @28 = mac(@23,@27,@28) */
  for (i=0, rr=w28; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w27+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #300: @51 = @28' */
  for (i=0, rr=w51, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #301: {@23, @35, @36, @49} = horzsplit(@51) */
  casadi_copy(w51, 4, w23);
  casadi_copy(w51+4, 4, w35);
  casadi_copy(w51+8, 4, w36);
  casadi_copy(w51+12, 4, w49);
  /* #302: @49 = @49' */
  /* #303: {@10, @38, @11, @4} = horzsplit(@49) */
  w10 = w49[0];
  w38 = w49[1];
  w11 = w49[2];
  w4 = w49[3];
  /* #304: @36 = @36' */
  /* #305: {@7, @2, @19, @53} = horzsplit(@36) */
  w7 = w36[0];
  w2 = w36[1];
  w19 = w36[2];
  w53 = w36[3];
  /* #306: @4 = (@4+@19) */
  w4 += w19;
  /* #307: @35 = @35' */
  /* #308: {@19, @54, @55, @56} = horzsplit(@35) */
  w19 = w35[0];
  w54 = w35[1];
  w55 = w35[2];
  w56 = w35[3];
  /* #309: @4 = (@4+@54) */
  w4 += w54;
  /* #310: @23 = @23' */
  /* #311: {@54, @57, @58, @59} = horzsplit(@23) */
  w54 = w23[0];
  w57 = w23[1];
  w58 = w23[2];
  w59 = w23[3];
  /* #312: @4 = (@4+@54) */
  w4 += w54;
  /* #313: @4 = (@4+@6) */
  w4 += w6;
  /* #314: @11 = (@11-@53) */
  w11 -= w53;
  /* #315: @11 = (@11+@19) */
  w11 += w19;
  /* #316: @11 = (@11-@57) */
  w11 -= w57;
  /* #317: @11 = (@11+@0) */
  w11 += w0;
  /* #318: @7 = (@7-@38) */
  w7 -= w38;
  /* #319: @7 = (@7+@56) */
  w7 += w56;
  /* #320: @7 = (@7-@58) */
  w7 -= w58;
  /* #321: @7 = (@7+@14) */
  w7 += w14;
  /* #322: @10 = (@10+@2) */
  w10 += w2;
  /* #323: @10 = (@10-@55) */
  w10 -= w55;
  /* #324: @10 = (@10-@59) */
  w10 -= w59;
  /* #325: @10 = (@10+@39) */
  w10 += w39;
  /* #326: @15 = vertcat(@12, @5, @9, @13, @40, @20, @4, @11, @7, @10, @37, @8, @3) */
  rr=w15;
  *rr++ = w12;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w20;
  *rr++ = w4;
  *rr++ = w11;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w37;
  *rr++ = w8;
  *rr++ = w3;
  /* #327: @60 = @15[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s8, rr=w60, ss=w15; cii!=casadi_s8+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #328: (@41[0, 1, 2, 9, 10, 11, 12] = @60) */
  for (cii=casadi_s9, rr=w41, ss=w60; cii!=casadi_s9+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #329: @60 = @15[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s8, rr=w60, ss=w15; cii!=casadi_s8+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #330: (@41[0, 3, 6, 9, 13, 17, 21] = @60) */
  for (cii=casadi_s10, rr=w41, ss=w60; cii!=casadi_s10+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #331: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #332: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #333: @12 = @17[0] */
  for (rr=(&w12), ss=(&w17)+0; ss!=(&w17)+1; ss+=1) *rr++ = *ss;
  /* #334: @12 = (-@12) */
  w12 = (- w12 );
  /* #335: @17 = @12' */
  casadi_copy((&w12), 1, (&w17));
  /* #336: @31 = mac(@17,@22,@31) */
  casadi_mtimes((&w17), casadi_s11, w22, casadi_s1, w31, casadi_s0, w, 0);
  /* #337: @31 = @31' */
  /* #338: @21 = zeros(1x3) */
  casadi_clear(w21, 3);
  /* #339: @12 = @12' */
  /* #340: @21 = mac(@12,@32,@21) */
  casadi_mtimes((&w12), casadi_s11, w32, casadi_s1, w21, casadi_s0, w, 0);
  /* #341: @21 = @21' */
  /* #342: @31 = (@31+@21) */
  for (i=0, rr=w31, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #343: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #344: (@15[:3] += @31) */
  for (rr=w15+0, ss=w31; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #345: {@12, @17, @5, @9, @13, @40, @20, @4, @11, @7, @10, @37, @8} = vertsplit(@15) */
  w12 = w15[0];
  w17 = w15[1];
  w5 = w15[2];
  w9 = w15[3];
  w13 = w15[4];
  w40 = w15[5];
  w20 = w15[6];
  w4 = w15[7];
  w11 = w15[8];
  w7 = w15[9];
  w10 = w15[10];
  w37 = w15[11];
  w8 = w15[12];
  /* #346: @51 = zeros(4x4) */
  casadi_clear(w51, 16);
  /* #347: @51 = mac(@25,@27,@51) */
  for (i=0, rr=w51; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w25+j, tt=w27+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #348: @28 = @51' */
  for (i=0, rr=w28, cs=w51; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #349: {@25, @23, @35, @36} = horzsplit(@28) */
  casadi_copy(w28, 4, w25);
  casadi_copy(w28+4, 4, w23);
  casadi_copy(w28+8, 4, w35);
  casadi_copy(w28+12, 4, w36);
  /* #350: @36 = @36' */
  /* #351: {@3, @39, @59, @55} = horzsplit(@36) */
  w3 = w36[0];
  w39 = w36[1];
  w59 = w36[2];
  w55 = w36[3];
  /* #352: @35 = @35' */
  /* #353: {@2, @14, @58, @56} = horzsplit(@35) */
  w2 = w35[0];
  w14 = w35[1];
  w58 = w35[2];
  w56 = w35[3];
  /* #354: @55 = (@55+@58) */
  w55 += w58;
  /* #355: @23 = @23' */
  /* #356: {@58, @38, @0, @57} = horzsplit(@23) */
  w58 = w23[0];
  w38 = w23[1];
  w0 = w23[2];
  w57 = w23[3];
  /* #357: @55 = (@55+@38) */
  w55 += w38;
  /* #358: @25 = @25' */
  /* #359: {@38, @19, @53, @6} = horzsplit(@25) */
  w38 = w25[0];
  w19 = w25[1];
  w53 = w25[2];
  w6 = w25[3];
  /* #360: @55 = (@55+@38) */
  w55 += w38;
  /* #361: @55 = (@55+@20) */
  w55 += w20;
  /* #362: @59 = (@59-@56) */
  w59 -= w56;
  /* #363: @59 = (@59+@58) */
  w59 += w58;
  /* #364: @59 = (@59-@19) */
  w59 -= w19;
  /* #365: @59 = (@59+@4) */
  w59 += w4;
  /* #366: @2 = (@2-@39) */
  w2 -= w39;
  /* #367: @2 = (@2+@57) */
  w2 += w57;
  /* #368: @2 = (@2-@53) */
  w2 -= w53;
  /* #369: @2 = (@2+@11) */
  w2 += w11;
  /* #370: @3 = (@3+@14) */
  w3 += w14;
  /* #371: @3 = (@3-@0) */
  w3 -= w0;
  /* #372: @3 = (@3-@6) */
  w3 -= w6;
  /* #373: @3 = (@3+@7) */
  w3 += w7;
  /* #374: @15 = vertcat(@12, @17, @5, @9, @13, @40, @55, @59, @2, @3, @10, @37, @8) */
  rr=w15;
  *rr++ = w12;
  *rr++ = w17;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w55;
  *rr++ = w59;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w10;
  *rr++ = w37;
  *rr++ = w8;
  /* #375: @60 = @15[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s8, rr=w60, ss=w15; cii!=casadi_s8+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #376: (@41[3, 4, 5, 13, 14, 15, 16] = @60) */
  for (cii=casadi_s12, rr=w41, ss=w60; cii!=casadi_s12+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #377: @60 = @15[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s8, rr=w60, ss=w15; cii!=casadi_s8+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #378: (@41[1, 4, 7, 10, 14, 18, 22] = @60) */
  for (cii=casadi_s13, rr=w41, ss=w60; cii!=casadi_s13+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #379: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #380: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #381: @12 = @18[0] */
  for (rr=(&w12), ss=(&w18)+0; ss!=(&w18)+1; ss+=1) *rr++ = *ss;
  /* #382: @12 = (-@12) */
  w12 = (- w12 );
  /* #383: @18 = @12' */
  casadi_copy((&w12), 1, (&w18));
  /* #384: @31 = mac(@18,@22,@31) */
  casadi_mtimes((&w18), casadi_s14, w22, casadi_s1, w31, casadi_s0, w, 0);
  /* #385: @31 = @31' */
  /* #386: @21 = zeros(1x3) */
  casadi_clear(w21, 3);
  /* #387: @12 = @12' */
  /* #388: @21 = mac(@12,@32,@21) */
  casadi_mtimes((&w12), casadi_s14, w32, casadi_s1, w21, casadi_s0, w, 0);
  /* #389: @21 = @21' */
  /* #390: @31 = (@31+@21) */
  for (i=0, rr=w31, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #391: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #392: (@15[:3] += @31) */
  for (rr=w15+0, ss=w31; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #393: {@12, @18, @17, @5, @9, @13, @40, @55, @59, @2, @3, @10, @37} = vertsplit(@15) */
  w12 = w15[0];
  w18 = w15[1];
  w17 = w15[2];
  w5 = w15[3];
  w9 = w15[4];
  w13 = w15[5];
  w40 = w15[6];
  w55 = w15[7];
  w59 = w15[8];
  w2 = w15[9];
  w3 = w15[10];
  w10 = w15[11];
  w37 = w15[12];
  /* #394: @28 = zeros(4x4) */
  casadi_clear(w28, 16);
  /* #395: @28 = mac(@50,@27,@28) */
  for (i=0, rr=w28; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w50+j, tt=w27+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #396: @51 = @28' */
  for (i=0, rr=w51, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #397: {@50, @25, @23, @35} = horzsplit(@51) */
  casadi_copy(w51, 4, w50);
  casadi_copy(w51+4, 4, w25);
  casadi_copy(w51+8, 4, w23);
  casadi_copy(w51+12, 4, w35);
  /* #398: @35 = @35' */
  /* #399: {@8, @7, @6, @0} = horzsplit(@35) */
  w8 = w35[0];
  w7 = w35[1];
  w6 = w35[2];
  w0 = w35[3];
  /* #400: @23 = @23' */
  /* #401: {@14, @11, @53, @57} = horzsplit(@23) */
  w14 = w23[0];
  w11 = w23[1];
  w53 = w23[2];
  w57 = w23[3];
  /* #402: @0 = (@0+@53) */
  w0 += w53;
  /* #403: @25 = @25' */
  /* #404: {@53, @39, @4, @19} = horzsplit(@25) */
  w53 = w25[0];
  w39 = w25[1];
  w4 = w25[2];
  w19 = w25[3];
  /* #405: @0 = (@0+@39) */
  w0 += w39;
  /* #406: @50 = @50' */
  /* #407: {@39, @58, @56, @20} = horzsplit(@50) */
  w39 = w50[0];
  w58 = w50[1];
  w56 = w50[2];
  w20 = w50[3];
  /* #408: @0 = (@0+@39) */
  w0 += w39;
  /* #409: @0 = (@0+@40) */
  w0 += w40;
  /* #410: @6 = (@6-@57) */
  w6 -= w57;
  /* #411: @6 = (@6+@53) */
  w6 += w53;
  /* #412: @6 = (@6-@58) */
  w6 -= w58;
  /* #413: @6 = (@6+@55) */
  w6 += w55;
  /* #414: @14 = (@14-@7) */
  w14 -= w7;
  /* #415: @14 = (@14+@19) */
  w14 += w19;
  /* #416: @14 = (@14-@56) */
  w14 -= w56;
  /* #417: @14 = (@14+@59) */
  w14 += w59;
  /* #418: @8 = (@8+@11) */
  w8 += w11;
  /* #419: @8 = (@8-@4) */
  w8 -= w4;
  /* #420: @8 = (@8-@20) */
  w8 -= w20;
  /* #421: @8 = (@8+@2) */
  w8 += w2;
  /* #422: @15 = vertcat(@12, @18, @17, @5, @9, @13, @0, @6, @14, @8, @3, @10, @37) */
  rr=w15;
  *rr++ = w12;
  *rr++ = w18;
  *rr++ = w17;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w13;
  *rr++ = w0;
  *rr++ = w6;
  *rr++ = w14;
  *rr++ = w8;
  *rr++ = w3;
  *rr++ = w10;
  *rr++ = w37;
  /* #423: @60 = @15[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s8, rr=w60, ss=w15; cii!=casadi_s8+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #424: (@41[6, 7, 8, 17, 18, 19, 20] = @60) */
  for (cii=casadi_s15, rr=w41, ss=w60; cii!=casadi_s15+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #425: @60 = @15[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s8, rr=w60, ss=w15; cii!=casadi_s8+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #426: (@41[2, 5, 8, 11, 15, 19, 23] = @60) */
  for (cii=casadi_s16, rr=w41, ss=w60; cii!=casadi_s16+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #427: @33 = 00 */
  /* #428: @43 = 00 */
  /* #429: @46 = 00 */
  /* #430: @44 = 00 */
  /* #431: @45 = 00 */
  /* #432: @47 = 00 */
  /* #433: @51 = zeros(4x4) */
  casadi_clear(w51, 16);
  /* #434: @51 = mac(@26,@27,@51) */
  for (i=0, rr=w51; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #435: @28 = @51' */
  for (i=0, rr=w28, cs=w51; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #436: {@26, @27, @50, @25} = horzsplit(@28) */
  casadi_copy(w28, 4, w26);
  casadi_copy(w28+4, 4, w27);
  casadi_copy(w28+8, 4, w50);
  casadi_copy(w28+12, 4, w25);
  /* #437: @25 = @25' */
  /* #438: {@12, @18, @17, @5} = horzsplit(@25) */
  w12 = w25[0];
  w18 = w25[1];
  w17 = w25[2];
  w5 = w25[3];
  /* #439: @50 = @50' */
  /* #440: {@9, @13, @0, @6} = horzsplit(@50) */
  w9 = w50[0];
  w13 = w50[1];
  w0 = w50[2];
  w6 = w50[3];
  /* #441: @5 = (@5+@0) */
  w5 += w0;
  /* #442: @27 = @27' */
  /* #443: {@0, @14, @8, @3} = horzsplit(@27) */
  w0 = w27[0];
  w14 = w27[1];
  w8 = w27[2];
  w3 = w27[3];
  /* #444: @5 = (@5+@14) */
  w5 += w14;
  /* #445: @26 = @26' */
  /* #446: {@14, @10, @37, @2} = horzsplit(@26) */
  w14 = w26[0];
  w10 = w26[1];
  w37 = w26[2];
  w2 = w26[3];
  /* #447: @5 = (@5+@14) */
  w5 += w14;
  /* #448: @17 = (@17-@6) */
  w17 -= w6;
  /* #449: @17 = (@17+@0) */
  w17 += w0;
  /* #450: @17 = (@17-@10) */
  w17 -= w10;
  /* #451: @9 = (@9-@18) */
  w9 -= w18;
  /* #452: @9 = (@9+@3) */
  w9 += w3;
  /* #453: @9 = (@9-@37) */
  w9 -= w37;
  /* #454: @12 = (@12+@13) */
  w12 += w13;
  /* #455: @12 = (@12-@8) */
  w12 -= w8;
  /* #456: @12 = (@12-@2) */
  w12 -= w2;
  /* #457: @61 = 00 */
  /* #458: @62 = 00 */
  /* #459: @63 = 00 */
  /* #460: @26 = vertcat(@33, @43, @46, @44, @45, @47, @5, @17, @9, @12, @61, @62, @63) */
  rr=w26;
  *rr++ = w5;
  *rr++ = w17;
  *rr++ = w9;
  *rr++ = w12;
  /* #461: @27 = @26[:4] */
  for (rr=w27, ss=w26+0; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #462: (@41[21:25] = @27) */
  for (rr=w41+21, ss=w27; rr!=w41+25; rr+=1) *rr = *ss++;
  /* #463: @27 = @26[:4] */
  for (rr=w27, ss=w26+0; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #464: (@41[12:28:4] = @27) */
  for (rr=w41+12, ss=w27; rr!=w41+28; rr+=4) *rr = *ss++;
  /* #465: @64 = @41' */
  casadi_trans(w41,casadi_s17, w64, casadi_s17, iw);
  /* #466: output[2][0] = @64 */
  casadi_copy(w64, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s19;
    case 2: return casadi_s19;
    case 3: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s20;
    case 1: return casadi_s18;
    case 2: return casadi_s17;
    case 3: return casadi_s19;
    case 4: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 257;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
