/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* quadrotor_cost_ext_cost_e_fun_jac:(i0[13],i1[],i2[],i3[13])->(o0,o1[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+5, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+21, *w16=w+34, w17, w18, w19, w20, *w21=w+41, *w22=w+44, *w23=w+53, *w24=w+57, *w25=w+61, *w26=w+65, *w27=w+69, *w28=w+73, *w29=w+89, *w30=w+105, *w31=w+108, *w32=w+111, w33, w34, w35;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #16: @16 = @15[:3] */
  for (rr=w16, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #17: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #18: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #19: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #20: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #21: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #22: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #23: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #24: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #25: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #26: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #27: @18 = input[0][10] */
  w18 = arg[0] ? arg[0][10] : 0;
  /* #28: @19 = input[0][11] */
  w19 = arg[0] ? arg[0][11] : 0;
  /* #29: @20 = input[0][12] */
  w20 = arg[0] ? arg[0][12] : 0;
  /* #30: @15 = vertcat(@2, @3, @4, @5, @6, @7, @12, @13, @14, @17, @18, @19, @20) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #31: @21 = @15[:3] */
  for (rr=w21, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #32: @16 = (@16-@21) */
  for (i=0, rr=w16, cs=w21; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @21 = @16' */
  casadi_copy(w16, 3, w21);
  /* #34: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #35: @2 = 1.5 */
  w2 = 1.5000000000000000e+00;
  /* #36: (@22[0] = @2) */
  for (rr=w22+0, ss=(&w2); rr!=w22+1; rr+=1) *rr = *ss++;
  /* #37: @2 = 1.5 */
  w2 = 1.5000000000000000e+00;
  /* #38: (@22[4] = @2) */
  for (rr=w22+4, ss=(&w2); rr!=w22+5; rr+=1) *rr = *ss++;
  /* #39: @2 = 10 */
  w2 = 10.;
  /* #40: (@22[8] = @2) */
  for (rr=w22+8, ss=(&w2); rr!=w22+9; rr+=1) *rr = *ss++;
  /* #41: @1 = mac(@21,@22,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #42: @0 = mac(@1,@16,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #43: @2 = 1 */
  w2 = 1.;
  /* #44: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #45: @3 = (-@13) */
  w3 = (- w13 );
  /* #46: @4 = (-@14) */
  w4 = (- w14 );
  /* #47: @5 = (-@17) */
  w5 = (- w17 );
  /* #48: @24 = horzcat(@12, @3, @4, @5) */
  rr=w24;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #49: @24 = @24' */
  /* #50: @3 = (-@17) */
  w3 = (- w17 );
  /* #51: @25 = horzcat(@13, @12, @3, @14) */
  rr=w25;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w14;
  /* #52: @25 = @25' */
  /* #53: @3 = (-@13) */
  w3 = (- w13 );
  /* #54: @26 = horzcat(@14, @17, @12, @3) */
  rr=w26;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w12;
  *rr++ = w3;
  /* #55: @26 = @26' */
  /* #56: @14 = (-@14) */
  w14 = (- w14 );
  /* #57: @27 = horzcat(@17, @14, @13, @12) */
  rr=w27;
  *rr++ = w17;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w12;
  /* #58: @27 = @27' */
  /* #59: @28 = horzcat(@24, @25, @26, @27) */
  rr=w28;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  /* #60: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #61: @9 = (-@9) */
  w9 = (- w9 );
  /* #62: @10 = (-@10) */
  w10 = (- w10 );
  /* #63: @11 = (-@11) */
  w11 = (- w11 );
  /* #64: @24 = vertcat(@8, @9, @10, @11) */
  rr=w24;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #65: @23 = mac(@29,@24,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w29+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #66: @8 = @23[0] */
  for (rr=(&w8), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #67: @2 = (@2-@8) */
  w2 -= w8;
  /* #68: @8 = 0 */
  w8 = 0.;
  /* #69: @21 = @23[1:4] */
  for (rr=w21, ss=w23+1; ss!=w23+4; ss+=1) *rr++ = *ss;
  /* #70: @30 = @21' */
  casadi_copy(w21, 3, w30);
  /* #71: @31 = @23[1:4] */
  for (rr=w31, ss=w23+1; ss!=w23+4; ss+=1) *rr++ = *ss;
  /* #72: @8 = mac(@30,@31,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #73: @2 = (@2+@8) */
  w2 += w8;
  /* #74: @0 = (@0+@2) */
  w0 += w2;
  /* #75: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #76: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #77: @1 = @1' */
  /* #78: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #79: @16 = @16' */
  /* #80: @32 = @22' */
  for (i=0, rr=w32, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #81: @30 = mac(@16,@32,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #82: @30 = @30' */
  /* #83: @1 = (@1+@30) */
  for (i=0, rr=w1, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #84: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #85: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #86: {@0, @2, @8, @9, @10, @11, @17, @14, @13, @12, @3, @4, @5} = vertsplit(@15) */
  w0 = w15[0];
  w2 = w15[1];
  w8 = w15[2];
  w9 = w15[3];
  w10 = w15[4];
  w11 = w15[5];
  w17 = w15[6];
  w14 = w15[7];
  w13 = w15[8];
  w12 = w15[9];
  w3 = w15[10];
  w4 = w15[11];
  w5 = w15[12];
  /* #87: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #88: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #89: output[1][2] = @8 */
  if (res[1]) res[1][2] = w8;
  /* #90: output[1][3] = @9 */
  if (res[1]) res[1][3] = w9;
  /* #91: output[1][4] = @10 */
  if (res[1]) res[1][4] = w10;
  /* #92: output[1][5] = @11 */
  if (res[1]) res[1][5] = w11;
  /* #93: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #94: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #95: (@23[1:4] += @21) */
  for (rr=w23+1, ss=w21; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #96: (@23[1:4] += @31) */
  for (rr=w23+1, ss=w31; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #97: @11 = -1 */
  w11 = -1.;
  /* #98: (@23[0] += @11) */
  for (rr=w23+0, ss=(&w11); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #99: @24 = @24' */
  /* #100: @29 = mac(@23,@24,@29) */
  for (i=0, rr=w29; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w24+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #101: @28 = @29' */
  for (i=0, rr=w28, cs=w29; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #102: {@23, @24, @25, @26} = horzsplit(@28) */
  casadi_copy(w28, 4, w23);
  casadi_copy(w28+4, 4, w24);
  casadi_copy(w28+8, 4, w25);
  casadi_copy(w28+12, 4, w26);
  /* #103: @26 = @26' */
  /* #104: {@11, @10, @9, @8} = horzsplit(@26) */
  w11 = w26[0];
  w10 = w26[1];
  w9 = w26[2];
  w8 = w26[3];
  /* #105: @25 = @25' */
  /* #106: {@2, @0, @6, @7} = horzsplit(@25) */
  w2 = w25[0];
  w0 = w25[1];
  w6 = w25[2];
  w7 = w25[3];
  /* #107: @8 = (@8+@6) */
  w8 += w6;
  /* #108: @24 = @24' */
  /* #109: {@6, @18, @19, @20} = horzsplit(@24) */
  w6 = w24[0];
  w18 = w24[1];
  w19 = w24[2];
  w20 = w24[3];
  /* #110: @8 = (@8+@18) */
  w8 += w18;
  /* #111: @23 = @23' */
  /* #112: {@18, @33, @34, @35} = horzsplit(@23) */
  w18 = w23[0];
  w33 = w23[1];
  w34 = w23[2];
  w35 = w23[3];
  /* #113: @8 = (@8+@18) */
  w8 += w18;
  /* #114: @8 = (@8+@17) */
  w8 += w17;
  /* #115: output[1][6] = @8 */
  if (res[1]) res[1][6] = w8;
  /* #116: @9 = (@9-@7) */
  w9 -= w7;
  /* #117: @9 = (@9+@6) */
  w9 += w6;
  /* #118: @9 = (@9-@33) */
  w9 -= w33;
  /* #119: @9 = (@9+@14) */
  w9 += w14;
  /* #120: output[1][7] = @9 */
  if (res[1]) res[1][7] = w9;
  /* #121: @2 = (@2-@10) */
  w2 -= w10;
  /* #122: @2 = (@2+@20) */
  w2 += w20;
  /* #123: @2 = (@2-@34) */
  w2 -= w34;
  /* #124: @2 = (@2+@13) */
  w2 += w13;
  /* #125: output[1][8] = @2 */
  if (res[1]) res[1][8] = w2;
  /* #126: @11 = (@11+@0) */
  w11 += w0;
  /* #127: @11 = (@11-@19) */
  w11 -= w19;
  /* #128: @11 = (@11-@35) */
  w11 -= w35;
  /* #129: @11 = (@11+@12) */
  w11 += w12;
  /* #130: output[1][9] = @11 */
  if (res[1]) res[1][9] = w11;
  /* #131: output[1][10] = @3 */
  if (res[1]) res[1][10] = w3;
  /* #132: output[1][11] = @4 */
  if (res[1]) res[1][11] = w4;
  /* #133: output[1][12] = @5 */
  if (res[1]) res[1][12] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 123;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
