/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

/* f_error:(i0[4])->(o0[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, *w3=w+6;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #4: @3 = (@0?@1:0) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++)  = (w0?(*cs++):0);
  /* #5: @0 = (!@0) */
  w0 = (! w0 );
  /* #6: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #7: @1 = (@0?@1:0) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0?(*cs++):0);
  /* #8: @3 = (@3+@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #9: output[0][0] = @3 */
  casadi_copy(w3, 4, res[0]);
  return 0;
}

/* adj1_f_error:(i0[4],out_o0[4x1,0nz],adj_o0[4])->(adj_i0[4]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, *w3=w+6;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #4: @2 = 1 */
  w2 = 1.;
  /* #5: @2 = (@0?@2:0) */
  w2  = (w0?w2:0);
  /* #6: @1 = input[2][0] */
  casadi_copy(arg[2], 4, w1);
  /* #7: @3 = (@2*@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #8: @0 = (!@0) */
  w0 = (! w0 );
  /* #9: @2 = 1 */
  w2 = 1.;
  /* #10: @0 = (@0?@2:0) */
  w0  = (w0?w2:0);
  /* #11: @1 = (@0*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #12: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) -= (*cs++);
  /* #13: output[0][0] = @3 */
  casadi_copy(w3, 4, res[0]);
  return 0;
}

/* quadrotor_cost_ext_cost_fun_jac:(i0[13],i1[4],i2[],i3[13])->(o0,o1[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+2, *rr, *ss, *tt;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real w0, *w1=w+11, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+27, *w16=w+40, w17, w18, w19, w20, *w21=w+47, *w22=w+50, *w23=w+59, *w24=w+63, *w25=w+67, *w26=w+71, *w27=w+87, *w28=w+91, *w29=w+95, *w30=w+99, *w31=w+103, *w32=w+119, *w33=w+135, *w34=w+138, *w35=w+141, w37, w38, w39;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #16: @16 = @15[:3] */
  for (rr=w16, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #17: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #18: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #19: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #20: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #21: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #22: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #23: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #24: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #25: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #26: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #27: @18 = input[0][10] */
  w18 = arg[0] ? arg[0][10] : 0;
  /* #28: @19 = input[0][11] */
  w19 = arg[0] ? arg[0][11] : 0;
  /* #29: @20 = input[0][12] */
  w20 = arg[0] ? arg[0][12] : 0;
  /* #30: @15 = vertcat(@2, @3, @4, @5, @6, @7, @12, @13, @14, @17, @18, @19, @20) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #31: @21 = @15[:3] */
  for (rr=w21, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #32: @16 = (@16-@21) */
  for (i=0, rr=w16, cs=w21; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @21 = @16' */
  casadi_copy(w16, 3, w21);
  /* #34: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #35: @2 = 1.5 */
  w2 = 1.5000000000000000e+00;
  /* #36: (@22[0] = @2) */
  for (rr=w22+0, ss=(&w2); rr!=w22+1; rr+=1) *rr = *ss++;
  /* #37: @2 = 1.5 */
  w2 = 1.5000000000000000e+00;
  /* #38: (@22[4] = @2) */
  for (rr=w22+4, ss=(&w2); rr!=w22+5; rr+=1) *rr = *ss++;
  /* #39: @2 = 15 */
  w2 = 15.;
  /* #40: (@22[8] = @2) */
  for (rr=w22+8, ss=(&w2); rr!=w22+9; rr+=1) *rr = *ss++;
  /* #41: @1 = mac(@21,@22,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #42: @0 = mac(@1,@16,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #43: @2 = 0 */
  w2 = 0.;
  /* #44: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #45: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #46: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #47: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #48: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #49: @24 = vertcat(@3, @4, @5, @6) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #50: @25 = @24' */
  casadi_copy(w24, 4, w25);
  /* #51: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #52: @3 = 0.0505051 */
  w3 = 5.0505050505050504e-02;
  /* #53: (@26[0] = @3) */
  for (rr=w26+0, ss=(&w3); rr!=w26+1; rr+=1) *rr = *ss++;
  /* #54: @3 = 200 */
  w3 = 200.;
  /* #55: (@26[5] = @3) */
  for (rr=w26+5, ss=(&w3); rr!=w26+6; rr+=1) *rr = *ss++;
  /* #56: @3 = 200 */
  w3 = 200.;
  /* #57: (@26[10] = @3) */
  for (rr=w26+10, ss=(&w3); rr!=w26+11; rr+=1) *rr = *ss++;
  /* #58: @3 = 200 */
  w3 = 200.;
  /* #59: (@26[15] = @3) */
  for (rr=w26+15, ss=(&w3); rr!=w26+16; rr+=1) *rr = *ss++;
  /* #60: @23 = mac(@25,@26,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #61: @2 = mac(@23,@24,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #62: @0 = (@0+@2) */
  w0 += w2;
  /* #63: @2 = 1 */
  w2 = 1.;
  /* #64: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #65: @3 = (-@13) */
  w3 = (- w13 );
  /* #66: @4 = (-@14) */
  w4 = (- w14 );
  /* #67: @5 = (-@17) */
  w5 = (- w17 );
  /* #68: @27 = horzcat(@12, @3, @4, @5) */
  rr=w27;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #69: @27 = @27' */
  /* #70: @3 = (-@17) */
  w3 = (- w17 );
  /* #71: @28 = horzcat(@13, @12, @3, @14) */
  rr=w28;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w14;
  /* #72: @28 = @28' */
  /* #73: @3 = (-@13) */
  w3 = (- w13 );
  /* #74: @29 = horzcat(@14, @17, @12, @3) */
  rr=w29;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w12;
  *rr++ = w3;
  /* #75: @29 = @29' */
  /* #76: @14 = (-@14) */
  w14 = (- w14 );
  /* #77: @30 = horzcat(@17, @14, @13, @12) */
  rr=w30;
  *rr++ = w17;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w12;
  /* #78: @30 = @30' */
  /* #79: @31 = horzcat(@27, @28, @29, @30) */
  rr=w31;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #80: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #81: @9 = (-@9) */
  w9 = (- w9 );
  /* #82: @10 = (-@10) */
  w10 = (- w10 );
  /* #83: @11 = (-@11) */
  w11 = (- w11 );
  /* #84: @27 = vertcat(@8, @9, @10, @11) */
  rr=w27;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #85: @25 = mac(@32,@27,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w32+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #86: @28 = f_error(@25) */
  arg1[0]=w25;
  res1[0]=w28;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #87: @8 = @28[0] */
  for (rr=(&w8), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #88: @2 = (@2-@8) */
  w2 -= w8;
  /* #89: @8 = 0 */
  w8 = 0.;
  /* #90: @21 = @28[1:4] */
  for (rr=w21, ss=w28+1; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #91: @33 = @21' */
  casadi_copy(w21, 3, w33);
  /* #92: @34 = @28[1:4] */
  for (rr=w34, ss=w28+1; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #93: @8 = mac(@33,@34,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #94: @2 = (@2+@8) */
  w2 += w8;
  /* #95: @0 = (@0+@2) */
  w0 += w2;
  /* #96: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #97: @23 = @23' */
  /* #98: @28 = zeros(1x4) */
  casadi_clear(w28, 4);
  /* #99: @24 = @24' */
  /* #100: @32 = @26' */
  for (i=0, rr=w32, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #101: @28 = mac(@24,@32,@28) */
  for (i=0, rr=w28; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w32+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #102: @28 = @28' */
  /* #103: @23 = (@23+@28) */
  for (i=0, rr=w23, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #104: {@0, @2, @8, @9} = vertsplit(@23) */
  w0 = w23[0];
  w2 = w23[1];
  w8 = w23[2];
  w9 = w23[3];
  /* #105: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #106: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #107: output[1][2] = @8 */
  if (res[1]) res[1][2] = w8;
  /* #108: output[1][3] = @9 */
  if (res[1]) res[1][3] = w9;
  /* #109: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #110: @1 = @1' */
  /* #111: @33 = zeros(1x3) */
  casadi_clear(w33, 3);
  /* #112: @16 = @16' */
  /* #113: @35 = @22' */
  for (i=0, rr=w35, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #114: @33 = mac(@16,@35,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #115: @33 = @33' */
  /* #116: @1 = (@1+@33) */
  for (i=0, rr=w1, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #117: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #118: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #119: {@9, @8, @2, @0, @10, @11, @17, @14, @13, @12, @3, @4, @5} = vertsplit(@15) */
  w9 = w15[0];
  w8 = w15[1];
  w2 = w15[2];
  w0 = w15[3];
  w10 = w15[4];
  w11 = w15[5];
  w17 = w15[6];
  w14 = w15[7];
  w13 = w15[8];
  w12 = w15[9];
  w3 = w15[10];
  w4 = w15[11];
  w5 = w15[12];
  /* #120: output[1][4] = @9 */
  if (res[1]) res[1][4] = w9;
  /* #121: output[1][5] = @8 */
  if (res[1]) res[1][5] = w8;
  /* #122: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #123: output[1][7] = @0 */
  if (res[1]) res[1][7] = w0;
  /* #124: output[1][8] = @10 */
  if (res[1]) res[1][8] = w10;
  /* #125: output[1][9] = @11 */
  if (res[1]) res[1][9] = w11;
  /* #126: @32 = zeros(4x4) */
  casadi_clear(w32, 16);
  /* #127: @36 = zeros(4x1,0nz) */
  /* #128: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #129: (@23[1:4] += @21) */
  for (rr=w23+1, ss=w21; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #130: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #131: @11 = -1 */
  w11 = -1.;
  /* #132: (@23[0] += @11) */
  for (rr=w23+0, ss=(&w11); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #133: @28 = adj1_f_error(@25, @36, @23) */
  arg1[0]=w25;
  arg1[1]=0;
  arg1[2]=w23;
  res1[0]=w28;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #134: @27 = @27' */
  /* #135: @32 = mac(@28,@27,@32) */
  for (i=0, rr=w32; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w27+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #136: @26 = @32' */
  for (i=0, rr=w26, cs=w32; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #137: {@28, @27, @25, @23} = horzsplit(@26) */
  casadi_copy(w26, 4, w28);
  casadi_copy(w26+4, 4, w27);
  casadi_copy(w26+8, 4, w25);
  casadi_copy(w26+12, 4, w23);
  /* #138: @23 = @23' */
  /* #139: {@11, @10, @0, @2} = horzsplit(@23) */
  w11 = w23[0];
  w10 = w23[1];
  w0 = w23[2];
  w2 = w23[3];
  /* #140: @25 = @25' */
  /* #141: {@8, @9, @6, @7} = horzsplit(@25) */
  w8 = w25[0];
  w9 = w25[1];
  w6 = w25[2];
  w7 = w25[3];
  /* #142: @2 = (@2+@6) */
  w2 += w6;
  /* #143: @27 = @27' */
  /* #144: {@6, @18, @19, @20} = horzsplit(@27) */
  w6 = w27[0];
  w18 = w27[1];
  w19 = w27[2];
  w20 = w27[3];
  /* #145: @2 = (@2+@18) */
  w2 += w18;
  /* #146: @28 = @28' */
  /* #147: {@18, @37, @38, @39} = horzsplit(@28) */
  w18 = w28[0];
  w37 = w28[1];
  w38 = w28[2];
  w39 = w28[3];
  /* #148: @2 = (@2+@18) */
  w2 += w18;
  /* #149: @2 = (@2+@17) */
  w2 += w17;
  /* #150: output[1][10] = @2 */
  if (res[1]) res[1][10] = w2;
  /* #151: @0 = (@0-@7) */
  w0 -= w7;
  /* #152: @0 = (@0+@6) */
  w0 += w6;
  /* #153: @0 = (@0-@37) */
  w0 -= w37;
  /* #154: @0 = (@0+@14) */
  w0 += w14;
  /* #155: output[1][11] = @0 */
  if (res[1]) res[1][11] = w0;
  /* #156: @8 = (@8-@10) */
  w8 -= w10;
  /* #157: @8 = (@8+@20) */
  w8 += w20;
  /* #158: @8 = (@8-@38) */
  w8 -= w38;
  /* #159: @8 = (@8+@13) */
  w8 += w13;
  /* #160: output[1][12] = @8 */
  if (res[1]) res[1][12] = w8;
  /* #161: @11 = (@11+@9) */
  w11 += w9;
  /* #162: @11 = (@11-@19) */
  w11 -= w19;
  /* #163: @11 = (@11-@39) */
  w11 -= w39;
  /* #164: @11 = (@11+@12) */
  w11 += w12;
  /* #165: output[1][13] = @11 */
  if (res[1]) res[1][13] = w11;
  /* #166: output[1][14] = @3 */
  if (res[1]) res[1][14] = w3;
  /* #167: output[1][15] = @4 */
  if (res[1]) res[1][15] = w4;
  /* #168: output[1][16] = @5 */
  if (res[1]) res[1][16] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 153;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
