/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s6[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s8[11] = {0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13};
static const casadi_int casadi_s9[11] = {0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28};
static const casadi_int casadi_s10[11] = {0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37};
static const casadi_int casadi_s11[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s12[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[11] = {4, 4, 0, 1, 2, 3, 4, 1, 0, 3, 2};
static const casadi_int casadi_s14[11] = {4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32};
static const casadi_int casadi_s15[11] = {1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38};
static const casadi_int casadi_s16[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s17[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s18[11] = {4, 4, 0, 1, 2, 3, 4, 2, 3, 0, 1};
static const casadi_int casadi_s19[11] = {8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36};
static const casadi_int casadi_s20[11] = {2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39};
static const casadi_int casadi_s21[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s22[11] = {4, 4, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s23[61] = {17, 17, 0, 4, 8, 12, 16, 19, 22, 25, 25, 25, 25, 29, 33, 37, 41, 41, 41, 41, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13};
static const casadi_int casadi_s24[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s25[3] = {0, 0, 0};
static const casadi_int casadi_s26[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s27[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s28[20] = {0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* quadrotor_cost_ext_cost_0_fun_jac_hess:(i0[13],i1[4],i2[],i3[13])->(o0,o1[17],o2[17x17,41nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+5, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+21, *w16=w+34, w17, w18, w19, w20, *w21=w+41, *w22=w+44, *w23=w+53, *w24=w+57, *w25=w+61, *w26=w+65, *w27=w+81, *w28=w+85, *w29=w+89, *w30=w+93, *w31=w+97, *w32=w+113, *w33=w+129, *w34=w+132, *w35=w+135, *w36=w+144, w37, w38, w39, w40, *w41=w+164, *w42=w+205, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, *w57=w+224, *w58=w+241, *w59=w+252, *w66=w+254, *w67=w+262, *w68=w+270;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #16: @16 = @15[:3] */
  for (rr=w16, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #17: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #18: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #19: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #20: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #21: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #22: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #23: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #24: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #25: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #26: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #27: @18 = input[0][10] */
  w18 = arg[0] ? arg[0][10] : 0;
  /* #28: @19 = input[0][11] */
  w19 = arg[0] ? arg[0][11] : 0;
  /* #29: @20 = input[0][12] */
  w20 = arg[0] ? arg[0][12] : 0;
  /* #30: @15 = vertcat(@2, @3, @4, @5, @6, @7, @12, @13, @14, @17, @18, @19, @20) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #31: @21 = @15[:3] */
  for (rr=w21, ss=w15+0; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #32: @16 = (@16-@21) */
  for (i=0, rr=w16, cs=w21; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @21 = @16' */
  casadi_copy(w16, 3, w21);
  /* #34: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #35: @2 = 1 */
  w2 = 1.;
  /* #36: (@22[0] = @2) */
  for (rr=w22+0, ss=(&w2); rr!=w22+1; rr+=1) *rr = *ss++;
  /* #37: @2 = 1 */
  w2 = 1.;
  /* #38: (@22[4] = @2) */
  for (rr=w22+4, ss=(&w2); rr!=w22+5; rr+=1) *rr = *ss++;
  /* #39: @2 = 10 */
  w2 = 10.;
  /* #40: (@22[8] = @2) */
  for (rr=w22+8, ss=(&w2); rr!=w22+9; rr+=1) *rr = *ss++;
  /* #41: @1 = mac(@21,@22,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #42: @0 = mac(@1,@16,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #43: @2 = 0.8 */
  w2 = 8.0000000000000004e-01;
  /* #44: @3 = 0 */
  w3 = 0.;
  /* #45: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #46: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #47: @5 = input[1][1] */
  w5 = arg[1] ? arg[1][1] : 0;
  /* #48: @6 = input[1][2] */
  w6 = arg[1] ? arg[1][2] : 0;
  /* #49: @7 = input[1][3] */
  w7 = arg[1] ? arg[1][3] : 0;
  /* #50: @24 = vertcat(@4, @5, @6, @7) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #51: @25 = @24' */
  casadi_copy(w24, 4, w25);
  /* #52: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #53: @4 = 0.0505051 */
  w4 = 5.0505050505050504e-02;
  /* #54: (@26[0] = @4) */
  for (rr=w26+0, ss=(&w4); rr!=w26+1; rr+=1) *rr = *ss++;
  /* #55: @4 = 100 */
  w4 = 100.;
  /* #56: (@26[5] = @4) */
  for (rr=w26+5, ss=(&w4); rr!=w26+6; rr+=1) *rr = *ss++;
  /* #57: @4 = 100 */
  w4 = 100.;
  /* #58: (@26[10] = @4) */
  for (rr=w26+10, ss=(&w4); rr!=w26+11; rr+=1) *rr = *ss++;
  /* #59: @4 = 100 */
  w4 = 100.;
  /* #60: (@26[15] = @4) */
  for (rr=w26+15, ss=(&w4); rr!=w26+16; rr+=1) *rr = *ss++;
  /* #61: @23 = mac(@25,@26,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #62: @3 = mac(@23,@24,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #63: @2 = (@2*@3) */
  w2 *= w3;
  /* #64: @0 = (@0+@2) */
  w0 += w2;
  /* #65: @2 = 1 */
  w2 = 1.;
  /* #66: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #67: @3 = (-@13) */
  w3 = (- w13 );
  /* #68: @4 = (-@14) */
  w4 = (- w14 );
  /* #69: @5 = (-@17) */
  w5 = (- w17 );
  /* #70: @27 = horzcat(@12, @3, @4, @5) */
  rr=w27;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #71: @27 = @27' */
  /* #72: @3 = (-@17) */
  w3 = (- w17 );
  /* #73: @28 = horzcat(@13, @12, @3, @14) */
  rr=w28;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w3;
  *rr++ = w14;
  /* #74: @28 = @28' */
  /* #75: @3 = (-@13) */
  w3 = (- w13 );
  /* #76: @29 = horzcat(@14, @17, @12, @3) */
  rr=w29;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w12;
  *rr++ = w3;
  /* #77: @29 = @29' */
  /* #78: @14 = (-@14) */
  w14 = (- w14 );
  /* #79: @30 = horzcat(@17, @14, @13, @12) */
  rr=w30;
  *rr++ = w17;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w12;
  /* #80: @30 = @30' */
  /* #81: @31 = horzcat(@27, @28, @29, @30) */
  rr=w31;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #82: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #83: @9 = (-@9) */
  w9 = (- w9 );
  /* #84: @10 = (-@10) */
  w10 = (- w10 );
  /* #85: @11 = (-@11) */
  w11 = (- w11 );
  /* #86: @27 = vertcat(@8, @9, @10, @11) */
  rr=w27;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #87: @25 = mac(@32,@27,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w32+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #88: @8 = @25[0] */
  for (rr=(&w8), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #89: @2 = (@2-@8) */
  w2 -= w8;
  /* #90: @8 = sq(@2) */
  w8 = casadi_sq( w2 );
  /* #91: @9 = 0 */
  w9 = 0.;
  /* #92: @21 = @25[1:4] */
  for (rr=w21, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #93: @33 = @21' */
  casadi_copy(w21, 3, w33);
  /* #94: @34 = @25[1:4] */
  for (rr=w34, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #95: @9 = mac(@33,@34,@9) */
  for (i=0, rr=(&w9); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #96: @8 = (@8+@9) */
  w8 += w9;
  /* #97: @0 = (@0+@8) */
  w0 += w8;
  /* #98: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #99: @0 = 0.8 */
  w0 = 8.0000000000000004e-01;
  /* #100: @23 = @23' */
  /* #101: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #102: @25 = zeros(1x4) */
  casadi_clear(w25, 4);
  /* #103: @24 = @24' */
  /* #104: @24 = (@0*@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #105: @32 = @26' */
  for (i=0, rr=w32, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #106: @25 = mac(@24,@32,@25) */
  for (i=0, rr=w25; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w32+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #107: @25 = @25' */
  /* #108: @23 = (@23+@25) */
  for (i=0, rr=w23, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #109: {@8, @9, @10, @11} = vertsplit(@23) */
  w8 = w23[0];
  w9 = w23[1];
  w10 = w23[2];
  w11 = w23[3];
  /* #110: output[1][0] = @8 */
  if (res[1]) res[1][0] = w8;
  /* #111: output[1][1] = @9 */
  if (res[1]) res[1][1] = w9;
  /* #112: output[1][2] = @10 */
  if (res[1]) res[1][2] = w10;
  /* #113: output[1][3] = @11 */
  if (res[1]) res[1][3] = w11;
  /* #114: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #115: @1 = @1' */
  /* #116: @33 = zeros(1x3) */
  casadi_clear(w33, 3);
  /* #117: @16 = @16' */
  /* #118: @35 = @22' */
  for (i=0, rr=w35, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #119: @33 = mac(@16,@35,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #120: @33 = @33' */
  /* #121: @1 = (@1+@33) */
  for (i=0, rr=w1, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #122: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #123: (@15[:3] += @1) */
  for (rr=w15+0, ss=w1; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #124: {@11, @10, @9, @8, @17, @14, @13, @12, @3, @4, @5, @6, @7} = vertsplit(@15) */
  w11 = w15[0];
  w10 = w15[1];
  w9 = w15[2];
  w8 = w15[3];
  w17 = w15[4];
  w14 = w15[5];
  w13 = w15[6];
  w12 = w15[7];
  w3 = w15[8];
  w4 = w15[9];
  w5 = w15[10];
  w6 = w15[11];
  w7 = w15[12];
  /* #125: output[1][4] = @11 */
  if (res[1]) res[1][4] = w11;
  /* #126: output[1][5] = @10 */
  if (res[1]) res[1][5] = w10;
  /* #127: output[1][6] = @9 */
  if (res[1]) res[1][6] = w9;
  /* #128: output[1][7] = @8 */
  if (res[1]) res[1][7] = w8;
  /* #129: output[1][8] = @17 */
  if (res[1]) res[1][8] = w17;
  /* #130: output[1][9] = @14 */
  if (res[1]) res[1][9] = w14;
  /* #131: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #132: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #133: (@23[1:4] += @21) */
  for (rr=w23+1, ss=w21; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #134: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #135: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #136: @2 = (-@2) */
  w2 = (- w2 );
  /* #137: (@23[0] += @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #138: @25 = @27' */
  casadi_copy(w27, 4, w25);
  /* #139: @31 = mac(@23,@25,@31) */
  for (i=0, rr=w31; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #140: @36 = @31' */
  for (i=0, rr=w36, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #141: {@23, @24, @28, @29} = horzsplit(@36) */
  casadi_copy(w36, 4, w23);
  casadi_copy(w36+4, 4, w24);
  casadi_copy(w36+8, 4, w28);
  casadi_copy(w36+12, 4, w29);
  /* #142: @29 = @29' */
  /* #143: {@2, @14, @17, @8} = horzsplit(@29) */
  w2 = w29[0];
  w14 = w29[1];
  w17 = w29[2];
  w8 = w29[3];
  /* #144: @28 = @28' */
  /* #145: {@9, @10, @11, @18} = horzsplit(@28) */
  w9 = w28[0];
  w10 = w28[1];
  w11 = w28[2];
  w18 = w28[3];
  /* #146: @8 = (@8+@11) */
  w8 += w11;
  /* #147: @24 = @24' */
  /* #148: {@11, @19, @20, @37} = horzsplit(@24) */
  w11 = w24[0];
  w19 = w24[1];
  w20 = w24[2];
  w37 = w24[3];
  /* #149: @8 = (@8+@19) */
  w8 += w19;
  /* #150: @23 = @23' */
  /* #151: {@19, @38, @39, @40} = horzsplit(@23) */
  w19 = w23[0];
  w38 = w23[1];
  w39 = w23[2];
  w40 = w23[3];
  /* #152: @8 = (@8+@19) */
  w8 += w19;
  /* #153: @8 = (@8+@13) */
  w8 += w13;
  /* #154: output[1][10] = @8 */
  if (res[1]) res[1][10] = w8;
  /* #155: @17 = (@17-@18) */
  w17 -= w18;
  /* #156: @17 = (@17+@11) */
  w17 += w11;
  /* #157: @17 = (@17-@38) */
  w17 -= w38;
  /* #158: @17 = (@17+@12) */
  w17 += w12;
  /* #159: output[1][11] = @17 */
  if (res[1]) res[1][11] = w17;
  /* #160: @9 = (@9-@14) */
  w9 -= w14;
  /* #161: @9 = (@9+@37) */
  w9 += w37;
  /* #162: @9 = (@9-@39) */
  w9 -= w39;
  /* #163: @9 = (@9+@3) */
  w9 += w3;
  /* #164: output[1][12] = @9 */
  if (res[1]) res[1][12] = w9;
  /* #165: @2 = (@2+@10) */
  w2 += w10;
  /* #166: @2 = (@2-@20) */
  w2 -= w20;
  /* #167: @2 = (@2-@40) */
  w2 -= w40;
  /* #168: @2 = (@2+@4) */
  w2 += w4;
  /* #169: output[1][13] = @2 */
  if (res[1]) res[1][13] = w2;
  /* #170: output[1][14] = @5 */
  if (res[1]) res[1][14] = w5;
  /* #171: output[1][15] = @6 */
  if (res[1]) res[1][15] = w6;
  /* #172: output[1][16] = @7 */
  if (res[1]) res[1][16] = w7;
  /* #173: @41 = zeros(17x17,41nz) */
  casadi_clear(w41, 41);
  /* #174: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #175: @42 = ones(17x1,9nz) */
  casadi_fill(w42, 9, 1.);
  /* #176: {@7, NULL, NULL, NULL, @6, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@42) */
  w7 = w42[0];
  w6 = w42[1];
  w5 = w42[5];
  /* #177: @43 = 00 */
  /* #178: @44 = 00 */
  /* #179: @45 = 00 */
  /* #180: @2 = vertcat(@7, @43, @44, @45) */
  rr=(&w2);
  *rr++ = w7;
  /* #181: @7 = @2' */
  casadi_copy((&w2), 1, (&w7));
  /* #182: @23 = mac(@7,@26,@23) */
  casadi_mtimes((&w7), casadi_s2, w26, casadi_s1, w23, casadi_s0, w, 0);
  /* #183: @23 = @23' */
  /* #184: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #185: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #186: @2 = @2' */
  /* #187: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #188: @24 = mac(@2,@32,@24) */
  casadi_mtimes((&w2), casadi_s2, w32, casadi_s1, w24, casadi_s0, w, 0);
  /* #189: @24 = @24' */
  /* #190: @23 = (@23+@24) */
  for (i=0, rr=w23, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #191: {@2, @7, @4, @40} = vertsplit(@23) */
  w2 = w23[0];
  w7 = w23[1];
  w4 = w23[2];
  w40 = w23[3];
  /* #192: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #193: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #194: @20 = @6[0] */
  for (rr=(&w20), ss=(&w6)+0; ss!=(&w6)+1; ss+=1) *rr++ = *ss;
  /* #195: @20 = (-@20) */
  w20 = (- w20 );
  /* #196: @6 = @20' */
  casadi_copy((&w20), 1, (&w6));
  /* #197: @34 = mac(@6,@22,@34) */
  casadi_mtimes((&w6), casadi_s5, w22, casadi_s4, w34, casadi_s3, w, 0);
  /* #198: @34 = @34' */
  /* #199: @21 = zeros(1x3) */
  casadi_clear(w21, 3);
  /* #200: @20 = @20' */
  /* #201: @21 = mac(@20,@35,@21) */
  casadi_mtimes((&w20), casadi_s5, w35, casadi_s4, w21, casadi_s3, w, 0);
  /* #202: @21 = @21' */
  /* #203: @34 = (@34+@21) */
  for (i=0, rr=w34, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #204: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #205: (@15[:3] += @34) */
  for (rr=w15+0, ss=w34; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #206: {@20, @6, @10, @9, @3, @39, @37, @14, @17, @12, @38, @11, @18} = vertsplit(@15) */
  w20 = w15[0];
  w6 = w15[1];
  w10 = w15[2];
  w9 = w15[3];
  w3 = w15[4];
  w39 = w15[5];
  w37 = w15[6];
  w14 = w15[7];
  w17 = w15[8];
  w12 = w15[9];
  w38 = w15[10];
  w11 = w15[11];
  w18 = w15[12];
  /* #207: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #208: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #209: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #210: @43 = 00 */
  /* #211: @44 = 00 */
  /* #212: @45 = 00 */
  /* #213: @8 = horzcat(@5, @43, @44, @45) */
  rr=(&w8);
  *rr++ = w5;
  /* #214: @8 = @8' */
  /* #215: @43 = 00 */
  /* #216: @44 = 00 */
  /* #217: @45 = 00 */
  /* #218: @13 = horzcat(@43, @5, @44, @45) */
  rr=(&w13);
  *rr++ = w5;
  /* #219: @13 = @13' */
  /* #220: @44 = 00 */
  /* #221: @46 = 00 */
  /* #222: @19 = horzcat(@45, @44, @5, @46) */
  rr=(&w19);
  *rr++ = w5;
  /* #223: @19 = @19' */
  /* #224: @45 = 00 */
  /* #225: @47 = horzcat(@44, @45, @43, @5) */
  rr=(&w47);
  *rr++ = w5;
  /* #226: @47 = @47' */
  /* #227: @28 = horzcat(@8, @13, @19, @47) */
  rr=w28;
  *rr++ = w8;
  *rr++ = w13;
  *rr++ = w19;
  *rr++ = w47;
  /* #228: @29 = @28' */
  casadi_trans(w28,casadi_s6, w29, casadi_s6, iw);
  /* #229: @24 = mac(@29,@27,@24) */
  casadi_mtimes(w29, casadi_s6, w27, casadi_s7, w24, casadi_s7, w, 0);
  /* #230: @34 = @24[1:4] */
  for (rr=w34, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #231: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #232: @34 = @24[1:4] */
  for (rr=w34, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #233: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #234: @8 = @24[0] */
  for (rr=(&w8), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #235: @8 = (-@8) */
  w8 = (- w8 );
  /* #236: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #237: @8 = (-@8) */
  w8 = (- w8 );
  /* #238: (@23[0] += @8) */
  for (rr=w23+0, ss=(&w8); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #239: @36 = mac(@23,@25,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #240: @31 = @36' */
  for (i=0, rr=w31, cs=w36; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #241: {@23, @24, @29, @28} = horzsplit(@31) */
  casadi_copy(w31, 4, w23);
  casadi_copy(w31+4, 4, w24);
  casadi_copy(w31+8, 4, w29);
  casadi_copy(w31+12, 4, w28);
  /* #242: @28 = @28' */
  /* #243: {@8, @13, @19, @47} = horzsplit(@28) */
  w8 = w28[0];
  w13 = w28[1];
  w19 = w28[2];
  w47 = w28[3];
  /* #244: @29 = @29' */
  /* #245: {@5, @48, @49, @50} = horzsplit(@29) */
  w5 = w29[0];
  w48 = w29[1];
  w49 = w29[2];
  w50 = w29[3];
  /* #246: @47 = (@47+@49) */
  w47 += w49;
  /* #247: @24 = @24' */
  /* #248: {@49, @51, @52, @53} = horzsplit(@24) */
  w49 = w24[0];
  w51 = w24[1];
  w52 = w24[2];
  w53 = w24[3];
  /* #249: @47 = (@47+@51) */
  w47 += w51;
  /* #250: @23 = @23' */
  /* #251: {@51, @54, @55, @56} = horzsplit(@23) */
  w51 = w23[0];
  w54 = w23[1];
  w55 = w23[2];
  w56 = w23[3];
  /* #252: @47 = (@47+@51) */
  w47 += w51;
  /* #253: @47 = (@47+@37) */
  w47 += w37;
  /* #254: @19 = (@19-@50) */
  w19 -= w50;
  /* #255: @19 = (@19+@49) */
  w19 += w49;
  /* #256: @19 = (@19-@54) */
  w19 -= w54;
  /* #257: @19 = (@19+@14) */
  w19 += w14;
  /* #258: @5 = (@5-@13) */
  w5 -= w13;
  /* #259: @5 = (@5+@53) */
  w5 += w53;
  /* #260: @5 = (@5-@55) */
  w5 -= w55;
  /* #261: @5 = (@5+@17) */
  w5 += w17;
  /* #262: @8 = (@8+@48) */
  w8 += w48;
  /* #263: @8 = (@8-@52) */
  w8 -= w52;
  /* #264: @8 = (@8-@56) */
  w8 -= w56;
  /* #265: @8 = (@8+@12) */
  w8 += w12;
  /* #266: @57 = vertcat(@2, @7, @4, @40, @20, @6, @10, @9, @3, @39, @47, @19, @5, @8, @38, @11, @18) */
  rr=w57;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w40;
  *rr++ = w20;
  *rr++ = w6;
  *rr++ = w10;
  *rr++ = w9;
  *rr++ = w3;
  *rr++ = w39;
  *rr++ = w47;
  *rr++ = w19;
  *rr++ = w5;
  *rr++ = w8;
  *rr++ = w38;
  *rr++ = w11;
  *rr++ = w18;
  /* #267: @58 = @57[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w58, ss=w57; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #268: (@41[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @58) */
  for (cii=casadi_s9, rr=w41, ss=w58; cii!=casadi_s9+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #269: @58 = @57[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w58, ss=w57; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #270: (@41[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @58) */
  for (cii=casadi_s10, rr=w41, ss=w58; cii!=casadi_s10+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #271: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #272: @44 = 00 */
  /* #273: @34 = ones(17x1,3nz) */
  casadi_fill(w34, 3, 1.);
  /* #274: {NULL, @2, NULL, NULL, NULL, @7, NULL, NULL, NULL, NULL, NULL, @4, NULL, NULL, NULL, NULL, NULL} = vertsplit(@34) */
  w2 = w34[0];
  w7 = w34[1];
  w4 = w34[2];
  /* #275: @45 = 00 */
  /* #276: @43 = 00 */
  /* #277: @40 = vertcat(@44, @2, @45, @43) */
  rr=(&w40);
  *rr++ = w2;
  /* #278: @2 = @40' */
  casadi_copy((&w40), 1, (&w2));
  /* #279: @23 = mac(@2,@26,@23) */
  casadi_mtimes((&w2), casadi_s11, w26, casadi_s1, w23, casadi_s0, w, 0);
  /* #280: @23 = @23' */
  /* #281: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #282: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #283: @40 = @40' */
  /* #284: @40 = (@0*@40) */
  w40  = (w0*w40);
  /* #285: @24 = mac(@40,@32,@24) */
  casadi_mtimes((&w40), casadi_s11, w32, casadi_s1, w24, casadi_s0, w, 0);
  /* #286: @24 = @24' */
  /* #287: @23 = (@23+@24) */
  for (i=0, rr=w23, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #288: {@40, @2, @20, @6} = vertsplit(@23) */
  w40 = w23[0];
  w2 = w23[1];
  w20 = w23[2];
  w6 = w23[3];
  /* #289: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #290: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #291: @10 = @7[0] */
  for (rr=(&w10), ss=(&w7)+0; ss!=(&w7)+1; ss+=1) *rr++ = *ss;
  /* #292: @10 = (-@10) */
  w10 = (- w10 );
  /* #293: @7 = @10' */
  casadi_copy((&w10), 1, (&w7));
  /* #294: @34 = mac(@7,@22,@34) */
  casadi_mtimes((&w7), casadi_s12, w22, casadi_s4, w34, casadi_s3, w, 0);
  /* #295: @34 = @34' */
  /* #296: @21 = zeros(1x3) */
  casadi_clear(w21, 3);
  /* #297: @10 = @10' */
  /* #298: @21 = mac(@10,@35,@21) */
  casadi_mtimes((&w10), casadi_s12, w35, casadi_s4, w21, casadi_s3, w, 0);
  /* #299: @21 = @21' */
  /* #300: @34 = (@34+@21) */
  for (i=0, rr=w34, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #301: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #302: (@15[:3] += @34) */
  for (rr=w15+0, ss=w34; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #303: {@10, @7, @9, @3, @39, @47, @19, @5, @8, @38, @11, @18, @12} = vertsplit(@15) */
  w10 = w15[0];
  w7 = w15[1];
  w9 = w15[2];
  w3 = w15[3];
  w39 = w15[4];
  w47 = w15[5];
  w19 = w15[6];
  w5 = w15[7];
  w8 = w15[8];
  w38 = w15[9];
  w11 = w15[10];
  w18 = w15[11];
  w12 = w15[12];
  /* #304: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #305: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #306: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #307: @44 = 00 */
  /* #308: @56 = (-@4) */
  w56 = (- w4 );
  /* #309: @45 = 00 */
  /* #310: @43 = 00 */
  /* #311: @52 = horzcat(@44, @56, @45, @43) */
  rr=(&w52);
  *rr++ = w56;
  /* #312: @52 = @52' */
  /* #313: @45 = 00 */
  /* #314: @43 = 00 */
  /* #315: @56 = horzcat(@4, @44, @45, @43) */
  rr=(&w56);
  *rr++ = w4;
  /* #316: @56 = @56' */
  /* #317: @45 = 00 */
  /* #318: @48 = (-@4) */
  w48 = (- w4 );
  /* #319: @17 = horzcat(@43, @45, @44, @48) */
  rr=(&w17);
  *rr++ = w48;
  /* #320: @17 = @17' */
  /* #321: @43 = 00 */
  /* #322: @48 = horzcat(@45, @43, @4, @44) */
  rr=(&w48);
  *rr++ = w4;
  /* #323: @48 = @48' */
  /* #324: @29 = horzcat(@52, @56, @17, @48) */
  rr=w29;
  *rr++ = w52;
  *rr++ = w56;
  *rr++ = w17;
  *rr++ = w48;
  /* #325: @28 = @29' */
  casadi_trans(w29,casadi_s13, w28, casadi_s13, iw);
  /* #326: @24 = mac(@28,@27,@24) */
  casadi_mtimes(w28, casadi_s13, w27, casadi_s7, w24, casadi_s7, w, 0);
  /* #327: @34 = @24[1:4] */
  for (rr=w34, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #328: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #329: @34 = @24[1:4] */
  for (rr=w34, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #330: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #331: @52 = @24[0] */
  for (rr=(&w52), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #332: @52 = (-@52) */
  w52 = (- w52 );
  /* #333: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #334: @52 = (-@52) */
  w52 = (- w52 );
  /* #335: (@23[0] += @52) */
  for (rr=w23+0, ss=(&w52); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #336: @31 = mac(@23,@25,@31) */
  for (i=0, rr=w31; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #337: @36 = @31' */
  for (i=0, rr=w36, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #338: {@23, @24, @28, @29} = horzsplit(@36) */
  casadi_copy(w36, 4, w23);
  casadi_copy(w36+4, 4, w24);
  casadi_copy(w36+8, 4, w28);
  casadi_copy(w36+12, 4, w29);
  /* #339: @29 = @29' */
  /* #340: {@52, @56, @17, @48} = horzsplit(@29) */
  w52 = w29[0];
  w56 = w29[1];
  w17 = w29[2];
  w48 = w29[3];
  /* #341: @28 = @28' */
  /* #342: {@4, @55, @53, @13} = horzsplit(@28) */
  w4 = w28[0];
  w55 = w28[1];
  w53 = w28[2];
  w13 = w28[3];
  /* #343: @48 = (@48+@53) */
  w48 += w53;
  /* #344: @24 = @24' */
  /* #345: {@53, @14, @54, @49} = horzsplit(@24) */
  w53 = w24[0];
  w14 = w24[1];
  w54 = w24[2];
  w49 = w24[3];
  /* #346: @48 = (@48+@14) */
  w48 += w14;
  /* #347: @23 = @23' */
  /* #348: {@14, @50, @37, @51} = horzsplit(@23) */
  w14 = w23[0];
  w50 = w23[1];
  w37 = w23[2];
  w51 = w23[3];
  /* #349: @48 = (@48+@14) */
  w48 += w14;
  /* #350: @48 = (@48+@19) */
  w48 += w19;
  /* #351: @17 = (@17-@13) */
  w17 -= w13;
  /* #352: @17 = (@17+@53) */
  w17 += w53;
  /* #353: @17 = (@17-@50) */
  w17 -= w50;
  /* #354: @17 = (@17+@5) */
  w17 += w5;
  /* #355: @4 = (@4-@56) */
  w4 -= w56;
  /* #356: @4 = (@4+@49) */
  w4 += w49;
  /* #357: @4 = (@4-@37) */
  w4 -= w37;
  /* #358: @4 = (@4+@8) */
  w4 += w8;
  /* #359: @52 = (@52+@55) */
  w52 += w55;
  /* #360: @52 = (@52-@54) */
  w52 -= w54;
  /* #361: @52 = (@52-@51) */
  w52 -= w51;
  /* #362: @52 = (@52+@38) */
  w52 += w38;
  /* #363: @57 = vertcat(@40, @2, @20, @6, @10, @7, @9, @3, @39, @47, @48, @17, @4, @52, @11, @18, @12) */
  rr=w57;
  *rr++ = w40;
  *rr++ = w2;
  *rr++ = w20;
  *rr++ = w6;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w3;
  *rr++ = w39;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w17;
  *rr++ = w4;
  *rr++ = w52;
  *rr++ = w11;
  *rr++ = w18;
  *rr++ = w12;
  /* #364: @58 = @57[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w58, ss=w57; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #365: (@41[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @58) */
  for (cii=casadi_s14, rr=w41, ss=w58; cii!=casadi_s14+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #366: @58 = @57[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w58, ss=w57; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #367: (@41[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @58) */
  for (cii=casadi_s15, rr=w41, ss=w58; cii!=casadi_s15+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #368: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #369: @45 = 00 */
  /* #370: @43 = 00 */
  /* #371: @34 = ones(17x1,3nz) */
  casadi_fill(w34, 3, 1.);
  /* #372: {NULL, NULL, @40, NULL, NULL, NULL, @2, NULL, NULL, NULL, NULL, NULL, @20, NULL, NULL, NULL, NULL} = vertsplit(@34) */
  w40 = w34[0];
  w2 = w34[1];
  w20 = w34[2];
  /* #373: @44 = 00 */
  /* #374: @6 = vertcat(@45, @43, @40, @44) */
  rr=(&w6);
  *rr++ = w40;
  /* #375: @40 = @6' */
  casadi_copy((&w6), 1, (&w40));
  /* #376: @23 = mac(@40,@26,@23) */
  casadi_mtimes((&w40), casadi_s16, w26, casadi_s1, w23, casadi_s0, w, 0);
  /* #377: @23 = @23' */
  /* #378: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #379: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #380: @6 = @6' */
  /* #381: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #382: @24 = mac(@6,@32,@24) */
  casadi_mtimes((&w6), casadi_s16, w32, casadi_s1, w24, casadi_s0, w, 0);
  /* #383: @24 = @24' */
  /* #384: @23 = (@23+@24) */
  for (i=0, rr=w23, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #385: {@6, @40, @10, @7} = vertsplit(@23) */
  w6 = w23[0];
  w40 = w23[1];
  w10 = w23[2];
  w7 = w23[3];
  /* #386: @15 = zeros(13x1) */
  casadi_clear(w15, 13);
  /* #387: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #388: @9 = @2[0] */
  for (rr=(&w9), ss=(&w2)+0; ss!=(&w2)+1; ss+=1) *rr++ = *ss;
  /* #389: @9 = (-@9) */
  w9 = (- w9 );
  /* #390: @2 = @9' */
  casadi_copy((&w9), 1, (&w2));
  /* #391: @34 = mac(@2,@22,@34) */
  casadi_mtimes((&w2), casadi_s17, w22, casadi_s4, w34, casadi_s3, w, 0);
  /* #392: @34 = @34' */
  /* #393: @21 = zeros(1x3) */
  casadi_clear(w21, 3);
  /* #394: @9 = @9' */
  /* #395: @21 = mac(@9,@35,@21) */
  casadi_mtimes((&w9), casadi_s17, w35, casadi_s4, w21, casadi_s3, w, 0);
  /* #396: @21 = @21' */
  /* #397: @34 = (@34+@21) */
  for (i=0, rr=w34, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #398: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #399: (@15[:3] += @34) */
  for (rr=w15+0, ss=w34; rr!=w15+3; rr+=1) *rr += *ss++;
  /* #400: {@9, @2, @3, @39, @47, @48, @17, @4, @52, @11, @18, @12, @38} = vertsplit(@15) */
  w9 = w15[0];
  w2 = w15[1];
  w3 = w15[2];
  w39 = w15[3];
  w47 = w15[4];
  w48 = w15[5];
  w17 = w15[6];
  w4 = w15[7];
  w52 = w15[8];
  w11 = w15[9];
  w18 = w15[10];
  w12 = w15[11];
  w38 = w15[12];
  /* #401: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #402: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #403: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #404: @45 = 00 */
  /* #405: @43 = 00 */
  /* #406: @51 = (-@20) */
  w51 = (- w20 );
  /* #407: @44 = 00 */
  /* #408: @54 = horzcat(@45, @43, @51, @44) */
  rr=(&w54);
  *rr++ = w51;
  /* #409: @54 = @54' */
  /* #410: @43 = 00 */
  /* #411: @44 = 00 */
  /* #412: @51 = horzcat(@43, @45, @44, @20) */
  rr=(&w51);
  *rr++ = w20;
  /* #413: @51 = @51' */
  /* #414: @44 = 00 */
  /* #415: @46 = 00 */
  /* #416: @55 = horzcat(@20, @44, @45, @46) */
  rr=(&w55);
  *rr++ = w20;
  /* #417: @55 = @55' */
  /* #418: @20 = (-@20) */
  w20 = (- w20 );
  /* #419: @8 = horzcat(@44, @20, @43, @45) */
  rr=(&w8);
  *rr++ = w20;
  /* #420: @8 = @8' */
  /* #421: @28 = horzcat(@54, @51, @55, @8) */
  rr=w28;
  *rr++ = w54;
  *rr++ = w51;
  *rr++ = w55;
  *rr++ = w8;
  /* #422: @29 = @28' */
  casadi_trans(w28,casadi_s18, w29, casadi_s18, iw);
  /* #423: @24 = mac(@29,@27,@24) */
  casadi_mtimes(w29, casadi_s18, w27, casadi_s7, w24, casadi_s7, w, 0);
  /* #424: @34 = @24[1:4] */
  for (rr=w34, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #425: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #426: @34 = @24[1:4] */
  for (rr=w34, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #427: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #428: @54 = @24[0] */
  for (rr=(&w54), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #429: @54 = (-@54) */
  w54 = (- w54 );
  /* #430: @54 = (2.*@54) */
  w54 = (2.* w54 );
  /* #431: @54 = (-@54) */
  w54 = (- w54 );
  /* #432: (@23[0] += @54) */
  for (rr=w23+0, ss=(&w54); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #433: @36 = mac(@23,@25,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #434: @31 = @36' */
  for (i=0, rr=w31, cs=w36; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #435: {@23, @24, @29, @28} = horzsplit(@31) */
  casadi_copy(w31, 4, w23);
  casadi_copy(w31+4, 4, w24);
  casadi_copy(w31+8, 4, w29);
  casadi_copy(w31+12, 4, w28);
  /* #436: @28 = @28' */
  /* #437: {@54, @51, @55, @8} = horzsplit(@28) */
  w54 = w28[0];
  w51 = w28[1];
  w55 = w28[2];
  w8 = w28[3];
  /* #438: @29 = @29' */
  /* #439: {@20, @37, @49, @56} = horzsplit(@29) */
  w20 = w29[0];
  w37 = w29[1];
  w49 = w29[2];
  w56 = w29[3];
  /* #440: @8 = (@8+@49) */
  w8 += w49;
  /* #441: @24 = @24' */
  /* #442: {@49, @5, @50, @53} = horzsplit(@24) */
  w49 = w24[0];
  w5 = w24[1];
  w50 = w24[2];
  w53 = w24[3];
  /* #443: @8 = (@8+@5) */
  w8 += w5;
  /* #444: @23 = @23' */
  /* #445: {@5, @13, @19, @14} = horzsplit(@23) */
  w5 = w23[0];
  w13 = w23[1];
  w19 = w23[2];
  w14 = w23[3];
  /* #446: @8 = (@8+@5) */
  w8 += w5;
  /* #447: @8 = (@8+@17) */
  w8 += w17;
  /* #448: @55 = (@55-@56) */
  w55 -= w56;
  /* #449: @55 = (@55+@49) */
  w55 += w49;
  /* #450: @55 = (@55-@13) */
  w55 -= w13;
  /* #451: @55 = (@55+@4) */
  w55 += w4;
  /* #452: @20 = (@20-@51) */
  w20 -= w51;
  /* #453: @20 = (@20+@53) */
  w20 += w53;
  /* #454: @20 = (@20-@19) */
  w20 -= w19;
  /* #455: @20 = (@20+@52) */
  w20 += w52;
  /* #456: @54 = (@54+@37) */
  w54 += w37;
  /* #457: @54 = (@54-@50) */
  w54 -= w50;
  /* #458: @54 = (@54-@14) */
  w54 -= w14;
  /* #459: @54 = (@54+@11) */
  w54 += w11;
  /* #460: @57 = vertcat(@6, @40, @10, @7, @9, @2, @3, @39, @47, @48, @8, @55, @20, @54, @18, @12, @38) */
  rr=w57;
  *rr++ = w6;
  *rr++ = w40;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w39;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w8;
  *rr++ = w55;
  *rr++ = w20;
  *rr++ = w54;
  *rr++ = w18;
  *rr++ = w12;
  *rr++ = w38;
  /* #461: @58 = @57[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w58, ss=w57; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #462: (@41[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @58) */
  for (cii=casadi_s19, rr=w41, ss=w58; cii!=casadi_s19+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #463: @58 = @57[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w58, ss=w57; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #464: (@41[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @58) */
  for (cii=casadi_s20, rr=w41, ss=w58; cii!=casadi_s20+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #465: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #466: @44 = 00 */
  /* #467: @43 = 00 */
  /* #468: @45 = 00 */
  /* #469: @59 = ones(17x1,2nz) */
  casadi_fill(w59, 2, 1.);
  /* #470: {NULL, NULL, NULL, @6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @40, NULL, NULL, NULL} = vertsplit(@59) */
  w6 = w59[0];
  w40 = w59[1];
  /* #471: @10 = vertcat(@44, @43, @45, @6) */
  rr=(&w10);
  *rr++ = w6;
  /* #472: @6 = @10' */
  casadi_copy((&w10), 1, (&w6));
  /* #473: @23 = mac(@6,@26,@23) */
  casadi_mtimes((&w6), casadi_s21, w26, casadi_s1, w23, casadi_s0, w, 0);
  /* #474: @23 = @23' */
  /* #475: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #476: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #477: @10 = @10' */
  /* #478: @0 = (@0*@10) */
  w0 *= w10;
  /* #479: @24 = mac(@0,@32,@24) */
  casadi_mtimes((&w0), casadi_s21, w32, casadi_s1, w24, casadi_s0, w, 0);
  /* #480: @24 = @24' */
  /* #481: @23 = (@23+@24) */
  for (i=0, rr=w23, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #482: {@0, @10, @6, @7} = vertsplit(@23) */
  w0 = w23[0];
  w10 = w23[1];
  w6 = w23[2];
  w7 = w23[3];
  /* #483: @44 = 00 */
  /* #484: @43 = 00 */
  /* #485: @45 = 00 */
  /* #486: @46 = 00 */
  /* #487: @60 = 00 */
  /* #488: @61 = 00 */
  /* #489: @32 = zeros(4x4) */
  casadi_clear(w32, 16);
  /* #490: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #491: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #492: @62 = 00 */
  /* #493: @63 = 00 */
  /* #494: @64 = 00 */
  /* #495: @9 = (-@40) */
  w9 = (- w40 );
  /* #496: @2 = horzcat(@62, @63, @64, @9) */
  rr=(&w2);
  *rr++ = w9;
  /* #497: @2 = @2' */
  /* #498: @63 = 00 */
  /* #499: @9 = (-@40) */
  w9 = (- w40 );
  /* #500: @64 = 00 */
  /* #501: @3 = horzcat(@63, @62, @9, @64) */
  rr=(&w3);
  *rr++ = w9;
  /* #502: @3 = @3' */
  /* #503: @65 = 00 */
  /* #504: @9 = horzcat(@64, @40, @62, @65) */
  rr=(&w9);
  *rr++ = w40;
  /* #505: @9 = @9' */
  /* #506: @64 = 00 */
  /* #507: @39 = horzcat(@40, @64, @63, @62) */
  rr=(&w39);
  *rr++ = w40;
  /* #508: @39 = @39' */
  /* #509: @29 = horzcat(@2, @3, @9, @39) */
  rr=w29;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w9;
  *rr++ = w39;
  /* #510: @28 = @29' */
  casadi_trans(w29,casadi_s22, w28, casadi_s22, iw);
  /* #511: @24 = mac(@28,@27,@24) */
  casadi_mtimes(w28, casadi_s22, w27, casadi_s7, w24, casadi_s7, w, 0);
  /* #512: @34 = @24[1:4] */
  for (rr=w34, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #513: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #514: @34 = @24[1:4] */
  for (rr=w34, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #515: (@23[1:4] += @34) */
  for (rr=w23+1, ss=w34; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #516: @2 = @24[0] */
  for (rr=(&w2), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #517: @2 = (-@2) */
  w2 = (- w2 );
  /* #518: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #519: @2 = (-@2) */
  w2 = (- w2 );
  /* #520: (@23[0] += @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #521: @32 = mac(@23,@25,@32) */
  for (i=0, rr=w32; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #522: @26 = @32' */
  for (i=0, rr=w26, cs=w32; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #523: {@23, @25, @24, @28} = horzsplit(@26) */
  casadi_copy(w26, 4, w23);
  casadi_copy(w26+4, 4, w25);
  casadi_copy(w26+8, 4, w24);
  casadi_copy(w26+12, 4, w28);
  /* #524: @28 = @28' */
  /* #525: {@2, @3, @9, @39} = horzsplit(@28) */
  w2 = w28[0];
  w3 = w28[1];
  w9 = w28[2];
  w39 = w28[3];
  /* #526: @24 = @24' */
  /* #527: {@40, @47, @48, @8} = horzsplit(@24) */
  w40 = w24[0];
  w47 = w24[1];
  w48 = w24[2];
  w8 = w24[3];
  /* #528: @39 = (@39+@48) */
  w39 += w48;
  /* #529: @25 = @25' */
  /* #530: {@48, @55, @20, @54} = horzsplit(@25) */
  w48 = w25[0];
  w55 = w25[1];
  w20 = w25[2];
  w54 = w25[3];
  /* #531: @39 = (@39+@55) */
  w39 += w55;
  /* #532: @23 = @23' */
  /* #533: {@55, @18, @12, @38} = horzsplit(@23) */
  w55 = w23[0];
  w18 = w23[1];
  w12 = w23[2];
  w38 = w23[3];
  /* #534: @39 = (@39+@55) */
  w39 += w55;
  /* #535: @9 = (@9-@8) */
  w9 -= w8;
  /* #536: @9 = (@9+@48) */
  w9 += w48;
  /* #537: @9 = (@9-@18) */
  w9 -= w18;
  /* #538: @40 = (@40-@3) */
  w40 -= w3;
  /* #539: @40 = (@40+@54) */
  w40 += w54;
  /* #540: @40 = (@40-@12) */
  w40 -= w12;
  /* #541: @2 = (@2+@47) */
  w2 += w47;
  /* #542: @2 = (@2-@20) */
  w2 -= w20;
  /* #543: @2 = (@2-@38) */
  w2 -= w38;
  /* #544: @64 = 00 */
  /* #545: @63 = 00 */
  /* #546: @62 = 00 */
  /* #547: @66 = vertcat(@0, @10, @6, @7, @44, @43, @45, @46, @60, @61, @39, @9, @40, @2, @64, @63, @62) */
  rr=w66;
  *rr++ = w0;
  *rr++ = w10;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w39;
  *rr++ = w9;
  *rr++ = w40;
  *rr++ = w2;
  /* #548: @67 = @66[:8] */
  for (rr=w67, ss=w66+0; ss!=w66+8; ss+=1) *rr++ = *ss;
  /* #549: (@41[:50:25;12:16] = @67) */
  for (rr=w41+0, ss=w67; rr!=w41+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *ss++;
  /* #550: @67 = @66[:8] */
  for (rr=w67, ss=w66+0; ss!=w66+8; ss+=1) *rr++ = *ss;
  /* #551: (@41[:50:25;3:19:4] = @67) */
  for (rr=w41+0, ss=w67; rr!=w41+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *ss++;
  /* #552: @68 = @41' */
  casadi_trans(w41,casadi_s23, w68, casadi_s23, iw);
  /* #553: output[2][0] = @68 */
  casadi_copy(w68, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s24;
    case 1: return casadi_s7;
    case 2: return casadi_s25;
    case 3: return casadi_s24;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s26;
    case 1: return casadi_s27;
    case 2: return casadi_s23;
    case 3: return casadi_s25;
    case 4: return casadi_s28;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 311;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
